### ISSUE TITLE
chain.address_type_txes() fails when address type count = 0

### ISSUE THREAD

**Issue by satwo** [citp/BlockSci#104]
When calling chain.address_type_txes() with a block range that has 0 transactions of the specified address type, the script hangs and eventually throws a "std::bad_alloc" error.

Example:
txes_protocol = chain.address_type_txes(511645, 511646, blocksci.address_type.nulldata)`

Error:
MemoryError: std::bad_alloc

I've also reproduced this behavior with address type of multisig, eg. block 170.

**Comment by hkalodner** [comment]
Huh interesting. I've never hit that before, but I can recreate it. If it's the same problem you're hitting, it looks a like a bug that occurs in the `segmentChain` method which `address_type_txes` depends on which occurs whenever the range of blocks contains fewer transactions than your machine has CPUs. I'm working on a fix now.

Incidentally in the just released BlockSci v0.5, `chain.address_type_txes()` has been replaced by `chain.blocks.txes.including_output_of_type(blocksci.address_type.nulldata)` which returns a [`blocksci.TxIterator`](https://citp.github.io/BlockSci/reference/chain/iterators/TxIterator.html) object.

**Comment by satwo** [comment]
Great, thanks for the quick fix!!

Look forward to checking out v0.5.
