### ISSUE TITLE
Missing slash in local compilation instructions

### ISSUE THREAD

**Issue by brickinedifice** [citp/BlockSci#105]
I believe there is a missing slash in the second last line of this command on [https://citp.github.io/BlockSci/compiling.html](url)

`sudo apt install cmake libtool autoconf libboost-filesystem-dev libboost-iostreams-dev \
libboost-serialization-dev libboost-thread-dev libboost-test-dev  libssl-dev libjsoncpp-dev \
libcurl4-openssl-dev libjsoncpp-dev libjsonrpccpp-dev libsnappy-dev zlib1g-dev libbz2-dev
liblz4-dev libzstd-dev libjemalloc-dev libsparsehash-dev python3-dev python3-pip`

**Comment by hkalodner** [comment]
Whoops good catch thanks
