### ISSUE TITLE
RuntimeError when executing Python method chain.map_blocks() from iPython Jupyter Notebook

### ISSUE THREAD

**Issue by boshmaf** [citp/BlockSci#109]
BlockSci version 0.5.0 running on a VM with 16 threads. This is specific to iPython Juputer Playbook. When executed as a Python script, the exception is not thrown. Might have to do with multiprocessing and iPython hitting some limit.

When executing this Python line from the sample notebook,

`%time net_coins_per_block = chain.map_blocks(lambda block: block.net_address_type_value())`

the following exception is thrown:

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/export/data/projects/BlockSci/blockscipy/blocksci/__init__.py", line 58, in real_map_func
    local_chain = Blockchain(input[1])
  File "/export/data/projects/BlockSci/blockscipy/blocksci/__init__.py", line 172, in new_init
    old_init(self, loc)
RuntimeError: Could not open address index with error: While opendir: /export/data/projects/BlockSci/data/addressesDb: Too many open files
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>()

/export/data/projects/BlockSci/blockscipy/blocksci/__init__.py in map_blocks(self, blockFunc, start, end, cpu_count)
    106         return accum
    107 
--> 108     return mapreduce_block_ranges(self, mapFunc, reduceFunc, missing_param, start, end, cpu_count)
    109 
    110 def filter_blocks(self, filterFunc, start = None, end = None, cpu_count=psutil.cpu_count()):

/export/data/projects/BlockSci/blockscipy/blocksci/__init__.py in mapreduce_block_ranges(chain, mapFunc, reduceFunc, init, start, end, cpu_count)
     67         results_future = p.map_async(real_map_func, segments[1:])
     68         first = mapFunc(chain[raw_segments[0][0]:raw_segments[0][1]])
---> 69         results = results_future.get()
     70         results = [Unpickler(res, chain).load() for res in results]
     71     results.insert(0, first)

/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

RuntimeError: Could not open address index with error: While opendir: /export/data/projects/BlockSci/data/addressesDb: Too many open files
```

**Comment by hkalodner** [comment]
The issue appears to be with the number of files RocksDb opens. When using the multiprocess API, a blocksci instance is opened in every process which leaves to too many files being opened on some systems. In the next version I can try to figure out whether there is some way to limit the number of files RocksDB opens.

Other than that the two main ways to get around this issue is by passing a lower `cpu_count` to the `map_blocks` function or by increasing the open file descriptor limit for your OS. The way to do this is different depending on what OS you're using, but it shouldn't be too hard to find instructions.

**Comment by sirpy** [comment]
I've had the same issue running jupyter as a systemd service
it needed special config in the service conf as it didnt respect global limits of open files.
so either you need to change you limits.conf or change the service conf to increase number of open files

**Comment by ddolgov** [comment]
Same issue running on 8-threaded Ubuntu/Azure:
`Linux xxx-blocksci 4.15.0-1014-azure #14~16.04.1-Ubuntu SMP Thu Jun 14 15:42:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Same behavior observed in python interpreter, a script or jupyter.

I don't think I am anywhere close to the system's open file descriptor limit:
```
xxx@xxx-blocksci:~$ cat /proc/sys/fs/file-nr
4224    0       6579321
```

**Comment by ddolgov** [comment]
I've had the same error on an Azure/Ubuntu.

To raise the open file descriptor limit run something like `ulimit -n 64000` (mine was set to 1024 by default) before running the script or python interpreter. For a permanent increase, see [https://underyx.me/2015/05/18/raising-the-maximum-number-of-file-descriptors](this)
