### ISSUE TITLE
Data directory not recognized

### ISSUE THREAD

**Issue by ckinkeldey** [citp/BlockSci#110]
Hi, I installed BlockSci from scratch, started the parser and it all looked good.
But when I try to access the chain in python, I get:
```
>>> import blocksci
>>> chain = blocksci.Blockchain("mypath_to_bitcoin-data")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ck/BlockSci/blockscipy/blocksci/__init__.py", line 172, in new_init
  old_init(self, loc)
  RuntimeError: Error, data directory does not contain config.ini. Are you sure mypath_to_bitcoin-data was the output directory of blocksci_parser?
```
The data directory looks OK but there is no `config.ini`. It is supposed to be there?
Thanks!

**Comment by boshmaf** [comment]
@ckinkeldey: Try adding a slash at the end of the path, as the function expects a directory not a file, like this:
```
chain = blocksci.Blockchain("mypath_to_bitcoin-data/")
```

**Comment by boshmaf** [comment]
This was an issue on older releases. Are you sure you have pulled the latest?

Also, a work around this problem is to create the file yourself and rerun the parser. Just add this single line in `config.ini`:
```
version=4
```
