### ISSUE TITLE
totalOutWithoutSelfChurn() in BlockSci/clustering/src/python_cluster/python_interface.cpp runs very slowly. However, can be easily sped up.

### ISSUE THREAD

**Issue by zaczw** [citp/BlockSci#111]
Hi BlockSci Team,

totalOutWithoutSelfChurn() in BlockSci/clustering/src/python_cluster/python_interface.cpp currently runs very slowly. However, I think I know why and how it can be easily fixed. 

The key is that if you apply totalOutWithoutSelfChurn() to a block that have inputs associated with addresses in the "supercluster" (cluster index 32, as described in pg 12 of the BlockSci whitepaper), then cluster.getSize() in line 47 of BlockSci/clustering/src/python_cluster/python_interface.cpp calculates the size of the supercluster. This takes a long time, and greatly slows down totalOutWithoutSelfChurn().

I have attached the pdf version of a jupyter notebook that I used to conduct experiments that led me to this conclusion, as well as a photo of the line that is causing the problem.

My suggestion for the BlockSci team will be to code up the filtering out of the megacluster as cluster.index() != 32 or something like that instead of cluster.getSize() < 30000 in line 47. Otherwise, totalOutWithoutSelfChurn() will continue to run too slowly to be useful.

Best,
Zachry 

![cluster_get_size](https://user-images.githubusercontent.com/7476244/39972327-6be615e4-56d2-11e8-8344-7fc60e44a58f.PNG)
[slow_bc_cluster_size_calc.pdf](https://github.com/citp/BlockSci/files/1998988/slow_bc_cluster_size_calc.pdf)

**Comment by hkalodner** [comment]
Ah good catch. I think this is a regression in v0.5. I think the proper solution is to use `cluster.getTypeEquivSize()` instead which is constant time and gives an approximation for the size of the cluster. That function has the behavior that `cluster.getSize()`. The difference between the two functions is mostly an implementation detail of how clustering works and the difficulty of defining the size of given cluster.

I'll fix this tonight or tomorrow.

**Comment by zaczw** [comment]
Awesome, glad to hear this! Just to confirm, when you push the fix, will it be fixed on the AWS AMI as well?
