### ISSUE TITLE
BlockSci Demo: RuntimeError: Could not open address index with error: While opendir: ~/bitcoin-data/addressesDb: Too many open files

### ISSUE THREAD

**Issue by zjfheart** [citp/BlockSci#113]
There is an error of  " Measuring different types of address use"

Here is the full errors report: 
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/jingfeng/BlockSci/blockscipy/blocksci/__init__.py", line 58, in real_map_func
    local_chain = Blockchain(input[1])
  File "/home/jingfeng/BlockSci/blockscipy/blocksci/__init__.py", line 172, in new_init
    old_init(self, loc)
RuntimeError: Could not open address index with error: While opendir: /home/jingfeng/bitcoin-data/addressesDb: Too many open files
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>()

~/BlockSci/blockscipy/blocksci/__init__.py in map_blocks(self, blockFunc, start, end, cpu_count)
    106         return accum
    107 
--> 108     return mapreduce_block_ranges(self, mapFunc, reduceFunc, missing_param, start, end, cpu_count)
    109 
    110 def filter_blocks(self, filterFunc, start = None, end = None, cpu_count=psutil.cpu_count()):

~/BlockSci/blockscipy/blocksci/__init__.py in mapreduce_block_ranges(chain, mapFunc, reduceFunc, init, start, end, cpu_count)
     67         results_future = p.map_async(real_map_func, segments[1:])
     68         first = mapFunc(chain[raw_segments[0][0]:raw_segments[0][1]])
---> 69         results = results_future.get()
     70         results = [Unpickler(res, chain).load() for res in results]
     71     results.insert(0, first)

/usr/local/lib/python3.5/dist-packages/multiprocess/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

RuntimeError: Could not open address index with error: While opendir: /home/jingfeng/bitcoin-data/addressesDb: Too many open files

**Comment by hkalodner** [comment]
This duplicates #109. Closing this and continuing the discussion there.
