### ISSUE TITLE
most_valuable_addresses is too slow

### ISSUE THREAD

**Issue by foonsun** [citp/BlockSci#114]
I have use the ami and the same aws instance r4.2xlarge  in aws.now the problem is calculating the most_valueable_addresses through the jumpter is too slow.I have run it for one day.But it still give the results.Any suggestions would be appreciated.

**Comment by foonsun** [comment]
It has run for over three days.but still not end.
Any suggestions?

**Comment by foonsun** [comment]
Hope someone could help me.

**Comment by hkalodner** [comment]
Hey @foonsun, sorry I shouldn't have included that code for this release. I'm playing around with ways of making this more performant, but the current API is too slow to function. I'll hopefully provide a way to do this in the next release.

**Comment by foonsun** [comment]
@hkalodner thanks for your help.
