### ISSUE TITLE
Problem while installing BlockSci using pip3

### ISSUE THREAD

**Issue by heojae91** [citp/BlockSci#115]
I'm using Mac, and BlockSci worked well in previous version. To upgrade my BlockSci module, I downloaded new version of BlockSci and remove all the data from previous version according to [this guide](https://citp.github.io/BlockSci/compiling.html) and tried `sudo -H pip3 install -e blockscipy` but it doesn't work for me. It emits

```
Command "/usr/local/opt/python/bin/python3.6 -c "import setuptools,
tokenize;__file__='/Users/jayheo/Lab/BlockSci/blockscipy/setup.py';f=getattr(tokenize, 'open', open)
(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop
--no-deps" failed with error code 1 in /Users/jayheo/Lab/BlockSci/blockscipy/
```

The error log is
```
...
In file included from /usr/local/include/blocksci/address/address.hpp:20:
    /usr/local/include/range/v3/view/any_view.hpp:498:53: error: no matching function for call to object of type 'const _size_::fn'
                        return static_cast<std::size_t>(ranges::size(range_box_t::get()));
                                                        ^~~~~~~~~~~~
    /usr/local/include/range/v3/view/any_view.hpp:474:17: note: in instantiation of member function 'ranges::v3::detail::any_view_impl<ranges::v3::transform_view<ranges::v3::any_view<blocksci::Cluster, 31, void>, (lambda at /Users/jayheo/Lab/BlockSci/blockscipy/src/range_apply_py.hpp:77:69)>, long long, 31>::size' requested here
                    any_view_impl(Rng rng)
...
```

This is full log of my install sequence : [log.txt](https://github.com/citp/BlockSci/files/2048277/log.txt)

Anyone can give me some suggestion for fixing this error?

**Comment by heojae91** [comment]
I solved the problem with using `sudo cp -r libs/range-v3/include/meta /usr/local/include` and `sudo cp -r libs/range-v3/include/range /usr/local/include`. Installation using pip3 works nicely.

But when I import blocksci module in jupyter notebook,  it says there is no module named blocksci and the blocksci directory is not appeared in BlockSci/Notebooks. I did the same sequence on my desktop which runs Ubuntu 16.04, same problem happened.

**Comment by hkalodner** [comment]
Hmm it looks like the original probably is that '/usr/local/include/range' should also be deleted. I'll add this to the removing the old version instruction. I shifted BlockSci over to installing range-v3 as a sub project rather than a separate installation like it was before.

The updated v0.5 install instructions should install BlockSci into the normal python module directory rather than in BlockSci/Notebooks.

Did you run `CC=gcc-7 CXX=g++-7 sudo -H pip3 install -e blockscipy` as described in the v0.5 compilation instructions?

**Comment by heojae91** [comment]
Yes, I followed the instructions. I also checked the version of the compilers and cmake.

On Ubuntu, I installed blociscipy using pip3 after make / make install with your instruction but it fails. It seems like the compiler cannot recognize C++ 17 style although I'm compiling with gcc-7 and g++-7.

Error log : 
```
...
    /home/jayheo/blockchain/BlockSci/blockscipy/src/range_conversion.hpp:225:8: error: expected ‘(’ before ‘constexpr’
         if constexpr (is_optional<value_type>::value) {
            ^
    /home/jayheo/blockchain/BlockSci/blockscipy/src/cluster/cluster/cluster_range.cpp:17:1: error: expected ‘}’ at end of input
     }
     ^
    /home/jayheo/blockchain/BlockSci/blockscipy/src/cluster/cluster/cluster_range.cpp:17:1: warning: no return statement in function returning non-void [-Wreturn-type]
    In file included from /home/jayheo/blockchain/BlockSci/blockscipy/src/self_apply_py.hpp:12:0,
                     from /home/jayheo/blockchain/BlockSci/blockscipy/src/cluster/cluster/cluster_py.cpp:11:
    /home/jayheo/blockchain/BlockSci/blockscipy/src/range_conversion.hpp: In function ‘constexpr bool isNestedOptionalRange()’:
    /home/jayheo/blockchain/BlockSci/blockscipy/src/range_conversion.hpp:225:8: error: expected ‘(’ before ‘constexpr’
         if constexpr (is_optional<value_type>::value) {
            ^
    /home/jayheo/blockchain/BlockSci/blockscipy/src/cluster/cluster/cluster_py.cpp:86:1: error: expected ‘}’ at end of input
     }
     ^
...
```

And I'm using : 
Ubuntu 16.04
cmake 3.11.2
gcc-7  7.3.0
g++-7 7.3.0

I think the version is correct, but I cannot understand why the error occurred.

**Comment by annonch** [comment]
I had the above problem, i had two cmake versions, one I installed myself and one from the ubuntu package that was outdated. uninstalling cmake and then doing something like `sudo ln -s /media/bitcoin/tools/cmake/cmake-3.11.3-Linux-x86_64/bin/* /usr/local/bin ` fixed it for me. Also I found that just having set the CC and CXX environment variables was not enough and I needed to link them in /usr/bin/cc and user/bin/c++

**Comment by heojae91** [comment]
It caused by version issue of gcc and g++. So, I followed instruction on #128 and it worked.
