### ISSUE TITLE
code for velocity calculation

### ISSUE THREAD

**Issue by andreasp888** [citp/BlockSci#116]
Hello,
Would you please provide the code you used to estimate the velocity of bitcoin in your working paper? For instance, how did you create Figure 12: two estimates of the velocity of bitcoins?
Thank you.

**Comment by ujnamss** [comment]
@hkalodner - Any inputs on this?

**Comment by brockelmore** [comment]
@andreasp888 Don't know if you are still interested, but I just posted my solution for this in a similar issue. I created a function to create the estimated Tx Volume per block. You can change heuristics and what not to achieve results you desire.
