### ISSUE TITLE
Rounding inconsistency with valueZat?

### ISSUE THREAD

**Issue by Haaroon** [citp/BlockSci#117]
Ran the ZCash chain through the BlockSci rpc parser. 
Was looking at some tranasaction output values in blockscipy. 
It seems that value out in one transaction was incorrect, (due to rounding precision?)
This damages the consistency when looking for transactions with absolute values. 

For example, output 0 from this txid (30287c5c83f73dd0ab22c367cdd8ac8ba4e56dc135c84b8657026a02e3298d25) is 1.33767. 

When searched for in blocksci it returns the first TxOut as value=133766999. 

I haven't been able to find any other transactions like this, not sure if its my interpreter, the parsing process by blocksci or something gone wrong in my end. 

Would appreciate any help, or to see if this is reproduced on other blocksci parsed zcash data chains.

**Comment by hkalodner** [comment]
Ah. I haven't seen this before. This appears to be a problem in https://github.com/minium/bitcoin-api-cpp. The RPC lists the output values as floating point numbers, and the RPC interface library interprets these as doubles, which introduces rounding errors. There's a page about this issue on the Bitcoin wiki (https://en.bitcoin.it/wiki/Proper_Money_Handling_(JSON-RPC)) along with a solution. I'll fix this in the next update. It'll require a re-parse to fix.
