### ISSUE TITLE
ModuleNotFoundError: No module named 'blocksci'

### ISSUE THREAD

**Issue by ujnamss** [citp/BlockSci#119]
Hi,

I have installed blocksci following the instructions at: https://citp.github.io/BlockSci/compiling.html [Ubuntu 16.04]

I was able to successfully parse the bitcoin blockchain with the following command:
$HOME_DIR/BlockSci/release/tools/parser/blocksci_parser --output-directory /btc-data update disk --coin-directory /bitcoin

Now i would like to use python bindings in my python code:
```
import blocksci

class BlockSciQueryService:

    def __init__(self, bsciIndexPath):
        self.bsciIndexPath = bsciIndexPath
        self.chain = blocksci.Blockchain(bsciIndexPath)

    def findCoinsPerBlock(self):
        net_coins_per_block = self.chain.map_blocks(lambda block: block.net_address_type_value())
        print("net_coins_per_block:{}".format(net_coins_per_block))
```

When i run a test case using BlockSciQueryService, i get a ModuleNotFoundError: No module named 'blocksci' error.

I printed sys.path and it points to the directory containing blocksci:
$HOME_DIR/BlockSci/blockscipy

Not sure what i am missing. My environment just has python3.6 installed.

**Comment by ujnamss** [comment]
I changed pip install step to exclude "-e" option ==>  `pip install ./blockscipy`. This solved the problem after multiple hours of trial and error.

**Comment by hkalodner** [comment]
I'm not sure what this error occurred. The `-e` installs the BlockSci module in development mode which allows incremental recompilation. I'm not sure why it was messing up the install process for you. I wouldn't think that flag would effect whether the installed module should be found. Either way it should be installed into whatever folder pip normally installs into.

**Comment by josiahgray12** [comment]
I was having a similar problem and I realized I was accidentally running python 2.7 instead of python 3. Something to double check if you are having this issue.

**Comment by ypsilon94** [comment]
Encountered same issue! How did you uninstalled the module? I'm trying to undo that and then install it without the -e flag

**Comment by tejaskhajanchee** [comment]
@hkalodner 
Please Help!!
I am getting the same error: `ImportError: No module named 'blocksci'`. I tried the above mentioned solutions also. It still doesn't work.

While performing the last command mentioned [compilation instructions for Ubuntu 16.04](https://citp.github.io/BlockSci/compiling.html#ubuntu-16-04), I encounter an error that I have recorded in a file. I am also uploading that file. Please have a look. I am not understanding how to resolve that issue.
[BlockSci_error.txt](https://github.com/citp/BlockSci/files/2272517/BlockSci_error.txt)

I have python 3.5.2 installed. I updated my GCC to GCC-7.3.0, Clang to Clang-6.0.1, and also I had ensured before starting the compilation that I didn't have a previous version of blocksci installed.

I have created a bitcoin full node and downloaded a the chain up to a pruned length of 10GB (due limitations of space), and the block sci parser also worked without any issue.

I need help.
