### ISSUE TITLE
Parser running extremely slow on machine with good specs

### ISSUE THREAD

**Issue by josiahgray12** [citp/BlockSci#121]
Hi, 

I'm having some trouble getting the parser to actually complete parsing.

I'm running an 8 core Microsoft Azure machine with 64 GB of RAM, and the parser is still only 77% done after almost 40 hours of running. It started out moving at a reasonable pace, but when I left if on over night, the next morning it had made barely any progress over the night, moving from about 55% to 65% in the 12 hours I left it.

Just to try and provide as much info as possible, at the time of writing the parser is using 18GB of ram, and the rest of my ram is entirely free. And the parser is barely using any CPU,  it says in htop 0.6% of a core.

Any ideas on what I could do to speed it up, or any mistakes I may have made during setup that may be causing this slow down?

Thanks

**Comment by agamrp** [comment]
@josiahgray12 I'm actually running into this as well, was there anything you did to address or the parser just finished up so you closed the issue?

**Comment by josiahgray12** [comment]
@agamrp I did not end up having to do anything, it eventually finished. It actually just finished parsing completely this morning around 10. I'm assuming it's just because as the parser got closer to current time, the blockchain became much more dense with transaction information. Now it just takes a days to finish up parsing instead of hours.

**Comment by agamrp** [comment]
@josiahgray12 thanks yeah I'm at 92% right now after almost a week, so hopefully should be finishing up soon, and that makes sense, thanks for letting me know!

**Comment by Haaroon** [comment]
on first try the bitcoin parser took a week, so i would suggest copying the files from ec2 (if you have the extra cash to spend) and then updating this version locally.

**Comment by alex-btc** [comment]
Any info on how many days the parser take to parse the whole bitcoin blockchain in 2022?
I am 8 hours in and just 15% done.

**Comment by Haaroon** [comment]
It's largely dependent on your hard drive speed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
