### ISSUE TITLE
Mempool Recorder setup

### ISSUE THREAD

**Issue by josiahgray12** [citp/BlockSci#123]
I see in the documentation that:

`mempool_recorder <data location> --username <username> --password <password> [--address <address>] [--port <port>]`

is the model command to run in order to run data collection in the mempool. However, I am not sure what parts of this are expecting to be replaced by values I should input, and how I determine what those input values would be.

I could use a quick explanation of how this works.

**Comment by nelsontodd** [comment]
Hi,

The mempool_recorder uses RPC requests to get transaction data from the node you're running. So the `--password` and `--username` flags require you to input values that you get from your node configuration. An example call could look like this:

`mempool_recorder /home/ubuntu/blocksci-output --username nelson --password nelson11`
