### ISSUE TITLE
Incorrect address format for litecoin?

### ISSUE THREAD

**Issue by Haaroon** [citp/BlockSci#124]
I seem to be missing something. 
I've parsed and run clustering a litecoin blockchain upto the latest block. 
Now I am searching clusters for a specific address. 
It seems when I use the litecoin address format I cannot use `chain.address_from_string`. 

For example this ltc address `LfrrHCNQouXJC3fJx11qTPtq7ZrRdjsb1X` in blocksci is represented like this `PubkeyHashAddress(1Mdu1z4ajFHEwEy9ms2YBNq4uMV9RqqqiV)`

Is there any way I can alter the format so the addresses are displayed in the LTC style?

Edit: From doing a bit of digging the addresses are parsed from the scriptsig bitcoin style which is why they all are output like this. I'll work around by parsing the addresses I want into this format before searching. 

Thanks.

**Comment by Haaroon** [comment]
its getting a bit cumbersome having to manually extract the scriptsig and then convert the addresses to search, is there any other way or plans to incoreperate other address types?

**Comment by maltemoeser** [comment]
There'll be an updated description on how to use BlockSci with altcoins in the next documentation update. Currently, BlockSci selects specific address formats for altcoins based on the name of the data directory. In this case, the BlockSci data directory [would need to include `namecoin`](https://github.com/citp/BlockSci/blob/master/src/util/data_configuration.cpp#L79)
