### ISSUE TITLE
blocksci_clusterer instructions

### ISSUE THREAD

**Issue by josiahgray12** [citp/BlockSci#127]
I have since figured it out, but I think it would be helpful for the v0.5.0 documentation to have instructions on how to use the blocksci_clusterer command. For anyone reading through issues trying to figure this out themselves: 
blocksci_clusterer <data_directory> <cluster_output_destination> --overwrite

Where you replace <data_directory> with the path to the output of your parser, <cluster_output_destination> with where you want the new cluster data stored, and --overwrite is an option to run if you have alrady run the clustering command and you are updating your data.

**Comment by annjieching** [comment]
got it, thank you!

**Comment by engenegr** [comment]
Nothing changed to 2019.
I just put for everybody googling or finding via github this error 
`Error, blocksci scripts directory does not exist`
It connected to the issue.
