### ISSUE TITLE
Installing python library not working

### ISSUE THREAD

**Issue by josiahgray12** [citp/BlockSci#128]
Hi,

I have completed all the installation instructions and am so close to being able to properly use BlockSci. I am still unable to properly install the python3 blocksci library. 

When I try to import blocksci in python script I get a module not found error.

>>> import blocksci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'blocksci'

I went back to the local setup instructions in the v0.5.0 documentation and tried to re-run the:

CC=gcc-7 CXX=g++-7 sudo -H pip3 install -e blockscipy

command with no success.

Here is the output from running that command:

Obtaining file:///home/jdgray/BlockSci/blockscipy
Requirement already satisfied: multiprocess>=0.70.5 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (0.70.5)
Requirement already satisfied: psutil>=5.4.2 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (5.4.6)
Requirement already satisfied: pycrypto>=2.6.1 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (2.6.1)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (0.23.0)
Requirement already satisfied: dateparser>=0.6.0 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (0.7.0)
Requirement already satisfied: dill>=0.2.6 in /usr/local/lib/python3.5/dist-packages (from multiprocess>=0.70.5->blocksci==0.5.0) (0.2.7.1)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from pandas>=0.22.0->blocksci==0.5.0) (1.14.4)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.5/dist-packages (from pandas>=0.22.0->blocksci==0.5.0) (2018.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.5/dist-packages (from pandas>=0.22.0->blocksci==0.5.0) (2.7.3)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.5/dist-packages (from dateparser>=0.6.0->blocksci==0.5.0) (1.5.1)
Requirement already satisfied: regex in /usr/local/lib/python3.5/dist-packages (from dateparser>=0.6.0->blocksci==0.5.0) (2018.6.9)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.5.0->pandas>=0.22.0->blocksci==0.5.0) (1.10.0)
Installing collected packages: blocksci
  Running setup.py develop for blocksci
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/jdgray/BlockSci/blockscipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing top-level names to blocksci.egg-info/top_level.txt
    writing dependency_links to blocksci.egg-info/dependency_links.txt
    writing requirements to blocksci.egg-info/requires.txt
    writing blocksci.egg-info/PKG-INFO
    reading manifest file 'blocksci.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'blocksci.egg-info/SOURCES.txt'
    running build_ext
    -- pybind11 v2.2.2
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/jdgray/BlockSci/blockscipy/build/temp.linux-x86_64-3.5
    [  1%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_py.cpp.o
    [  3%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_range.cpp.o
    In file included from /home/jdgray/BlockSci/blockscipy/src/ranges_py.hpp:12:0,
                     from /home/jdgray/BlockSci/blockscipy/src/cluster/cluster/cluster_range.cpp:9:
    /home/jdgray/BlockSci/blockscipy/src/range_conversion.hpp: In function ‘constexpr bool isNestedOptionalRange()’:
    /home/jdgray/BlockSci/blockscipy/src/range_conversion.hpp:225:8: error: expected ‘(’ before ‘constexpr’
         if constexpr (is_optional<value_type>::value) {
            ^
    /home/jdgray/BlockSci/blockscipy/src/cluster/cluster/cluster_range.cpp:17:1: error: expected ‘}’ at end of input
     }
     ^
    /home/jdgray/BlockSci/blockscipy/src/cluster/cluster/cluster_range.cpp:17:1: warning: no return statement in function returning non-void [-Wreturn-type]
    In file included from /home/jdgray/BlockSci/blockscipy/src/self_apply_py.hpp:12:0,
                     from /home/jdgray/BlockSci/blockscipy/src/cluster/cluster/cluster_py.cpp:11:
    /home/jdgray/BlockSci/blockscipy/src/range_conversion.hpp: In function ‘constexpr bool isNestedOptionalRange()’:
    /home/jdgray/BlockSci/blockscipy/src/range_conversion.hpp:225:8: error: expected ‘(’ before ‘constexpr’
         if constexpr (is_optional<value_type>::value) {
            ^
    /home/jdgray/BlockSci/blockscipy/src/cluster/cluster/cluster_py.cpp:86:1: error: expected ‘}’ at end of input
     }
     ^
    /home/jdgray/BlockSci/blockscipy/src/cluster/cluster/cluster_py.cpp:86:1: warning: no return statement in function returning non-void [-Wreturn-type]
    CMakeFiles/_blocksci.dir/build.make:75: recipe for target 'CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_range.cpp.o' failed
    make[2]: *** [CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_range.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/_blocksci.dir/build.make:62: recipe for target 'CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_py.cpp.o' failed
    make[2]: *** [CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_py.cpp.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/_blocksci.dir/all' failed
    make[1]: *** [CMakeFiles/_blocksci.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jdgray/BlockSci/blockscipy/setup.py", line 76, in <module>
        'dateparser>=0.6.0'
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/jdgray/BlockSci/blockscipy/setup.py", line 32, in run
        self.build_extension(ext)
      File "/home/jdgray/BlockSci/blockscipy/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/jdgray/BlockSci/blockscipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/jdgray/BlockSci/blockscipy/

I hope this in an issue that can be diagnosed as something simple. Let me know if I should provide any further details on my situation.

Thanks

**Comment by p4u** [comment]
Looks like a GCC version problem, somehow just specifing CC and CXX system variables does not work , if you are using Ubuntu you can make Gcc/G++ v7 default compilers, try:

```
sudo udpate-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10

```

**Comment by josiahgray12** [comment]
Thanks, there was definitely a problem with my GCC. I also think I was using an outdated version of cmake. I read through lots of stackoverflow articles, and the only thing that ended up fixing my problem was running 

hash -r

in the terminal. I'm not sure what it did, but afterwards I ran the blocksci install and it worked.
