### ISSUE TITLE
BlockSci with Zcash

### ISSUE THREAD

**Issue by feddan35** [citp/BlockSci#13]
Hi!

I am trying to run the tool with Zcash, I ran the whole setup according to the readme, but after a lot of testing the RPC parser still says:

```
terminate called after throwing an instance of 'Json::LogicError'
what():  Value is not convertible to UInt.
```

Any idea of what can be the problem? Is there something else I have to specify to make the tool compatible with Zcash?

**Comment by hkalodner** [comment]
This was fixed in a previous release.
