### ISSUE TITLE
Very High Wall Time

### ISSUE THREAD

**Issue by warproxxx** [citp/BlockSci#130]
I am running BlockSci in a google cloud instance (Ubuntu 16.04 Server - Python3 with jupyter notebook). I am currently using 6 Core with 46 GB RAM.

In all of these tests, when i time execution, the wall time is enormously high compared to CPU time.After the first attempt the wall time decreases significantly. Why is it like this? Is there any way to change it?

This is the command i am running:
`%time net_coins_per_block = chain.map_blocks(lambda block: block.net_address_type_value())`

Attempt 1:

> CPU times: user 14.8 s, sys: 9.38 s, total: 24.2 s
> Wall time: 5min 56s

Attempt 2: 

> CPU times: user 11.7 s, sys: 768 ms, total: 12.5 s
> Wall time: 16.6 s

It's the same across a lot of different RAM and CPU Cores. The Wall time is extremely high in the first run and decreases significantly after that.

Does it work like this? Can i not decrease the wall time?

**Comment by csegarragonz** [comment]
I am pretty sure that the first time you run a blocksci command it loads all the chain data. That is why it is taking so long (for me it is about a minute not 4/5 though). Once everything is loaded it should run normally. (Note that this is my experience from using blocksci with the interactive shell and through scripts, not via Jupyter, I guess it must be the same though.)

As far as I know there is no way to avoid this. Just make sure you make all the calls at once in one session.

Hope it helps!
