### ISSUE TITLE
question on using different clustering heuristics

### ISSUE THREAD

**Issue by bb324930** [citp/BlockSci#133]
Many thanks for all the great work on this library. I have a clustering question.

It's not immediately clear how clustering strategies are composable / customizable. 

I'd like to run a clustering with only the `multi-input transaction` heuristic (ie: no change assumptions) and also ignores CoinJoin & coinbase txns and I'm unsure how to do that. 

The Python `blocksci.cluster.ClusterManager` interface only exposes a way to point to the output dir of the `blocksci_cluster` executable. And the C++ code itself assumes a change heuristic, as shown [here](https://github.com/citp/BlockSci/blob/47b53ff82ac0bee250be8d9bb3693f056f572ed6/tools/clusterer/main.cpp#L34). 

Is recompilation necessary to try different clustering techniques? And how might I run a clustering without a change heuristic?

**Comment by Haaroon** [comment]
Yes, I would like to do the same too. I realised that the clusters generated by BlockSci are far greater that the clusters I generated manually with multi-input. In one case for a zcash chain it reported over half of addresses belonging to one cluster, when my multi-input reported much much less.

**Comment by Axsel** [comment]
you can easily do it with the provided python interface
```
c = blocksci.heuristics.change.optimal_change() and blocksci.heuristics.change.peeling_chain()
cm.create_clustering(cluster_data, chain, c, True)
```

different available heuristics are provided in the documentation
https://citp.github.io/BlockSci/reference/heuristics/change.html

**Comment by maltemoeser** [comment]
There's currently no straightforward option to disable the use of change address heuristics in the clusterer. #136 adds a simple NoChange heuristic to effectively disable it.

For now, you can make use of the composability of these heuristics to achieve the same effect (albeit slower).
```python
nochange = blocksci.heuristics.change.legacy() - blocksci.heuristics.change.legacy()
```

**Comment by Haaroon** [comment]
Thanks for all your replies. 
But the above code is essentailly just taking away the same two items? `nochange = blocksci.heuristics.change.legacy() - blocksci.heuristics.change.legacy()`, given they are the same variables doesnt it just cancel out?

**Comment by maltemoeser** [comment]
Correct, thereby no addresses from change outputs are merged into the cluster. The multi-input heuristic is always applied.
