### ISSUE TITLE
Segmentation fault at block 511207 - Bitcoin

### ISSUE THREAD

**Issue by PietroSaggese** [citp/BlockSci#139]
Hi, when I run the parser, the process gets stuck at the block 511207.
I am using a server with enough RAM, as specified in the instructions.
I tried to make the process less computationally demanding by parsing the chain in several steps (here it has to parse only 606 blocks).
It always stops at block 511207.
Here is the error message:

....@ubuntulab2:/storage$ blocksci_parser --output-directory bitcoin-data update --max-block -20000 disk --coin-directory .bitcoin
100.0% done fetching block headers
Starting with chain of 511149 blocks
Removing 0 blocks
Adding 606 blocks
11.46% done, Block 511207/511755Segmentation fault (core dumped)

I don't understand why it happens. Can someone help me?

**Comment by ClementPavue** [comment]
Got the same issue. An idea to fix it is to reparse everything from scratch.

**Comment by PietroSaggese** [comment]
thanks, it worked!
