### ISSUE TITLE
Cluster methods extremely slow

### ISSUE THREAD

**Issue by Husam92** [citp/BlockSci#143]
Hi all,

I have been experiencing this across almost all versions of BlockSci when using the ClusterManager.

So, to explain what is exactly happening, let's take this example. I want to iterate through a list of addresses. Each iteration will call the following methods:

`sci_address = chain.address_from_string("xxxxxxxxxxxxxxx") `
          ` if sci_address is not None: `
                     `cluster = cluster_manager.cluster_with_address(sci_address) `
                     `if cluster is not None: `
                            `print(cluster.size()) //same behavior with len(cluster) `

Apparently, the problem beings as soon as you try to access the cluster object. The script just hangs and if I do htop to check the processes running, I see the following:

<img width="561" alt="screen shot 2018-07-21 at 6 55 15 pm" src="https://user-images.githubusercontent.com/10672009/43037666-5f744548-8d18-11e8-976d-693376e1a2b7.png">

Any ideas? Does accessing cluster object supposed to be extremely slow? Or is it for certain clusters? (because I tried this with many addresses and it does not matter how large is the cluster being retrieved) But, sometimes it succeeds after a few seconds of processing.

**Comment by maltemoeser** [comment]
I think the size() method will do some additional processing to account for equiv addresses, using `cluster.type_equiv_size` should be faster

**Comment by Husam92** [comment]
As I mention in the code it does not matter which method is called on the cluster it will still be extremely slow to even access any property of the cluster object.

**Comment by Husam92** [comment]
<img width="879" alt="screen shot 2018-07-28 at 3 15 23 pm" src="https://user-images.githubusercontent.com/10672009/43356421-2afd65a4-9279-11e8-95db-2f619dd67386.png">

For example, just opening a python terminal, importing the blockchain and cluster_manager then getting a cluster, once I press tab to expose the cluster methods, everything hangs. Sometimes it resolves and displays results (after few minutes) and sometimes never displays anything.

**Comment by shihao-guo** [comment]
Try remake the cluster without any change address heuristics. The hang maybe caused by frequent cluster collision due to untuned change address heuristics. 

You could do 

```
chain = blocksci.Blockchain('/home/ubuntu/bitcoin')
cm = blocksci.cluster.ClusterManager('/home/ubuntu/bitcoin/clusters', chain)
nochange = blocksci.heuristics.change.legacy() - blocksci.heuristics.change.legacy()
cm.create_clustering('/home/ubuntu/bitcoin/clusters', chain, nochange, True)
```

**Comment by Husam92** [comment]
Just tried, same problem

**Comment by Husam92** [comment]
Update:

Just noticed that when I run "iotop" command, I find that the IO is > 95% when a big cluster method is accessed. Does it matter if the system was installed on a virtual machine with a Network Attached Storage vs. if it has direct access to hardware (i.e. SSDs) ?

**Comment by kaneda-fr** [comment]
Hi,
I also notices that parsing through all clusters is extremely slow (504 Millions). 

The clustering creation is very efficient and it completes under 10 mins, but extracting the data is a pain. I wonder if going C++ would be faster or if any alternate options would be recommended.
