### ISSUE TITLE
blockcsci.CurrencyConverter KeyError

### ISSUE THREAD

**Issue by erkkipiipari** [citp/BlockSci#145]
I'm running the newest AMI and I want to run the example "Average Fee per Transaction in 2017 in USD" from the example notebook with the entire time range using the following code snippet:

```
chain = blocksci.Blockchain("/home/ubuntu/bitcoin")
converter = blocksci.CurrencyConverter()
fees = chain.blocks.fee / chain.blocks.tx_count
times = chain.blocks.time
df = pd.DataFrame({"Fee":fees}, index=times)
df = converter.satoshi_to_currency_df(df, chain)
ax = df.resample("d").mean().plot(legend=False)
ax.set_ylim(ymin=0)
plt.tight_layout()
```

Result is the following error:
> KeyError: ('2018-07-26', 'occurred at index 2018-07-26 00:02:26')

The entire error message is as follows:

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-5-6b4542a65684> in <module>()
>       1 df = pd.DataFrame({"Fee":fees}, index=times)
> ----> 2 df = converter.satoshi_to_currency_df(df, chain)
>       3 ax = df.resample("d").mean().plot(legend=False)
>       4 ax.set_ylim(ymin=0)
>       5 plt.tight_layout()
> 
> ~/BlockSci/blockscipy/blocksci/currency.py in satoshi_to_currency_df(self, df, chain, columns)
>      85         if index_type == "int64":
>      86             df["index"] = pd.Series(df["index"]).apply(lambda x: chain[x].time.date())
> ---> 87         df = df.apply(convert_row, axis=1)
>      88         del df["index"]
>      89         return df
> 
> ~/.local/lib/python3.5/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, args, **kwds)
>    4852                         f, axis,
>    4853                         reduce=reduce,
> -> 4854                         ignore_failures=ignore_failures)
>    4855             else:
>    4856                 return self._apply_broadcast(f, axis)
> 
> ~/.local/lib/python3.5/site-packages/pandas/core/frame.py in _apply_standard(self, func, axis, ignore_failures, reduce)
>    4948             try:
>    4949                 for i, v in enumerate(series_gen):
> -> 4950                     results[i] = func(v)
>    4951                     keys.append(v.name)
>    4952             except Exception as e:
> 
> ~/BlockSci/blockscipy/blocksci/currency.py in convert_row(row)
>      76             if hasattr(date, 'date'):
>      77                 date = date.date()
> ---> 78             rate = self.exchangerate(date) / 1e8
>      79             for column in columns:
>      80                 if column in row:
> 
> ~/BlockSci/blockscipy/blocksci/currency.py in exchangerate(self, date)
>      51         if date < self.COINDESK_START:
>      52             return 0
> ---> 53         return self.data[str(date)]
>      54 
>      55     def btc_to_currency(self, value, date):
> 
> KeyError: ('2018-07-26', 'occurred at index 2018-07-26 00:02:26')

I'd really like to use the CurrencyConverter in the entire chain length. How can this be fixed?

**Comment by maltemoeser** [comment]
The API doesn't provide a same-day price, you'll need to exclude the current day when doing the analysis.
