### ISSUE TITLE
Modifying heuristics and re-run the clusterizer

### ISSUE THREAD

**Issue by ypsilon94** [citp/BlockSci#146]
Hi,
I would like to modify your heurisitcs to find the change address in a transaction and see the effect I have one the final clusters; do you have any suggestion or indication on how to do that?
Any tip or trick?
I'm using version 0.4.5 but I'm updating to the newest version

Thank you in advance!

**Comment by ypsilon94** [comment]
Actually I'm updating to the newest version!

**Comment by maltemoeser** [comment]
You can easily create multiple clusterings using the ClusterManager, see https://gist.github.com/maltemoeser/b8ff7be6be23459c659207cdf1c42094 for an example of how to create a clustering with and one without the legacy change heuristic. You can also compose a new heuristic by combining existing ones.
