### ISSUE TITLE
No module named 'blocksci' after completed blockscipy installation

### ISSUE THREAD

**Issue by salvp** [citp/BlockSci#148]
Hi everyone,

I'm trying to update Blocksci to the newest version, but, although it seems to install Blockscipy, the blocksci library can't be used in any .py file i create, nor in any notebook as the demo, because not found. Here what happens:

This is the output if i try without the -e flag

CC=gcc-7 CXX=g++-7 sudo -H pip3 install blockscipy
Collecting blockscipy
  Could not find a version that satisfies the requirement blockscipy (from versions: )
No matching distribution found for blockscipy

I tried with this command CC=gcc-7 CXX=g++-7 sudo -H pip3 install ./blockscipy
Processing ./blockscipy
Requirement already satisfied: multiprocess>=0.70.5 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (0.70.5)
Requirement already satisfied: psutil>=5.4.2 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (5.4.6)
Requirement already satisfied: pycrypto>=2.6.1 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (2.6.1)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (0.22.0)
Requirement already satisfied: dateparser>=0.6.0 in /usr/local/lib/python3.5/dist-packages (from blocksci==0.5.0) (0.7.0)
Requirement already satisfied: dill>=0.2.6 in /usr/local/lib/python3.5/dist-packages (from multiprocess>=0.70.5->blocksci==0.5.0) (0.2.7.1)
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.5/dist-packages (from pandas>=0.22.0->blocksci==0.5.0) (2.7.3)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.5/dist-packages (from pandas>=0.22.0->blocksci==0.5.0) (2018.4)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from pandas>=0.22.0->blocksci==0.5.0) (1.14.2)
Requirement already satisfied: regex in /usr/local/lib/python3.5/dist-packages (from dateparser>=0.6.0->blocksci==0.5.0) (2018.2.21)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.5/dist-packages (from dateparser>=0.6.0->blocksci==0.5.0) (1.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil>=2->pandas>=0.22.0->blocksci==0.5.0) (1.11.0)
Building wheels for collected packages: blocksci
  Running setup.py bdist_wheel for blocksci ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-t009q5lo/wheels/9b/ff/55/bb49c9e99a551174004430362b36eb8495e4c151f50b954618
Successfully built blocksci
Installing collected packages: blocksci
  Found existing installation: blocksci 0.5.0
    Uninstalling blocksci-0.5.0:
      Successfully uninstalled blocksci-0.5.0
Successfully installed blocksci-0.5.0

And this is the output when i try to import blocksci module

~/BlockSci/Notebooks$ python3
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'blocksci'
>>> 

Can you help me somehow? I saw previous issues, https://github.com/citp/BlockSci/issues/106,https://github.com/citp/BlockSci/issues/128,https://github.com/citp/BlockSci/issues/115, those ways didn't work!

Thank you!

**Comment by maltemoeser** [comment]
Why are you not using the `-e` flag? blockscipy must be built locally and the `-e` flag tells pip the directory path to blockscipy
