### ISSUE TITLE
BlockSci port for CentOS

### ISSUE THREAD

**Issue by ArgirisKala** [citp/BlockSci#152]
I am trying to compile locally BlockSci at CentOS 6 and CentOS 7 following the instructions from github.

The first problem i encountered was the boost lib, the required version does not exist,  i find a way to overcome by compiling some custom rpm packets.

The next problem comes with libjson-rpc (libjson-rpc-cpp) that it is also not available for CentOS 6 and CentOS 7, but i can't overcome it.

Do you have port BlockSci to CentOS 6 or 7 ?
Do you have any instructions for compiling at CentOS 6 or 7 ?

Any help will be appreciated.

**Comment by hkalodner** [comment]
Sorry BlockSci doesn't prove support for any platforms other than Ubuntu and Mac OS. It should be possible to get BlockSci running on CentOS by manually compiling its various dependencies. libjson-rpc-cpp for instance has instructions on how to build from source in its repo https://github.com/cinemast/libjson-rpc-cpp#build-from-source.
