### ISSUE TITLE
Is there any way to map addresses to exchanges or pools?

### ISSUE THREAD

**Issue by liuzf13** [citp/BlockSci#160]
Hi everyone,

    I'm a new bee to block chain. Thanks to blocksci, Now I can get input and output addressed from some transactions. 
    
    I'm wondering is there any way to map those addresses to exchanges like Bitfinex or Bittrex?

    Thanks!

**Comment by maltemoeser** [comment]
BlockSci allows to tag address clusters, but we don't provide any such tags. There are a few public sources that you could try, such as [WalletExplorer](https://www.walletexplorer.com/) or [Blockchain.info](https://www.blockchain.com/btc/tags), but they may not be reliable or complete.

Furthermore, you can map blocks to pools by looking at the information contained in the coinbase transaction, but again there's no guarantee that this information is correct.
```python
blocksci.get_miner(chain[300005])
>>> 'SlushPool'
```
