### ISSUE TITLE
Error in the BlockSci configuration

### ISSUE THREAD

**Issue by UthpalaPitawela** [citp/BlockSci#162]
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update
sudo apt install cmake libtool autoconf libboost-filesystem-dev libboost-iostreams-dev \
libboost-serialization-dev libboost-thread-dev libboost-test-dev  libssl-dev libjsoncpp-dev \
libcurl4-openssl-dev libjsoncpp-dev libjsonrpccpp-dev libsnappy-dev zlib1g-dev libbz2-dev \
liblz4-dev libzstd-dev libjemalloc-dev libsparsehash-dev python3-dev python3-pip

git clone https://github.com/citp/BlockSci.git
cd BlockSci
mkdir release
cd release
CC=gcc-7 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Release ..
I have successfully followed the above installation steps.But when I "make" it, got the following errors
![ss222222](https://user-images.githubusercontent.com/17847364/45482813-af49cb00-b76c-11e8-8d1c-057f190c4650.png)

**Comment by hkalodner** [comment]
So I'm not entirely sure why, but from the screenshot it looks like g++-5 standard library is being used. The urls would look like /usr/include/c++/7/ if it were properly using g++-7.

**Comment by hkalodner** [comment]
Closed due to inactivity
