### ISSUE TITLE
Poor Performance of the Clustering Algorithm

### ISSUE THREAD

**Issue by IsurangaPerera** [citp/BlockSci#164]
When running the clustering algorithm it maps whole data files into the memory. This has caused the heavy use of virtual memory hence heavy IO usage. This seems to be the problem faced in #143 as well. This problem can be largely seen when the memory being used is smaller (16GB etc.). Due to a large number of cache misses parallel algorithm used in BlockSci is extremely slow when compared to the sequential version of the same algorithm. This problem can be overcome by partial mapping of data files. As an example instead of mapping the whole transaction to the memory, the above file can be divided into parts and map each part to the memory depending on the free memory available.

@hkalodner @maltemoeser please provide your insight on the issue.

**Comment by maltemoeser** [comment]
This is correct, BlockSci hasn't been optimized for machines with small amounts of memory (that's why we recommend using instances with 60 GB of memory or more for optimal performance).

**Comment by hkalodner** [comment]
Just to add in here, BlockSci has been developed for research purposes. Its target is optimal performance on single high-memory machines. If other people would like to contribute optimizations that improve performance on machines with under 64gb of memory, that would be great, but it's not a goal for us.
