### ISSUE TITLE
Only get the last transactions of an address or a cluster

### ISSUE THREAD

**Issue by ClementPavue** [citp/BlockSci#165]
It's sometimes long to get all the transactions of large cluster or addresses. If we have a function to only get the last transactions or the first we would have a way to interact with them quicker.

**Comment by hkalodner** [comment]
`cluster.outs` and `address.outs` return instantly, providing an iterator over all outputs of the associated cluster or address. These can then be iterated over in a for loop or list comprehension. In the current development branch (v0.6) we've extended `address.ins`, `address.out_txes`, and `cluster.ins` to return iterators as well.

`cluster.txes()` returns a list of unique transactions where a given address or cluster is used for either and input or an output. Unfortunately there's no way to lazily calculate that.
