### ISSUE TITLE
How to avoid super-cluster?

### ISSUE THREAD

**Issue by ksocks** [citp/BlockSci#167]
Can anyone suggest a way to run the clustering that avoids generating the 139 million address supercluster?

**Comment by ksocks** [comment]
Using multi-input only criteria from example in cluster.py moved the addresses I was interested in into separate smaller clusters. I'm interpreting this to mean that the change-heuristic was likely making occasional mistakes that created links jumping between clusters? Would it be possible to resolve this while including change addresses by first clustering with multi-input only, than adding in change addresses for transactions in this set but not following those links any further? It's unclear how I would do this in the BlockSci clustering framework, if you have any suggestions I would appreciate it, thank you!

**Comment by maltemoeser** [comment]
In [The Unreasonable Effectiveness of Address Clustering](https://arxiv.org/abs/1605.06369), Harrigan and Fretter suggest the following, which might help:

> "It is a rarity for two large address clusters to merge, thereby drastically changing the results of an earlier analysis. If fact, if two large address clusters do merge, it may indicate that the multi-input heuristic has produced a false positive."

**Comment by ksocks** [comment]
Thanks!

**Comment by sirpy** [comment]
I've also experimented with multi-input only clustering, still I've received a super cluster numbered 261, which includes some clusters I know should not be there. This differs from clusters found on walletexplorer.com which i think uses multi input only also. This leads me to speculate there exists a bug in the merging/clustering process.  Any tips on debugging the clustering process?
