### ISSUE TITLE
Lower RAM requirements with Dask 

### ISSUE THREAD

**Issue by westurner** [citp/BlockSci#17]
Dask provides a similar API to Pandas and supports datasets larger than can fit into RAM.

From https://dask.pydata.org/en/latest/dataframe.html :

> A Dask DataFrame is a large parallel dataframe composed of many smaller Pandas dataframes, split along the index. These pandas dataframes may live on disk for larger-than-memory computing on a single machine, or on many different machines in a cluster.

- Docs: https://dask.pydata.org/en/latest/
- Src: https://github.com/dask/dask
- Pypi: https://pypi.org/project/dask/
- CondaPkg: ``dask``

**Comment by westurner** [comment]
Dask-ml

> Dask-ML enables parallel and distributed machine learning using Dask alongside existing machine learning libraries like Scikit-Learn.

- Src: https://github.com/dask/dask-ml
- Docs: http://dask-ml.readthedocs.io/en/latest/

**Comment by hkalodner** [comment]
This is certainly interesting. I hadn't seen Dask before. It might be useful in conjunction with BlockSci, but BlockSci does not use pandas for data availability. We implement a custom data access interface using memory mapped files.
