### ISSUE TITLE
Throw exception when loading clustering from invalid directory

### ISSUE THREAD

**Issue by maltemoeser** [citp/BlockSci#171]
BlockSci should throw an exception when trying to load a clustering from files that do not actually exist.

#### Expected Result
When loading a clustering with an invalid file path, BlockSci should return an error similar to instantiating a Blockchain object from an invalid path:

```
RuntimeError: Error, blocksci data directory does not exist
```

#### Actual Result
The ClusterManager will not complain but crash when trying to interact with the clusters.

#### Reproduction Steps
```
cm = blocksci.cluster.ClusterManager("/some/invalid/path", chain)
```

#### System Information
BlockSci version: 0.5
Using AMI: yes
Total memory: 60 GB

**Comment by yya518** [comment]
@maltemoeser Maybe I missed this, but I cannot find API in the document where I can construct the ClusterManager from an existing clustering dir. I happen to find your comments here so I can load cm from an existing clustering dir. It would be nice to include the API in the document. :-)

**Comment by maltemoeser** [comment]
@yya518 we have it covered in the [FAQ](https://github.com/citp/BlockSci/wiki#how-do-i-use-blockscis-clustering-module), but I'll make sure to double-check the documentation, thanks :)
