### ISSUE TITLE
coinjoin heuristic bug?

### ISSUE THREAD

**Issue by sirpy** [citp/BlockSci#174]
Please provide a clear and concise description of what the problem is.

#### Expected Result
What you expected to happen.
this transaction marked as coinjoin
https://www.walletexplorer.com/txid/8c5ca4305144d76535fb74ca664cb94aff2cdd2563f70652de579efc6d812d32
this line of code seems suspicious to me, otherwise it seems this transaction should return true for iscoinjoin:
https://github.com/citp/BlockSci/blob/67ee51d6c89e145e879181c7f934fddb4ce3b54b/src/heuristics/tx_identification.cpp#L50

#### Actual Result
What happened instead.
addresses clustered into same wallet

#### Reproduction Steps
cluster without change heuristic

#### System Information
BlockSci version:  0.5
Using AMI: no
Total memory: 64g

**Comment by sirpy** [comment]
I understand, but looking at the current code heuristic I dont understand where the transaction i've attached fails.
Can you elaborate on line 50 in the heuristic, from what I understand pr->second is supposed to be the maximum value but its being compared to the participants count. Also what are the value types numbers in the following lines? 547?

**Comment by sirpy** [comment]
Can you explain lines 50+54 in the heuristic?

**Comment by maltemoeser** [comment]
`outputValues` is a mapping from output value to the number of times the value occurs.
`pr->second != participantCount` checks whether the number of outputs having the most common output value equals the number of expected participants of a CoinJoin transaction (calculated in line 24).
Line 54 ignores some false positives (output values of 546 or 2730 Satoshi are unlikely to be CoinJoins), though I don't know exactly where these values come from (@hkalodner might remember).

**Comment by maltemoeser** [comment]
Your transaction has 21 outputs, so our heuristic expects 11 outputs sharing the same value. However, none of the values appear more than once, hence `1 != 11` and it returns false.
