### ISSUE TITLE
Blocktrail migrated to BTC.com

### ISSUE THREAD

**Issue by ivigamberdiev** [citp/BlockSci#175]
In python module you have class BlocktrailData, but now it's not working, because Data API now in BTC.com.
Proof: https://www.blocktrail.com/api

**Comment by maltemoeser** [comment]
Seems like the BTC API does not provide timestamps for when the block was first seen by btc.com. In addition, since we have the mempool recorder now, we can probably get rid of the `BlocktrailData` class

**Comment by maltemoeser** [comment]
Will be removed in the next release. Built-in alternatives include using the `BlockchainInfoData` or the mempool recorder. There might be other APIs available online that users can use, too.
