### ISSUE TITLE
Duplicate methods in Tx and some notes about Address

### ISSUE THREAD

**Issue by ivigamberdiev** [citp/BlockSci#178]
In python module for class blocksci.Tx have methods like ins/inputs and outs/outputs, but this methods have same task. In class blocksci.Address have only ins and outs and so maybe need leave ins and outs methods. Also, I have some notes about class blocksci.Address. Firstly, we have method ins() and attribute outs, expected only methods or attributes. Secondly, return bevavior is unsimilar, because ins return list, but outs return Iterator.

**Comment by maltemoeser** [comment]
This has been changed In 0.6, where `address.ins` and `address.outs` both return iterators
