### ISSUE TITLE
Not able to convert into a tabular format

### ISSUE THREAD

**Issue by Ichigo199214** [citp/BlockSci#179]
I am a Python beginner and I want to create 1 day bitcoin blockchain transactions in the below format for a blockchain research project. Any advice/help would be very much appreciated.

![image](https://user-images.githubusercontent.com/44038360/46762194-7b4ac280-cca4-11e8-97d8-d2ad9f281364.png)

**Comment by maltemoeser** [comment]
Take a look at the [Pandas](https://pandas.pydata.org/pandas-docs/stable/10min.html) library, it allows you to construct data frames
