### ISSUE TITLE
Aggregating UTXOs based on price when they last moved 

### ISSUE THREAD

**Issue by Muggsie** [citp/BlockSci#181]
If I wanted to aggregate UTXOs based on price when they were last used in a transaction. Could this be done through your tool?

**Comment by maltemoeser** [comment]
Yes, if you're interested in the current UTXO set you could just iterate over the chain, find all outputs that are unspent and then use the provided CurrencyConverter tool to get the exchange rate based on the time of the block that includes the output.

**Comment by Muggsie** [comment]
Fantastic. This is deep waters for me so I'll begin with trying to set up everything first

Sorry for the basic question but: 

If I want to do this for say BTC, BCH, Namecoin and a couple of other compatible UTXO chains; Do I need to set up my own nodes for each chain? Or do you already have some running I can extract data from? 

Thanks for your time
