### ISSUE TITLE
Unicode Error while Exporting data to csv

### ISSUE THREAD

**Issue by Ichigo199214** [citp/BlockSci#184]
The problem is limited to very few rows and I want to figure out a way to export data even if I can get a solution to simply skip the rows causing the error.

#### Expected Result
I am exporting below data (much bigger than below) to csv. 
![image](https://user-images.githubusercontent.com/44038360/47273988-1af13600-d56c-11e8-84ba-69f9d8669460.png)

#### Actual Result
I am encountering below error pertaining to blockhash address.(Output Full Address)

![image](https://user-images.githubusercontent.com/44038360/47274004-61df2b80-d56c-11e8-8ec0-d482a7b39b7a.png)

When I convert column to list, I can see it says NulldataAddressdata:

[PubkeyHashAddress(1J6YY9GwgF8vQiEuHbsoBAybsCCgPuRgnW),
 PubkeyHashAddress(1BX2CWuV2okb2sJCjJoFyo6ebreYriRKC3),
 PubkeyHashAddress(1A49B7uEzDy1WTBKLH29CjEgdmW4emN6J2),
 PubkeyHashAddress(1NLwCYRxGoN8gzXsSMzhhXuQvCCN6gE1oL),
 NulldataAddressData()]

#### Reproduction Steps
```
import blocksci
example_block_height = 392236
chain = blocksci.Blockchain('/data/research/blocksci')
df_output = pd.DataFrame({'Trx_index'  : chain[example_block_height].
                  txes.outputs.tx_index,                                        
                  'Output_Coins' : chain[example_block_height].
                  txes.outputs.value,
                  'Output_Address_type' : chain[example_block_height].
                  txes.outputs.address_type,
                  'Output_Address_index' : chain[example_block_height].
                  txes.outputs.address.address_num,
                  'Output_Full_Address' : chain[example_block_height].
                  txes.outputs.address.all,
                 })
```

#### System Information
BlockSci version: Latest
Using AMI: Unsure
Total memory: 64GB

**Comment by hkalodner** [comment]
This will be fixed in v0.6 by just not including any raw op_return data when a NulldataAddressData object is printed.
