### ISSUE TITLE
chain.address_from_string(addr_str).in_txes(). Contradictory results

### ISSUE THREAD

**Issue by wario25m** [citp/BlockSci#188]
Hi there!
Thanx for this great tool! I really enjoy to use it!
I am using your Amazon EC2 image with the specifications recommended. 
Now unfortunately I observed some strange behavior and wondered whether you can tell me what I'm doing wrong.
When I'm checking whether old addresses were used as input:

`chain = blocksci.Blockchain("/home/ubuntu/bitcoin")`
`addr_str = "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF`
`addr = chain.address_from_string(addr_str)`
`print(addr.has_been_spent)`

... gives me 
`False`

But then 
`print(len(addr.in_txes()))` 
gives me 
`24`, 
as if the address was used as an input.

But the address can't be found in those tx as input:
`print(addr.in_txes()[-1])`
`print(addr.in_txes()[-1].inputs[0].address)`
Output:
`Tx(len(txins)=1, len(txouts)=2, size_bytes=142, block_height=545520, tx_index=348291636)`
`bc1qs2qh94n9flm2kgzr6hdftf39lnav94w2ggk4pq`

Do you have an idea what could be wrong?

**Comment by maltemoeser** [comment]
@hkalodner I can't reproduce this on the 0.6 branch

**Comment by wario25m** [comment]
RESOLVED!

I started a new server, let the node update blocks and the parser do its work and the problem was gone. May the problem have been that I ran the parser "manually" while it was programmed to update hourly? Anyway it's resolved and I am glad. Thank you

**Comment by hkalodner** [comment]
I'd imagine having two instances of the parser running concurrently on the same data would lead to corruption. This definitely isn't a case that there's any internal guards against.
