### ISSUE TITLE
address_type kills the kernel

### ISSUE THREAD

**Issue by lzl124631x** [citp/BlockSci#189]
Please provide a clear and concise description of what the problem is.

#### Expected Result
`Tx.outs.address_type` should not break kernel.

```
import blocksci
import matplotlib.pyplot as plt
import matplotlib.ticker
import collections
import pandas as pd
import numpy as np
%matplotlib notebook
# parser_data_directory should be set to the data-directory which the blocksci_parser output
chain = blocksci.Blockchain("/home/ubuntu/bitcoin")
exampleTxIndex = 300000
exampleTx = chain.tx_with_index(exampleTxIndex)
print(exampleTx.outs.address.all) # works fine
print(exampleTx.outs[0].address_type) # works fine
exampleTx.outs.address_type # breaks!!
```

#### Actual Result
see above

#### Reproduction Steps
see above

#### System Information
BlockSci version: 0.5.0
Using AMI: yes
Total memory: same as the default AMI (60G?)

**Comment by maltemoeser** [comment]
> hi there?

We are an academic team and aren't able to provide the standard of support that you might expect for a commercial project, but we'll do our best. We look at every issue, but it can sometimes take a few days until we do so.

**Comment by lzl124631x** [comment]
@maltemoeser Yeah. I totally understand. Just want to know if this bug has been acknowledged. Thanks!
