### ISSUE TITLE
Litecoin - BlockSci parser segfault (RPC)

### ISSUE THREAD

**Issue by defconst** [citp/BlockSci#191]
Thanks for looking into #132 

I also obtain a segfault at block 1201538 for Litecoin (using RPC)
(segwitActivationHeight is 1201536 in v0.6 config file)

> /usr/local/bin/litecoind -version
> Litecoin Core Daemon version v0.16.3

#### Reproduction Steps

**v0.5**
```
blocksci_parser --output-directory /var/data/blocksci_data/litecoin update --max-block 1201538 rpc --username *** --password *** --address 172.17.42.1 --port 8532 
66.7% done fetching block headers

Starting with chain of 1201537 blocks
Removing 0 blocks
Adding 1 blocks
Segmentation fault (core dumped)
```

**v0.6**
```
> blocksci_parser ./ltc.cfg update
0.0% done fetching block headers

Starting with chain of 1201537 blocks
Removing 0 blocks
Adding 1 blocks
0.00% done, Block 1201537/1201537Segmentation fault (core dumped)
```

Config file:
```
> cat ltc.cfg 
{
    "chainConfig": {
        "coinName": "litecoin",
        "dataDirectory": "/var/data/blocksci_data/litecoin/",
        "pubkeyPrefix": [
            48
        ],
        "scriptPrefix": [
            50
        ],
        "segwitActivationHeight": 1201536,
        "segwitPrefix": "ltc"
    },
    "parser": {
        "maxBlockNum": 1201538,
        "rpc": {
            "address": "172.17.42.1",
            "password": "***",
            "port": 8532,
            "username": "***"
        }
    },
    "version": 5
}
```

#### System Information
BlockSci version: master (v0.5) and v0.6 branch
Using AMI: no
Total memory: 256GB

**Comment by hkalodner** [comment]
Thanks for the report! I'll check it out before the next release.

**Comment by hkalodner** [comment]
I just ran through Litecoin on v0.6 with the disk parser to verify that was working. It completed without any problems. I can try it with the RPC parser next. There could definitely be an RPC mode bug that isn't triggered with the disk parser.

@defconst if you get a chance you might want to try running the v0.6 parser for litecoin in disk mode. If that doesn't work, there's a chance there's some sort of corruption in your local block data files in which case syncing your node from scratch might fix it.

**Comment by defconst** [comment]
@hkalodner Yes, I can confirm that v0.6 works for litecoin in disk mode.

**Comment by hkalodner** [comment]
I'm currently reindexing Litecoin since I had txindex off before. After that's done I'll be able to debug the parser in RPC mode.

This may not be much of an issue in Litecoin since at least the disk parser is working (which is much faster so definitely preferred when it's available), but whatever issue is here probably effects other blockchains as well.

**Comment by allenday** [comment]
I'm also getting a failure with LTC:
```
blocksci_parser /data/litecoin.cfg update
99.9% done fetching block headers

Starting with chain of 0 blocks
Removing 0 blocks
Adding 1521661 blocks
34.59% done, Block 1214028/1521660
Back linking transactions
99.99% done
69.24% done, Block 1355010/1521660
Back linking transactions
99.96% done
99.36% done, Block 1517321/1521660terminate called after throwing an instance of 'Json::LogicError'
  what():  LargestUInt out of Int range
```

It seems to be related to an unsigned int bug in the JsonCpp dependency, see https://github.com/ethereum/aleth/issues/4681

**Comment by hkalodner** [comment]
Interesting, I tried out litecoin with the RPC parser a little over a week ago (Before block 1517321) and it was working fine. Litecoin works with the disk parser so I'd recommend using that instead, but this is definitely a bug. I'll look into it and try to pin down what RPC data is triggering it.

**Comment by allenday** [comment]
I was having a similar problem with `master` on bitcoin. It may be resolved
on `v0.6`, I'm running it now, but it's very slow.

**Comment by defconst** [comment]
I observed the same problem with Bitcoin Cash (BlockSci v0.5/master):

```
blocksci_parser --output-directory /var/data/blocksci_data update --max-block 337900 rpc --username *** --password *** --address 172.17.42.1 --port 8432
98.7% done fetching block headers                                             
                                                                              
Starting with chain of 337870 blocks                                          
Removing 0 blocks                                                             
Adding 30 blocks                                                              
0.00% done, Block 337870/337899terminate called after throwing an instance of 'Json::LogicError'
  what():  LargestUInt out of Int range
```

**Comment by allenday** [comment]
Bitcoin RPC also failing on `v0.6`:

```
99.9% done fetching block headers

Starting with chain of 0 blocks
Removing 0 blocks
Adding 548856 blocks
2.82% done, Block 212575/548855
Back linking transactions
99.98% done
5.65% done, Block 243520/548855
Back linking transactions
99.98% done
8.47% done, Block 277278/548855
Back linking transactions
99.97% done
11.29% done, Block 303959/548855
Back linking transactions
99.98% done
14.12% done, Block 327439/548855
Back linking transactions
99.99% done
15.81% done, Block 337871/548855terminate called after throwing an instance of 'Json::LogicError'
  what():  LargestUInt out of Int range
```

**Comment by allenday** [comment]
> I observed the same problem with Bitcoin Cash (BlockSci v0.5/master):
> 
> ```
> blocksci_parser --output-directory /var/data/blocksci_data update --max-block 337900 rpc --username *** --password *** --address 172.17.42.1 --port 8432
> 98.7% done fetching block headers                                             
>                                                                               
> Starting with chain of 337870 blocks                                          
> Removing 0 blocks                                                             
> Adding 30 blocks                                                              
> 0.00% done, Block 337870/337899terminate called after throwing an instance of 'Json::LogicError'
>   what():  LargestUInt out of Int range
> ```

I have also reproduced this on bitcoin-cash with `v0.6` branch, but mine fails on block 337871:

```
99.9% done fetching block headers

Starting with chain of 0 blocks
Removing 0 blocks
Adding 555412 blocks
3.79% done, Block 212575/555411
Back linking transactions
99.96% done
7.59% done, Block 243520/555411
Back linking transactions
99.98% done
11.38% done, Block 277278/555411
Back linking transactions
99.97% done
15.18% done, Block 303959/555411
Back linking transactions
99.98% done
18.97% done, Block 327439/555411
Back linking transactions
99.99% done
21.24% done, Block 337871/555411terminate called after throwing an instance of 'Json::LogicError'
  what():  LargestUInt out of Int range
```
