### ISSUE TITLE
most_valuable_addresses() - takes greater than 20hrs? 

### ISSUE THREAD

**Issue by JRizzly** [citp/BlockSci#192]
Hey guys, I found this tool and its great for something however it seems like it hangs up on some issues. 

I was running BlockSci on the given EC2  instance on 32 GB mem, and all of the example functions worked. However when I was experimenting with the instance and wanted to run the most_valuable_addresses() on the chain, it would sit in the running stage for > 20 hrs. I know this function call is very expensive, but it seemed that after trying it several time there must have been something wrong. In the jupyter note book, it just kept the star saying it was running. Has anyone else been able to run this function in a respectable time?

Please provide a clear and concise description of what the problem is.

#### Expected Result
It to return a Dict[int, address]

#### Actual Result
continual running >20 hrs ... I know, amazon made some money off me for sure

#### Reproduction Steps
load the chain and run the function 

import blocksci
yes

#### System Information
BlockSci version: latest 
Using AMI: yes/no - 
Total memory: 32 GBs

**Comment by JRizzly** [comment]
Thanks for quick reply. 

Is there an image for the AWS EC2 instance that is for an older version of this code that has this function confirmed working?

**Comment by hkalodner** [comment]
I don't think this was in prior versions. It was mostly written for testing purposes, and was unintentionally included in the release. v0.6 should have is significantly faster method for calculating this.

**Comment by hkalodner** [comment]
This can now be done much more efficiently in v0.6 with the new `group_by` API. The following code completes in 6.5 minutes on our EC2 instance. We're still working on getting the release ready so no AWS image yet.

Btw, this is on a 64gb machine with the BlockSci Bitcoin data held fully in memory. it will be a fair amount slower (Though hopefully still fairly fast) with 32gb of memory since that will require swapping.

```python
current_address_vals = chain.blocks.outputs.unspent() \
.group_by( \
    lambda output: output.address, \
    lambda outputs: outputs.value.sum \
)
top100 = heapq.nlargest(100, current_address_vals.items(), key=operator.itemgetter(1))
```

I'm gonna swap out `chain.most_valuable_addresses()` with this python implementation rather than its current c++ implementation for backwards compatibility for the old API.

**Comment by JRizzly** [comment]
@hkalodner , you are incredible. Thanks for throwing down some lambda functions to tackle that bug. 

Does the EC2 image you guys have linked from the read me include the new `group_by` API? 

So if I ran: 

`current_address_vals = chain.blocks.outputs.unspent() \
.group_by( \
    lambda output: output.address, \
    lambda outputs: outputs.value.sum \
)
top100 = heapq.nlargest(100, current_address_vals.items(), key=operator.itemgetter(1))`

would it work on the instance I have up right now?

Appreciate the feedback.

**Comment by maltemoeser** [comment]
@JRizzly this will be possible in the next release, it's not available in the current AMI. But if you're comfortable with compiling BlockSci yourself, you could try the v0.6 branch today

**Comment by JRizzly** [comment]
@hkalodner Thanks for the code/comments above: I haven't looked at v0.6 but in v0.5 unspent is a member variable, and not callable. So it should be 
`current_address_vals = chain.blocks.outputs.unspent` 
without the "()" for v0.5. 

@maltemoeser Thanks

Cool stuff below: 
Interesting stats I found as of Nov 2018: 

- As of Block 548,902 (Nov 2018), there are 57,941,684 address that contain UTXOs
- As of Block 548,902 (Nov 2018), 42,153,371 of those addresses or 73% are held in Pubkey or PubkeyHash addresses. 
- As of Block 548,902 (Nov 2018) about 24% of Pubkey or PubkeyHash addresses contain greater than $65. 

The most expensive function as far as time took about 760 seconds, on an EC2 instance, r5d.2xlarge on V0.5. 

Can't wait to see improvements  v0.6. This is a great product. I hope to see this project continue.
