### ISSUE TITLE
Missing v0.5 tag and release on github

### ISSUE THREAD

**Issue by allenday** [citp/BlockSci#193]
[v0.5 is documented as released](https://citp.github.io/BlockSci/changelog.html#version-0-5-0).

but is missing from project [releases](https://github.com/citp/BlockSci/releases) and [tags](https://github.com/citp/BlockSci/tags) pages.

**Comment by hkalodner** [comment]
Whoops, I guess I totally forgot to add an actual release to GitHub for that. I've now added one.
