### ISSUE TITLE
Dogecoin parses on master, fails on v0.6 branch over RPC

### ISSUE THREAD

**Issue by allenday** [citp/BlockSci#194]
Dogecoin parses on `master`, fails on `v0.6` branch over RPC

#### Expected Result
Dogecoin parses successfully on `master`

#### Actual Result
Dogecoin fails to parse on `v0.6`

#### Reproduction Steps
```
blocksci_parser /data/dogecoin.cfg update
Error loading chain index. Reparsing from scratch
99.9% done fetching block headers

Starting with chain of 2232052 blocks
Removing 1 blocks
Adding 229202 blocks
terminate called after throwing an instance of 'std::runtime_error'
  what():  Trying to open bloom filter of wrong size
```

```
cat /data/dogecoin.cfg 
{
    "chainConfig": {
        "coinName": "custom",
        "dataDirectory": "/data/dogecoin-parser",
        "pubkeyPrefix": [],
        "scriptPrefix": [],
        "segwitActivationHeight": 0,
        "segwitPrefix": ""
    },
    "parser": {
        "maxBlockNum": -6,
        "rpc": {
            "address": "10.4.1.2",
            "password": "y",
            "port": 3389,
            "username": "x"
        }
    },
    "version": 5
}
```

#### System Information
BlockSci version: v0.6 2018-11-06
Using AMI: no
Total memory: 400GB

**Comment by maltemoeser** [comment]
Not sure if it's related to the crash, but setting `segwitActivationHeight` to `0` would mean it is activated from the first block (which currently is only applicable to Bitcoin regtest). If Dogecoin does not use Segwit at all, you can set it to `2147483647`.

**Comment by hkalodner** [comment]
This is presumably the same problem as exists in #195. It's entirely possible I've managed to break the parser in a recent commit 😄, but if you're living on v0.6 and updating to the newest version you're probably hitting bugs due the data format still getting updates which breaks the parser. It should stabilize within the next couple weeks (or hopefully sooner).

**Comment by allenday** [comment]
parses successfully if I delete the `v0.5.x` index files from `master`
