### ISSUE TITLE
Dash parses on master, fails on v0.6 branch over RPC

### ISSUE THREAD

**Issue by allenday** [citp/BlockSci#195]
Dash parses on `master`, fails on `v0.6` branch over RPC

#### Expected Result
Dash parses successfully on `master`

#### Actual Result
```
blocksci_parser /data/dash.cfg update
Error loading chain index. Reparsing from scratch
99.9% done fetching block headers

Starting with chain of 875862 blocks
Removing 1 blocks
Adding 89962 blocks
terminate called after throwing an instance of 'std::runtime_error'
  what():  Trying to open bloom filter of wrong size
```

#### Reproduction Steps
```
blocksci_parser /data/dash.cfg update
Error loading chain index. Reparsing from scratch
99.9% done fetching block headers

Starting with chain of 875862 blocks
Removing 1 blocks
Adding 89962 blocks
terminate called after throwing an instance of 'std::runtime_error'
  what():  Trying to open bloom filter of wrong size
```

#### System Information
BlockSci version: v0.6
Using AMI: no
Total memory: 400GB

**Comment by hkalodner** [comment]
v0.6 is still a work in progress with the parser format receiving periodic updates. There's a reasonable chance running the parser from scratch will fix this. The data format is still a bit in flux as v0.6 will require a fresh parse on top of v0.5 so I'm making a number of fixes and improvements.

**Comment by allenday** [comment]
this is working successfully if I do a clean run and don't try to reuse indexes from v0.5.
