### ISSUE TITLE
Can't build first tx of the Bitcoin Blockchain

### ISSUE THREAD

**Issue by ClementPavue** [citp/BlockSci#198]
I tried to instanciante in cpp the first tx of the bitcoin blockchain eg. `4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b`

#### Expected Result
A instance of the tx.

#### Actual Result
No match hash

#### Reproduction Steps
```
try{
  Transaction t("4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",chain->getAccess());
}catch(const std::exception &e){
  std::cout << e.what();
}
```
Gives me : 
No match hash

And 

```
first(0,chain.getAccess());
std::cout << first.getHash().GetHex() << std::endl;
```

Gives me : 
4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b

To me the error is there:
```
    uint32_t getTxIndex(const blocksci::uint256 &hash, blocksci::HashIndex &index) {
        auto txIndex = index.getTxIndex(hash);
        if (txIndex == 0) {
            throw blocksci::InvalidHashException();
        }
        return txIndex;
    }
```

#### System Information
BlockSci version:  Last on master
Using AMI: no
Total memory: 32Gb

**Comment by hkalodner** [comment]
Hmm yep, you're right on the mark with what's causing the bug. I think this should be fairly easy to fix.

**Comment by hkalodner** [comment]
This should be fixed in the next release.
