### ISSUE TITLE
cluster.addresses is slow

### ISSUE THREAD

**Issue by sirpy** [citp/BlockSci#200]
#### Expected Result
What you expected to happen.
get first address/out of cluster quickly

#### Actual Result
What happened instead.
takes time for large clusters

#### Reproduction Steps
```
import blocksci,toolz
c = clustermanager.cluster_from_address(addr)
\#slow
print(toolz.first(c.addresses))

```
#### System Information
BlockSci version: 0.5
Using AMI: no
Total memory: 60gb

**Comment by hkalodner** [comment]
There are a couple improvements in v0.6 that should eliminate this issue.

**Comment by salber** [comment]
when is v0.6? due
