### ISSUE TITLE
litecoin - address_from_string returns None when the address exists

### ISSUE THREAD

**Issue by rg687** [citp/BlockSci#203]
Please provide a clear and concise description of what the problem is.

#### Expected Result
get an address from address_from_string when this address exist

#### Actual Result
Get an address instead of None 
https://chainz.cryptoid.info/ltc/tx.dws?40b41a889a8310529620cc2dae51b1df90104c0baa70d5020c1569729aaa16db.htm

#### Reproduction Steps
```
import blocksci

chain = blocksci.Blockchain("/home/litecoin/ltc.cfg")
print (type(chain.address_from_string("LLMRAtr3qBje2ySEa3CnZ55LA4TQMWnRY3")))
print (chain.tx_with_hash('40b41a889a8310529620cc2dae51b1df90104c0baa70d5020c1569729aaa16db').outs[0].address.address_string)

```
returns
``` 
<class 'NoneType'>
LLMRAtr3qBje2ySEa3CnZ55LA4TQMWnRY3
```

#### System Information
BlockSci version: 0.6
Using AMI: yes/no
Total memory: 64go

**Comment by maltemoeser** [comment]
Cannot reproduce this on the latest 90c442af9ea1727521279d5b00d683b122f0cd8b

```
In [10]: chain.address_from_string("LLMRAtr3qBje2ySEa3CnZ55LA4TQMWnRY3")                                                          
Out[10]: PubkeyHashAddress(LLMRAtr3qBje2ySEa3CnZ55LA4TQMWnRY3)

In [11]: print(type(chain.address_from_string("LLMRAtr3qBje2ySEa3CnZ55LA4TQMWnRY3")))                                             
<class 'blocksci.PubkeyHashAddress'>
```
