### ISSUE TITLE
litecoin cluster.addresses, cluster.txes() crash (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by rg687** [citp/BlockSci#205]
Please provide a clear and concise description of what the problem is.

#### Actual Result
The problem arises with list(cluster.addresses) or cluster.in_txes() or cluster.out_txes() or cluster.txes() all make the kernel crash with jupyter notebook.
Segmentation fault (core dumped)

#### Reproduction Steps
```
import blocksci
chain = blocksci.Blockchain("/home/litecoin/ltc.cfg")
addr = 'LKxmccbLHcLkPHBVsArmgiLmupy8B8mvAd'
address = chain.address_from_string(addr)
# current workaround to disable change the address heuristic
no_change_heuristic = blocksci.heuristics.change.legacy() - blocksci.heuristics.change.legacy()

cm = blocksci.cluster.ClusterManager.create_clustering("/opt/litecoin-clusters", chain, heuristic=no_change_heuristic)

# get the cluster containing a specific address
cluster = cm.cluster_with_address(address)
print ('cluster {}\n balance {}\n size {}'.format(cluster.index, cluster.balance(), cluster.size()))
```
```
99.94% done
cluster 18561707
balance 60646871053000
size 2
```

The problem arises with list(cluster.addresses) or cluster.in_txes() or cluster.out_txes() or cluster.txes() all make the kernel crash with jupyter notebook. Segmentation fault (core dumped)

It seems I can get the different addresses belonging in a cluster with address_num but how can I use it to recreate an Address from the internal identifier of the address?
```
cluster.addresses.address_num
array([30649918, 31255676], dtype=int64)
```

#### System Information
BlockSci version: 0.6
Using AMI: yes/no no
Total memory: 64go

**Comment by maltemoeser** [comment]
Thanks for the report. 0.6 is currently under development, and some things related to addresses are indeed currently broken.

> It seems I can get the different addresses belonging in a cluster with address_num but how can I use it to recreate an Address from the internal identifier of the address?

You can use `address_from_index`:
```python
chain.address_from_index(idx)
```

**Comment by hkalodner** [comment]
Thanks for the report! This was a regression introduced in v0.6 which is now fixed.
