### ISSUE TITLE
blocksci_parser not parsing past block Bitcoin #473,005

### ISSUE THREAD

**Issue by nelsontodd** [citp/BlockSci#208]
#### Expected Result
blocksci_parser builds a chain of 549,984 blocks.

#### Actual Result
blocksci_parser builds a chain of 473,005 blocks. 

#### Reproduction Steps
I have removed and resynced my block data with bitcoind multiple times, and ensured my copy of blocksci_parser was compiled from the latest commit. This was failing before the latest commit as well, and I'm not sure what the issue is.

We wrote our own parser (https://github.com/unchained-capital/bitcoin-iterate) that finishes syncing all the way through, but it has to skip block number 473,005. I'm thinking that something in this block is breaking blocksci, but considering no one else is having this issue I'm stumped.

#### System Information
BlockSci version: latest
Using AMI: yes
Total memory: 32Gb

**Comment by nelsontodd** [comment]
Update: the issue was a corrupt block after all

**Comment by salber** [comment]
How did you fix the corrupt block? bitcoind --reindex? Did you delete the block file?

Any tips would be appreciated

**Comment by nelsontodd** [comment]
I deleted the entire .bitcoin directory and resynced.
