### ISSUE TITLE
BitcoinCash segfault at block 555674

### ISSUE THREAD

**Issue by defconst** [citp/BlockSci#210]
After the fixes in the v0.6 branch (#132) parsing of BitcoinCash worked.
At height 555674 I get a segmentation fault again.

#### Reproduction Steps

> $ blocksci_parser /var/data/blocksci_data/bch.cfg update
> 100.0% done fetching block headers
> Starting with chain of 555673 blocks
> Removing 0 blocks
> Adding 1 blocks
> 0.00% done, Block 555674/555674Segmentation fault (core dumped)

config file

> $ cat bch.cfg
> {
>     "chainConfig": {
>         "coinName": "bitcoin_cash",
>         "dataDirectory": "/var/data/blocksci_data",
>         "pubkeyPrefix": [
>             0
>         ],
>         "scriptPrefix": [
>             5
>         ],
>         "segwitActivationHeight": 2147483647,
>         "segwitPrefix": "NONE"
>     },
>     "parser": {
>         "disk": {
>             "blockMagic": 3652501241,
>             "coinDirectory": "/var/data/block_data",
>             "hashFuncName": "doubleSha256"
>         },
>         "maxBlockNum": 555674
>     },
>     "version": 5
> }

#### System Information
BlockSci version: v0.6 branch (commit 8b89972)
Using AMI: no
Total memory: 256 GiB
Bitcoin ABC Daemon version v0.18.2.0-6a51d4f37

**Comment by hkalodner** [comment]
Wow, I think that's the fastest I've ever seen the parser be fixed and then break. I'll look into this.

**Comment by defconst** [comment]
I upgraded Bitcoin-ABC to the latest version (0.18.5) and parsed the blockchain from scratch. I was now able to parse block 555674. But I keep getting some other segfaults during core-update:

```
blocksci_parser /var/data/blocksci_data/bch.cfg core-update                
100.0% done fetching block headers
Starting with chain of 556750 blocks
Removing 0 blocks
Adding 30 blocks
0.00% done, Block 556751/556780terminate called after throwing an instance of 'NextQueueFinishedEarlyException'
  what():  Next queue finished early
Aborted (core dumped)          
```     
Only really small chunk sizes seem to work for the core-update (e.g. 5 blocks):

```
blocksci_parser /var/data/blocksci_data/bch.cfg update                     
100.0% done fetching block headers
Starting with chain of 556750 blocks
Removing 0 blocks
Adding 5 blocks
0.00% done, Block 556751/556755
Back linking transactions
95.13% done
Updating hash index
Updating index with 1841 txes
0.00% done
Updating address index
Updating index with 1841 txes
0.00% done
Updating index with scripts of type multisig_script
0.00% done
```

**Comment by hkalodner** [comment]
I successfully recreated the segfault locally. As long as I can figure out what's going wrong, I should have this fixed in the next couple days.

**Comment by hkalodner** [comment]
So I tracked down the problem. BlockSci parses transactions in the order they appear in a block. Bitcoin Cash introducing CTOR means that this no longer holds true. The parser breaks on the first block which includes a transaction spending an output of a transaction that occurs later than it in the same block.

This is going to be somewhat ugly to fix.

**Comment by hkalodner** [comment]
This required some serious plumbing, but the parser now works independently of any ordering constraints for  transactions within a given block. This means that Bitcoin Cash should be working now!

**Comment by defconst** [comment]
Great, yes it works again :+1: 

Parsing in one step didn't work
```
100.0% done fetching block headers
Starting with chain of 0 blocks
Removing 0 blocks
94.15% done, Block 536043/556760
Back linking transactions
99.98% done
97.92% done, Block 546597/556760terminate called after throwing an instance of 'NextQueueFinishedEarlyException'
  what():  Next queue finished early
```
but storing the blocks up to height 540000 and restarting the parser from this point worked.

Thanks!

**Comment by hkalodner** [comment]
I posted here a little too soon. I was able to complete the parse, but I think I managed to create another bug in the process. I'm currently trying to figure out what's going on.

**Comment by jredondo** [comment]
Similar issue here using v0.6 branch and BlockSci's AMI:
```
Back linking transactions
99.98% done
89.41% done, Block 476275/561288
Back linking transactions
99.98% done
93.14% done, Block 535514/561288
Back linking transactions
99.98% done
96.88% done, Block 546595/561288terminate called after throwing an instance of 'NextQueueFinishedEarlyException'
  what():  Next queue finished early
```

**Comment by defconst** [comment]
@jredondo 
Step 1: set `"maxBlockNum": 540000` in the config file
Step 2: `"maxBlockNum": -6`

**Comment by maltemoeser** [comment]
The `NextQueueFinishedEarlyException` occurring should (hopefully) be fixed now
