### ISSUE TITLE
When I run blocksci, it says "Failed to open block file "/root/.bitoin/blocks/blk01439.dat"

### ISSUE THREAD

**Issue by suban1440** [citp/BlockSci#213]
Please provide a clear and concise description of what the problem is.

#### Expected Result
I would like to update continuously using the following command.

"blocksci_parser --output-directory /mnt/hdd1/blocksci_db/ update --max-block -5 disk --coin-directory /root/.bitoin/"

#### Actual Result
I have excuted the following command.
"blocksci_parser --output-directory /mnt/hdd1/blocksci_db/ update --max-block 600000 disk --coin-directory /root/.bitoin/"

The above command did not cause any problems by raising the value of "--max-blocks".
But, The following command is causing the problem.
"--max-block -5"

![image](https://user-images.githubusercontent.com/40881624/48929724-aa548500-ef2e-11e8-8116-8ed3ab8c8656.png)

I want to know how to solve it.

#### System Information
BlockSci version: 0.5.0
Using AMI: no
Total memory: 128GB

**Comment by maltemoeser** [comment]
This looks like a typo to me, `.bitcoin` should be `.bitcoin`?
