### ISSUE TITLE
python program stuck in cluster.size()

### ISSUE THREAD

**Issue by juqiangl** [citp/BlockSci#214]
Hi,

I am trying to get the biggest clusters and their balances, without knowing how, I just tried to print all clusters' size and balance, but after returning some results, it stuck on one cluster.size().  Is it because the size of this cluster is too big?  Or is there a better way to just show the largest clusters?  The database I generated is Bitcoin, up to block 400000

Thanks,
Jeff

Here is my code:
...

clusters = cm.clusters()                                                                                                                                                                                            

print ("Total clusters: " + str(len(clusters)))                                                                                                                                                                     

for clus in clusters:

  print ("Cluster size is: " + str(clus.size()) + ", and balance is: " + str(clus.balance()/1e8))              
...

It printed some result then stuck:

Total clusters: 6246884
Cluster size is: 1, and balance is: 0.01
Cluster size is: 1, and balance is: 0.01
Cluster size is: 1, and balance is: 0.01
Cluster size is: 1, and balance is: 2.95995904
Cluster size is: 3, and balance is: 0.01175545
Cluster size is: 1, and balance is: 0.01934464
Cluster size is: 125, and balance is: 0.0
Cluster size is: 1, and balance is: 1e-08
Cluster size is: 1, and balance is: 0.001
Cluster size is: 1, and balance is: 45.82
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 98.0
Cluster size is: 1, and balance is: 200.0
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 497.0
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 35.78
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 367.75849319
Cluster size is: 1, and balance is: 143.62
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 35.784
Cluster size is: 1, and balance is: 21.0
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 65.0
Cluster size is: 1, and balance is: 39.81
Cluster size is: 1, and balance is: 98.48055
Cluster size is: 1, and balance is: 37.0
Cluster size is: 1, and balance is: 100.0
Cluster size is: 1, and balance is: 24.31

**Comment by charithccmc** [comment]
clus.size () method is slow, try clus.type_equiv_size. It should be faster than size()

**Comment by juqiangl** [comment]
Thanks, @charithccmc. Trying clus.type_equiv_size right now, so far it's stuck at the same place, let's see if it's faster than size().

**Comment by charithccmc** [comment]
Rerun the clusterer without any change address heuristics.

`chain = blocksci.Blockchain(<Path-to-Blocksci-Data>)
 cluster_manager = blocksci.cluster.ClusterManager(<Path-to-Blocksci-Cluster-Data>, chain)
 no_change = blocksci.heuristics.change.legacy() - blocksci.heuristics.change.legacy()
 cluster_manager.create_clustering(<Path-to-Blocksci-Cluster-Data>, chain, no_change, True)
`

**Comment by juqiangl** [comment]
Thanks.  I tried without calling .balance(), but it still stuck.  I am rebuilding clustering as @charithccmc suggested, and will try it after it's done.
