### ISSUE TITLE
Can anyone recommend an IDE, a debugger?

### ISSUE THREAD

**Issue by salber** [citp/BlockSci#215]
Anybody debugging BlockSci in an IDE?

Anybody imported the CMakeLists.txt into an IDE?

emacs and gdb?

**Comment by nelsontodd** [comment]
vim and tmux

**Comment by maltemoeser** [comment]
On OSX, Xcode is great for developing and debugging. You can generate an Xcode project using Cmake:
```
mkdir xcode && cd xcode
cmake -G Xcode ..
```
