### ISSUE TITLE
Where can I find some sample code in Python?

### ISSUE THREAD

**Issue by juqiangl** [citp/BlockSci#216]
Guys,

Anybody know where to find some BlockSci example code in Python?

**Comment by juqiangl** [comment]
Thanks, saw the code in Notebooks.  I am looking for examples about how to use different heuristics building clusters.

**Comment by maltemoeser** [comment]
Here's a brief example for how to use different change address heuristics: https://gist.github.com/maltemoeser/b8ff7be6be23459c659207cdf1c42094

An overview of existing change address heuristics is available in the documentation: https://citp.github.io/BlockSci/reference/heuristics/change.html

**Comment by juqiangl** [comment]
Thanks, @maltemoeser!
