### ISSUE TITLE
Blocksci AMI & Optimizations

### ISSUE THREAD

**Issue by vittico** [citp/BlockSci#221]
Hello guys! 

I have two silly questions. 

1.- I can not find AMI ami-0d0091e593d44cce1 on us-east-1, seems to be deregistered, is there a new ami available?

2.- I tried to build a new ami, based on ubuntu 18. I follow instructions almost religiously, I found some performace changes and would like to ask if there are some tweaks on the original ami. I checked  ulimits and found and found changes on max process, max open files and max memory locked from original blocksci ami based on ubuntu 16 to my ami based on ubuntu 18. Is there any other optimizations I should be aware?

**Comment by maltemoeser** [comment]
Sorry about the image being unavailable, that should be fixed now!

**Comment by hkalodner** [comment]
The open file limit is the only system configuration change. We should note this somewhere in the documentation. For some reason Ubuntu has a ridiculously low limit. BlockSci has a couple RocksDB databases that it depends on which leads to a large number of open files.

I followed the instructions from https://ro-che.info/articles/2017-03-26-increase-open-files-limit and https://underyx.me/2015/05/18/raising-the-maximum-number-of-file-descriptors to raise the limit.

We should probably note this in the documentation somewhere. It's only required on certain systems so it's not part of the general instructions, but it is necessary sometimes.
