### ISSUE TITLE
Updated Memory Requirements

### ISSUE THREAD

**Issue by nelsontodd** [citp/BlockSci#222]
#### System Information AWS r4.xlarge with 30gig RAM
BlockSci version: Latest
Using AMI: no
Total memory: 30G

Hi,

What are the latest system requirements to run blocksci? I'm getting a segfault now all of a sudden.

**Comment by maltemoeser** [comment]
When exactly are you getting a segfault and on which chain?

For Bitcoin we definitely recommend at least 60GB of memory.

**Comment by hkalodner** [comment]
We previously had a recommendation of 64GB, but a listed minimum requirement of 32GB in the documentation (https://citp.github.io/BlockSci/setup.html). I think this now needs to be updated to a minimum of 64GB. It also might be good to move or duplicate some of this into the readme so it is more apparent.

**Comment by nelsontodd** [comment]
Awesome. Thank y'all so much!
