### ISSUE TITLE
Guidence about parser

### ISSUE THREAD

**Issue by chaoyanglv** [citp/BlockSci#229]
BlockSci VERSION:0.5.0
Hello guys! I am sorry to disturb you. 
There are some questions about parsering bitcoin data files disturbing me. I have downloaded the bitcoin data files from Bitcoin core client, but I am not sure how to parser the data files by means of Disk Mode.
Could you give some guidence details (such as command lines etc)?
Thanks a lot!

**Comment by brockelmore** [comment]
See here: https://citp.github.io/BlockSci/setup.html


If you have compiled it already run this:

`blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin`


You can change "bitcoin-data" to the directory you want blocksci to use. coin-directory is the directory of your bitcoin files. This command will take at least a few hours depending on your system.

**Comment by chaoyanglv** [comment]
Thank you!
