### ISSUE TITLE
Avoiding Reorg/staying up-to-date Blocksci

### ISSUE THREAD

**Issue by brockelmore** [citp/BlockSci#231]
Per the [setup](https://citp.github.io/BlockSci/setup.html):

"It is recommended that the Blockchain be kept approximately 6 blocks back from the head of the chain in order to avoid imperfect reorg handling in BlockSci."

Is this still a concern as of v0.5 & v0.6? It seems (from first look thru) that there is reorg handling in the parser, so if I update my chain to be at the tip of the chain what errors may I encounter (corrupt db, wrong indexes, broken transaction graph...), besides the study referencing "throwing an exception"?

Assuming it is still bad:
If the library "ignores" blocks ahead of the _d_ parameter, is there no way to have an ephemeral extension to include those _d_ blocks? Could you bolt on that extension in exchange for a hit to memory consumption & speed when querying tip blocks (optionally of course)? It seems for a small minority of the data, you can give up some of the benefits that Blocksci data structures provide to allow better real-time analytics. Maybe something comparable in concept to something like an [SQL staging table](http://mysql.rjweb.org/doc.php/staging_table)? I know this is discussed somewhat in #2 but I think there is a solution where we don't need full platform independence to achieve real-time analytics.

I know there are a lot of priorities for v0.6, but if there is anything that can be done to more reliably keep Blocksci up to date, I think it would be a great addition to have it as a real-time analysis tool. I, unfortunately, program mainly in go and python and haven't dove into c++ to help, but this project does inspire me to do so. That being said, if you guys have some ideas about how you could implement this and want help on the python side of things I am happy to help.

**Comment by maltemoeser** [comment]
The reorg detection has not been extensively tested, so we wouldn't recommend relying on it too much.

BlockSci is built around the idea that most scientific blockchain analysis can be done using static snapshots of the blockchain. With that in mind, true real-time analysis is beyond the scope of our  current goals with BlockSci.
