### ISSUE TITLE
Is possible to get address tag from transaction or other method?

### ISSUE THREAD

**Issue by alex3dbros** [citp/BlockSci#232]
#### System Information (if applicable)
BlockSci version: 0.6
Using AMI: no, using local build
Total memory: 195 GB

Hi there, I managed to get v0.6 working and I am wondering if it's possible to obtain the 
address tag similar to the blockchain python api:
address.transactions[0].outputs[1].addr_tag .

Here's the info that I am trying to retrieve : https://www.blockchain.com/btc/tags?filter=16&offset=0

Each address has a tag added to it, I tried lookin over all functions and classes params but I could not find anything for txes or addresses.

Thanks!

**Comment by maltemoeser** [comment]
In BlockSci you can tag address clusters, but [we don't provide any address tags with BlockSci](https://github.com/citp/BlockSci/wiki#toc-analysis-tagged-addresses)
