### ISSUE TITLE
Jupyter Notebook gives "ModuleNotFound: BlockSci" error

### ISSUE THREAD

**Issue by blatherdrift** [citp/BlockSci#235]
When I try to import blocksci using jupyter notebook it tells me ModuleNotFound!! :( It works fine in the python3 console but for some reason Jupyter notebook won't work proper

#### System Information
BlockSci version: (latest)
Using AMI: yes/no?? I compiled this myself
Total memory: 64gig

**Comment by maltemoeser** [comment]
Are you using the correct (Python3) kernel?

**Comment by maltemoeser** [comment]
Closing it for now as this is not an issue with BlockSci itself.
