### ISSUE TITLE
bits to difficulty?

### ISSUE THREAD

**Issue by andreasp888** [citp/BlockSci#236]
How do I acquire difficulty level data directly using the Python interface or transform "bits" in the block header to the difficulty level?
Thank you.

**Comment by maltemoeser** [comment]
You could use the [calc_difficulty(nBits)](https://github.com/petertodd/python-bitcoinlib/blob/05cbb3c9560b36cfe71bac06085a231a6244e13a/bitcoin/core/__init__.py#L556) function from python-bitcoinlib

**Comment by andreasp888** [comment]
Thank you @maltemoeser!
