### ISSUE TITLE
Compilation error during make

### ISSUE THREAD

**Issue by henrychongtw** [citp/BlockSci#238]
Hi all, I am using an Ubuntu linux bash shell on Windows 10 to compile Blocksci
BlockSci version: latest
Using AMI: no
Total memory: 48GB
Cmake version: 3.13.2
gcc version: 7.4
g++ version: 7.4

I tried a lot of advice found in the other issues, but still came up with this error while trying to compile locally.

```
In file included from /mnt/c/henryshawn/analysis/BlockSci/src/address/address.cpp:11:0:
/mnt/c/henryshawn/analysis/BlockSci/src/../include/blocksci/../blocksci/address/address.hpp:20:10: fatal error: range/v3/view/any_view.hpp: No such file or directory
 #include <range/v3/view/any_view.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/blocksci.dir/build.make:75: recipe for target 'src/CMakeFiles/blocksci.dir/address/address.cpp.o' failed
make[2]: *** [src/CMakeFiles/blocksci.dir/address/address.cpp.o] Error 1
CMakeFiles/Makefile2:6389: recipe for target 'src/CMakeFiles/blocksci.dir/all' failed
make[1]: *** [src/CMakeFiles/blocksci.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

this happens when I run the following command:
`CC=gcc-7 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Release ..`

Any ideas?
Thanks!

**Comment by maltemoeser** [comment]
> `range/v3/view/any_view.hpp: No such file or directory`

Were the submodules checked out correctly? Did you try running 

```
git submodule init
git submodule update --recursive
```
