### ISSUE TITLE
Blocksci Mempool Recorder help

### ISSUE THREAD

**Issue by blatherdrift** [citp/BlockSci#239]
#### System Information (if applicable)
BlockSci version:  0.5.1
Using AMI: no
Total memory: 64 gigs

Hello,
I've got the memory pool recorder running but I can't seem to figure out how to query the data. I understand from the instructions that

"This data is accessable directly through the python API via Tx.time_seen and Block.time_seen which will return a datetime or None if the transaction or block was not observed."

but when I try to run a query with Tx.time_seen('my tx hash') it just gives a syntax error... Not really understanding how this works... My thoughts were I could use the recorder to investigate possible double-spends through this kind of query. I guess I just don't understand how to query this properly.

**Comment by maltemoeser** [comment]
[`Tx.time_seen`](https://citp.github.io/BlockSci/reference/chain/tx.html#blocksci.Tx.time_seen) is a property of a `Tx` object.

If you want the time seen of a specific tx, you need to do
```python
tx = chain.tx_with_hash("<your hash>")
tx.time_seen
```

**Comment by blatherdrift** [comment]
thanks this helps immensely with everything not just the mempool recorder
