### ISSUE TITLE
Blocksci_cluster manager crashes kernel immediately

### ISSUE THREAD

**Issue by blatherdrift** [citp/BlockSci#240]
Setup BlockSci 0.5, ran the clustering manager to 100% then tried the example cluster query at the bottom of the example notebook. It immediately crashes the Junyper kernel, never giving a result. Any idea what I can do to get this working? Sorry, not much documentation on this so I am not sure where to go from here

#### System Information
BlockSci version: 0.5
Using AMI: no
Total memory: 64 gigs

**Comment by blatherdrift** [comment]
Ran it through the python console and got this 

Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksci
>>> chain = blocksci.Blockchain('/home/blocksci/bitcoin-data')
>>> cm = blocksci.cluster.ClusterManager('home/blocksci/cluster-data', chain)
>>> address = chain.address_from_string("3EhLZarJUNSfV6TWMZY1Nh5mi3FMsdHa5U")
>>> cluster = cm.cluster_with_address(address)
>>> sum(address.balance(494653) for address in cluster.addresses) / 1e8

Segmentation fault (core dumped)

**Comment by blatherdrift** [comment]
I've been messing around with the parsed data-base a bit and the error message has changed

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-cb03126395c2> in <module>
      1 # Find the balance held by the cluster containing the given address at block height 494653
      2 address = chain.address_from_string('3EhLZarJUNSfV6TWMZY1Nh5mi3FMsdHa5U')
----> 3 cluster = cm.cluster_with_address(address)
      4 sum(address.balance(494653) for address in cluster.addresses) / 1e8

TypeError: cluster_with_address(): incompatible function arguments. The following argument types are supported:
    1. (self: blocksci.cluster.ClusterManager, address: Address) -> blocksci.cluster.Cluster

Invoked with: <blocksci.cluster.ClusterManager object at 0x7fe7559430d8>, None

**Comment by maltemoeser** [comment]
We'll try to look into this, at least to make sure that it's not occurring in 0.6, but not really sure what's going wrong here. Can you try using balance without the height to make sure that's not the problem?

**Comment by pablolarrimbe** [comment]
I seem to be getting the exact same behaviour in 0.5, also 64GB of RAM.

I was able to run the entire sample script, but my kernel crashes here:

cluster = cm.cluster_with_address(address)

I'm happy to provide any logs that might help troubleshoot/get to the bottom of this.
