### ISSUE TITLE
Parser: Address not linked to Transaction (but vice versa)

### ISSUE THREAD

**Issue by Felix0301** [citp/BlockSci#244]
Searching for all transactions where address X was an output (with out_txes())

#### Expected Result
Get all transactions where X is an output (manually checked that there should be at least 1)

#### Actual Result
No transactions related to this address. If I query for a transaction that I know is connected to the address directly, BlockSci finds it and also lists the address in the outputs

This issue appears to affect only transactions that were included in blocks that are newer than my intitial parsing process. I have the parser scheduled to run with the recommended:

@hourly /usr/local/bin/blocksci_parser --output-directory /home/ubuntu/bitcoin-data update --max-block -6 disk --coin-directory /home/ubuntu/.bitcoin

Any ideas why this might happen or how to fix it?

#### System Information
BlockSci version: 0.5.0
Using AMI: yes
Total memory: 64 GB

**Comment by ClementPavue** [comment]
Add the same issue while trying to switch from 0.5 to 0.6 and 0.5 again. To me I had to uninstall BlockSci reinstall and reparse the chain

**Comment by maltemoeser** [comment]
@ClementPavue this bug occurred on both 0.5 and 0.6 for you?

**Comment by ClementPavue** [comment]
Only on 0.5 after installing 0.6 and downgrading back to 0.5

**Comment by maltemoeser** [comment]
A working code example to reproduce this bug would be great (at the minimum to check whether it's still happening on v0.6)
