### ISSUE TITLE
Restarting with chain of 0 blocks after segmentation error

### ISSUE THREAD

**Issue by kepler16bv** [citp/BlockSci#247]
#### System Information (if applicable)
BlockSci version: not sure how to check but I compiled it myself from master like 10 days ago
Using AMI: no
Total memory: 64GB

Running the parser I reached block 460k, then I got a segmentation error. After that I tried to restart with the command below (which is the same command I used for the initial run) but the parser started from scratch.

The command I used both times:
```blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin```

The log obtained in the second run:
``` 
100.0% done fetching block headers
Starting with chain of 0 blocks
Removing 0 blocks
Adding 561620 blocks
0.00% done, Block 1/561620^C
```

So is this normal? How do I start from the last parsed block?

**Update**: 
FYI, the data is still in the output directory:
``` 
 >du -h bitcoin-data/
595M    bitcoin-data/parser/address
4,0K    bitcoin-data/parser/utxoAddressState
705M    bitcoin-data/parser
82G     bitcoin-data/chain
37G     bitcoin-data/scripts
14G     bitcoin-data/hashIndex
516K    bitcoin-data/addressesDb
4,0K    bitcoin-data/mempool
133G    bitcoin-data/
```

**Comment by maltemoeser** [comment]
If the parser crashes mid-run it's likely that the data files are corrupted and you need to start from scratch, see also #33. I'd recommend deleting the old data directory before attempting a new parse.

**Comment by kepler16bv** [comment]
Ok thanks for the answers and the reference.

What if the process has been completed? Should I keep it alive forever? Or in that case I can stop and restart on demand? I'm asking because before going further I would like to be sure at this point.

Thanks

**Comment by maltemoeser** [comment]
If the parser finishes successfully it will stop. You can then continue the parse when your node has received new blocks, or even [set up a cronjob](https://citp.github.io/BlockSci/setup.html#incremental-updates) to automatically keep it up to date.

**Comment by kepler16bv** [comment]
ok great. And in that case, the command to use to continue the parse is exactly the same? I'm thinking something along these lines:

```blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin```

**Comment by maltemoeser** [comment]
Yes that should work
