### ISSUE TITLE
how to plot the number of blocks created by the largest miners

### ISSUE THREAD

**Issue by Dimasty** [citp/BlockSci#250]
BlockSci version: 0.5.0
Hello!
I am working on one article, and I need a plot that lets me know how many blocks the largest miners have created depending on the time.
I have read the documentation for your impressive solution, but I am stuck with this issue and have not found suitable examples.
Maybe someone has already done something like this or something to advise?

**Comment by maltemoeser** [comment]
```
ds = pd.Series([block.miner() for block in chain.range("September 2017")])
ds.groupby(ds).count()
```

Will give you a list of miners and the respective number of blocks they found in September 2017.

```
AntPool            767
BATPOOL             41
BTC.TOP            651
BTC.com            562
...
```

Is this what you're looking for?

**Comment by Dimasty** [comment]
Hello!
Yes, this what i need, thank you
But now i have trouble when running your solution, like


UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 3291: ordinal not in range(128)

does it my fault?
