### ISSUE TITLE
blocksci.OutputIterator.spending_tx return blocksci.TxIterator rather than blocksci.TxOptionalIterator

### ISSUE THREAD

**Issue by simonohanlon101** [citp/BlockSci#257]
_Please provide a clear and concise description of what the problem is._
The `spending_tx` attribute of the `blocksci.OutputIterator` class returns a `blocksci.TxIterator` rather than a `blocksci.TxOptionalIterator`. A number of attributes are only available to the latter class (e.g. `has_value`).

#### Expected Result
```python
import blocksci
chain = blocksci.Blockchain("/data/blocksci/blocksci.config")
chain[1].outputs.spending_tx
#<blocksci.TxOptionalIterator at 0x7f19c504c048>
```

#### Actual Result
```python
import blocksci
chain = blocksci.Blockchain("/data/blocksci/blocksci.config")
chain[1].outputs.spending_tx
#<blocksci.TxIterator at 0x7f19c504c048>
```

#### Reproduction Steps
```
import blocksci
chain = blocksci.Blockchain("/data/blocksci/blocksci.config")
chain[1].outputs.spending_tx
```

#### System Information
BlockSci version: 0.6 (commit ID: `8631d67f7bd71e766e3e8d8663188f27b26beff3`)
Using AMI: no
Total memory: 61GB
EC2 instance type: `i3.2xlarge`

**Comment by maltemoeser** [comment]
A `blocksci.TxOptionalIterator` does not exist in the Python interface. IIRC, not having `Optional[Iterator|Range|Sequence]` was a conscious decision by @hkalodner to limit the already significant complexity (and build time) of the proxy interface.

**Comment by simonohanlon101** [comment]
Oh. I was trying to get this gist by @hkalodner to work, and if I understand correctly, in this gist, exactly this interface is used:

https://gist.github.com/hkalodner/b389a5009969de6b6141031829c9640b

On line 45. Unless I'm mistaken? Thanks for the fast response to raising an issue.

**Comment by maltemoeser** [comment]
Ah, that gist uses the old v0.5 interface. The Python interface has undergone a lot of change since then (in v0.6). The API change is simple to fix, however the gist seems to be running a lot slower than the 3min @hkalodner reported back then. Not sure if that's simply due to the increase in the size of the blockchain or some other change in BlockSci.

```
never_spent = np.sum(block.outputs.where(lambda o: ~o.is_spent).value)
output_values = block.outputs.where(lambda o: o.is_spent).value
output_heights = block.outputs.spending_tx.block.height
output_ages = block.outputs.spending_input.age
```

**Comment by simonohanlon101** [comment]
Wow, thank you so much for looking into this for me and recommending a solution. 

I'll give this a whirl and report how long this takes using the updated API.

Thanks.

**Comment by maltemoeser** [comment]
It took 27min to run on our EC2 instance
