### ISSUE TITLE
Temporal Clustering 

### ISSUE THREAD

**Issue by dsrincon** [citp/BlockSci#263]
#### System Information (if applicable)
BlockSci version:  0.5.0
Using AMI: yes
Total memory: 64 Mb

Hi, 

Great project! Thanks for putting this out there. 
I'm a researcher at Blockchain @ Berkeley and I want to perform clustering at different block heights. Is there a way to slice the blockchain object before feeding it into the cluster manager? 

Txs

**Comment by maltemoeser** [comment]
It's not possible in v0.5, but will be in the next version (see https://github.com/citp/BlockSci/issues/118). If you want to play around with the development version, it's available on the `v0.6` branch.
