### ISSUE TITLE
import/install blockscipy from requirements.txt

### ISSUE THREAD

**Issue by p1nox** [citp/BlockSci#270]
First of all, congrats! This tool it's awesome 🚀 🎉 💯 

I'd like to install `blockscipy` as a regular package included as a dependency in `requirements.txt` file, in order to have an easy to setup environment in python.

The easiest way I could was to do (having a brand new ubuntu instance):

```
# install python3 and virtualenv
apt-get update
apt-get install python3
apt-get install python-pip
sudo dpkg-reconfigure locales
sudo apt-get install python3-dev
sudo apt-get install python-dev
pip install virtualenv

# create and activate a virtual environment
virtualenv venv
virtualenv -p python3 venv
. venv/bin/activate

# install blockscipy from a local folder
pip install -e /home/ubuntu/BlockSci/blockscipy
# and requests package, because for some reason is missing...
pip install requests
```
At this point everything needed is installed in current venv to use blockscipy, so if I execute a script including `import blocksci` is working as expected.

And in order to automate this, I could freeze python packages list:
```
pip install -r requirements.txt

# which produce this content for requirements.txt file
-e git+https://github.com/citp/BlockSci.git@8213137f0360d4089d177e39e0467d28efa5b1db#egg=blocksci&subdirectory=blockscipy
certifi==2019.3.9
chardet==3.0.4
dateparser==0.7.1
dill==0.2.9
idna==2.8
multiprocess==0.70.7
numpy==1.16.3
pandas==0.24.2
psutil==5.6.2
pycrypto==2.6.1
python-dateutil==2.8.0
pytz==2019.1
regex==2019.4.14
requests==2.21.0
six==1.12.0
tzlocal==1.5.1
urllib3==1.24.3
```

And then, if I deactivate current environment, delete venv folder, create a new venv, and the install everything pointing to the new `requirements.txt` file, I get this error:

```
> pip install -r requirements.txt
Obtaining blocksci from git+https://github.com/citp/BlockSci.git@8213137f0360d4089d177e39e0467d28efa5b1db#egg=blocksci&subdirectory=blockscipy (from -r requirements.txt (line 1))
  Cloning https://github.com/citp/BlockSci.git (to revision 8213137f0360d4089d177e39e0467d28efa5b1db) to ./venv/src/blocksci
  Running command git clone -q https://github.com/citp/BlockSci.git /home/ubuntu/venv/src/blocksci
  Running command git checkout -q 8213137f0360d4089d177e39e0467d28efa5b1db
  Running command git submodule update --init --recursive -q
  fatal: reference is not a tree: 7b02cd2ea201021f82f2c4bcfe2106f9c3c92bb0
  Unable to checkout '7b02cd2ea201021f82f2c4bcfe2106f9c3c92bb0' in submodule path 'external/range-v3'
ERROR: Command "git submodule update --init --recursive -q" failed with error code 1 in /home/ubuntu/venv/src/blocksci
```

Is there a plan to include `blockscipy` in https://pypi.org/? Is there a different way to install this package from its local folder pointing it from `requirements.txt` file (I was looking that online, but found only pointing to git repository, and as `setup.py` is not in the root dir it doesn't work)? What would you recommend, to use docker?

**Comment by maltemoeser** [comment]
This particular error should go away if you check out the v0.5.1 tag (https://github.com/citp/BlockSci/tree/v0.5.1) or the development version v0.6 (#199, #183)

**Comment by p1nox** [comment]
Awesome! Thanks, this fixed the problem 👍 

Just to document the change, I just changed the commit to be the target tag in `requirements.txt`:

```
-e git+https://github.com/citp/BlockSci.git@v0.5.1#egg=blocksci&subdirectory=blockscipy
certifi==2019.3.9
chardet==3.0.4
dateparser==0.7.1
dill==0.2.9
idna==2.8
multiprocess==0.70.7
numpy==1.16.3
pandas==0.24.2
psutil==5.6.2
pycrypto==2.6.1
python-dateutil==2.8.0
pytz==2019.1
regex==2019.4.14
requests==2.21.0
six==1.12.0
tzlocal==1.5.1
urllib3==1.24.3
```

**Comment by maltemoeser** [comment]
Glad it's working now. Closing this for now, feel free to reopen or open a new issue if you run into any other trouble
