### ISSUE TITLE
Stuck while iterating clusters

### ISSUE THREAD

**Issue by p1nox** [citp/BlockSci#271]
#### System Information
BlockSci version: https://github.com/citp/BlockSci/tree/v0.5.1
Total memory: 60Gb RAM

Trying to loop over all clusters, and cause script to get stuck on an specific cluster, `31`. If I execute this snippet:

```
import blocksci
import csv
chain = blocksci.Blockchain(BITCOIN_FOLDER)
cm = blocksci.cluster.ClusterManager("%s/clusters" % BITCOIN_FOLDER, chain)

for c in cm.clusters():
    print(c.index)
    print(c.size())
```

It produces this output (shortened):

```
0
1
1
1
.
.
.
30
1
31
1
32
```

I returns and prints `c.index`, but it stops while trying to execute `c.size()`, specifically for this cluster with index 32. If I skip this cluster, the script continues as expected.

Is there a different way to loop over all clusters, and all its addresses?

**Comment by maltemoeser** [comment]
Most likely an instance of [Why is cluster.size() slow?](https://github.com/citp/BlockSci/wiki#why-is-clustersize-slow) (also see [Why do some clusters appear to be empty?](https://github.com/citp/BlockSci/wiki#why-do-some-clusters-appear-to-be-empty) for some more information of how clustering works under the hood)

The TLDR: .size() and .balance() require database lookups, which can be quite slow for large clusters

**Comment by p1nox** [comment]
Nice, thanks! I didn't realise there was a FAQ section, always looking docs at https://citp.github.io/BlockSci/index.html 👍
