### ISSUE TITLE
change_output error

### ISSUE THREAD

**Issue by faridasabry** [citp/BlockSci#274]
Testing with the blocksci python library v0.5.0 on the fully parsed bitcoin chain
```
tx= chain.tx_with_hash("f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16")
print(tx.change_output)
```
#### Expected Result 
I expected the output to be the same as the input address  to the transaction 
`TxIn(spent_tx_index=9, address=PubkeyAddress(12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S), value=5000000000)`
so the change output should be:
`TxOut(spending_tx_index=183, address=PubkeyAddress(12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S), value=4000000000)
`
#### Actual Result
But the output was:
`TxOut(spending_tx_index=156741, address=PubkeyAddress(1Q2TWHE3GMdB6BZKafqwxXtWAWgFt5Jvm3), value=1000000000)`

**Comment by maltemoeser** [comment]
BlockSci comes with a variety of [different heuristics](https://citp.github.io/BlockSci/reference/heuristics/change.html#change-address-heuristics). The [default (legacy) heuristic](https://citp.github.io/BlockSci/reference/heuristics/change.html#blocksci.heuristics.change.legacy) in v0.5 does not check for address reuse, instead it aims to replicate the client behavior heuristic from the "A fistful of bitcoins" paper combined with the optimal change heuristic. If you want to check for address reuse, you can use the [corresponding heuristic](https://citp.github.io/BlockSci/reference/heuristics/change.html#blocksci.heuristics.change.address_reuse) or even combine it with other heuristics
