### ISSUE TITLE
Alternative way to get clusters

### ISSUE THREAD

**Issue by p1nox** [citp/BlockSci#275]
BlockSci version: 0.5.1

In order to export all tuples `(address_string, cluster_index)`, one could loop into all clusters and all its addresses using python, but that will take some time.

Another approach would be to load binary files where clusters data is persisted, which I guess is `bitcoin/clusters/clusterAddresses.dat`. But I tried to use `numpy`, or regular `open()`, and trying to find the right encoding for the dataset present in binary file, but no luck.

I also thought that maybe this file is written using rocksdb, but I see no rocksdb usage where this file is written [here](https://github.com/citp/BlockSci/blob/master/src/cluster/cluster_manager.cpp#L265), and I tried to load that file as a db file in rocksdb, but didn't work.

I tried to open the file in cpp as well, but I'm missing also the size the buffer should have (`static_cast<long>(sizeof(DedupAddress) * orderedScripts.size())` ?), because if I do something like:

```
#include <iostream>
#include <fstream>
#include <iterator>
#include <vector>
using namespace std;

int main() {
   ifstream infile;
   infile.open("bitcoin/clusters/clusterAddresses.dat", ios::binary|ios::in);

   char buffer[32];
   while(infile.read((char *)&buffer, sizeof(buffer))) {
      cout << (char *)&buffer << endl;
   }

   infile.close();
   return 0;
}
```
The program prints only symbols, not readable data.

Is there a way to load the entire clusters/addresses information and dump it into one/multiple csv file? Probably related to https://github.com/citp/BlockSci/issues/200 ?

**Comment by maltemoeser** [comment]
The clustering is based on [equiv addresses](https://citp.github.io/BlockSci/reference/addresses/equiv_address.html), reading the binary files directly won't give you the address strings. Iterating over the cluster addresses in C++ is probably the fastest way to extract those
