### ISSUE TITLE
multisig address information inconsistent

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#276]
I think that BlockSCI v5.0 does not link every transaction in the case that the address is "multisig address".

#### Expected Result
The total number of transactions is 62.
https://www.blockchain.com/ko/btc/address/354bfNuNJKZwAH3FvcME1C2bXRhzYacbm6

#### Actual Result
txes :2
901266c8ea86559cb7f34749d5434d01766f1dfe99d361af47f5a538379e5f86
bf7dec5cb2c006010ed45da6ac5c68a3aa897c28b062eebacd2f48435c92adce

#### Reproduction Steps
```
import blocksci
chain = blocksci.Blockchain("blocksci_path")
addr = chain.address_from_string("354bfNuNJKZwAH3FvcME1C2bXRhzYacbm6")
print("txes :{}".format(len(addr.txes())))
for tx in addr.txes():
    print(tx.hash)

```
#### System Information
BlockSci version: (please provide a commit id if you're on a development branch) v5.1.0
Using AMI: no
Total memory: XX GB

**Comment by maltemoeser** [comment]
Thanks for the report, this looks similar to #272

**Comment by gateman1218** [comment]
Thanks for quick responses. According to your comments, this bug will be reproduced in v5.0.
How about the master branch? Because of this, I'm working on building v6.0.

**Comment by maltemoeser** [comment]
The master branch contains v0.5
