### ISSUE TITLE
Is master branch working well?

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#277]
I've downloaded the master branch of BlockSCI from the scratch yesterday and built the whole system by following the instruction. I successfully built every system component (blocksci_parser, etc) and parsed the blockchain by "blocksci_parser".
However, there is only a part of transactions, not every transaction when I queried "transactions linked to the input address". 
When I tested the same code on my PC which has an old version of BlockSCI (v5.1.0), I could get the results (complete set of transactions).

I think that the current version of the master branch seems to have critical bugs. Is there anyone who try to build the latest BlockSCI from the scratch and can share experiences?

#### System Information (if applicable)
BlockSci version: master
Using AMI: no
Total memory:64G

**Comment by Arryboom** [comment]
did you reindex the bitcoin-wallet database?

**Comment by maltemoeser** [comment]
Could you provide a working example of the code that produced inconsistent results? Did you try reparsing the chain? The master branch generally has been very stable. There are a couple of bugs that have been fixed in our development version v0.6

**Comment by gateman1218** [comment]
Sure. I've reparsed several times. I'm working on v6.0.
I will share my experience about that.
