### ISSUE TITLE
Re-install BlockSci & development environment

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#278]
According to the maintainers, v0.6 branch is not stable. If I want to pull the latest version of "v0.6 branch" and deploy the latest version in the system which has already old v0.6 branch, should I need to remove all files related to old v0.6 Blocksci? Or, I just simply do "git pull v0.6 branch" and follow the blocksci compiling instruction as if I deploy blocksci at first?

Shortly, I want to upgrade my system with "the latest version of v0.6". How can I do that?

The second question is the development environment. I want to fix or add features on blocksci. Are there any references for setting up development environment like "hello world example"? Compiling whole system takes a long time. Are there any recommendations to "partially" build what I modified or implemented?

Thanks.

#### System Information (if applicable)
BlockSci version: v0.6
Using AMI: no
Total memory: 64

**Comment by maltemoeser** [comment]
If you're already on the v0.6 branch and want to integrate the latest upstream changes, it should be as easy as
```bash
git pull
cd release
make
sudo make install
cd ..
pip3 install -e blockscipy
# on ubuntu instead: CC=gcc-7 CXX=g++-7 sudo -H pip3 install -e blockscipy
```

`make` will automatically detect which files have changed and only recompile the necessary parts

**Comment by gateman1218** [comment]
Thank you for your kind instruction!
