### ISSUE TITLE
How to use group_by in v0.6?

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#284]
#### System Information (if applicable)

Using AMI: no  
BlockSci version: v0.6
Blockchain: Bitcoin
Parser: Disk
Total memory: 64 GB  

I'd like to use "group_by" feature to merge input/output values per each address. Pseudocode is in the below.
The code without group_by is pretty slow. It consumes several seconds to handle one Bitcoin block.

#### Code
for tx_in in inputs:
     value_dic['tx_in.address'] = tx_in.value #if exists, adding new value to old value.

**Comment by maltemoeser** [comment]
Hey, yeah that's a perfect use case for `group_by`:

```python
chain.blocks[-1].inputs.group_by(lambda i1: i1.address, lambda i2: i2.value.sum)
```
