### ISSUE TITLE
Implementation questions 

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#285]
#### System Information (if applicable)

Using AMI: no  
BlockSci version: v0.6(please provide a commit id if you're on a development branch)  
Blockchain: Bitcoin  
Parser: Disk  
Total memory: 64 GB  

- How to loop iterator class in reverse order? I'd like to traverse "outputs, inputs, txes" from the latest one.
    I tried to the below code, but the system told me "object is not reversible".
`for o in reversed(blocksci_addr.outs):`

 - Is it possible to improve this code by using group_by()?
```
    for tx in blocksci_addr.out_txes:
        input_sum = input_sum + tx.input_count
        output_sum = output_sum + tx.output_count
```

**Comment by gateman1218** [comment]
Self answer for the first question.
`reversed(blocksci_addr.outs.to_list())`

**Comment by maltemoeser** [comment]
For the second one, with the `TxIterator` returned by `.out_txes` you can do:
```python
blocksci_address.out_txes.input_count.sum()
blocksci_address.out_txes.output_count.sum()
```
(`a.out_txes.input_count` returns a numpy array)

**Comment by gateman1218** [comment]
Thanks!
