### ISSUE TITLE
Traverse all transactions has bug on both v0.5 and v0.6

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#286]
#### System Information (if applicable)

Using AMI: no  
BlockSci version: v0.5, v0.6
Blockchain: Bitcoin
Parser: Disk 
Total memory: 64 GB  

I'd like to traverse all addresses to analyze each address.
Here is the code.

```
#Analyze all addresses
    addresses = chain.addresses(blocksci.address_type.pubkey)
    for idx in range(599457000): #if fails, I want to start from the failed addr index.
        addr = addresses[idx]
        addr_analyzer(addr)
```
When I just call `addr_analyzer()` function once, the results are exactly what I expected.
However, while running the code with 
I ran `#Analyze all addresses code`, the result is different with the first one.

Is it a bug on BlockSci or I missed something to analyze all addresses in a batch manner?

**Comment by maltemoeser** [comment]
Can you give me a code example that reproduces the difference in the result you're describing?

**Comment by gateman1218** [comment]
It was my mistake. The problem has been resolved.
