### ISSUE TITLE
How to do a multiprocess task on Blockrange?

### ISSUE THREAD

**Issue by faridasabry** [citp/BlockSci#287]
I am trying to do a multiprocessing task on a range of blocks, mapping block ranges to processes' pool, but I am receiving the following error:
`TypeError: can't pickle blocksci.BlockRange objects `at the map call.
I tried to pass the "blocksrange.all" instead but I received the error:
`TypeError: can't pickle blocksci.Tx objects`

System info:

Using AMI: no  
BlockSci version: 0.6.0
Blockchain: (Bitcoin)  
Parser: Disk
Total memory: 128 GB  

`def multiprocessing(func, args, workers):  
    with ProcessPoolExecutor(workers) as ex:
        res = ex.map(func, args)
    return list(res)
candidate_trans = multiprocessing(findCandidateTransactions, tasks, 8)
`

where task is a list of tuples filled up : 
`tasks.append( (blocks[start:end],btc_amount) )`
and 
`findCandidateTransactions` 
is the function that looks up transactions in the assigned block range.

**Comment by maltemoeser** [comment]
We provide a couple of `mapreduce_*` functions in the Python module that should achieve exactly this, take a look at the [`__init__.py`](https://github.com/citp/BlockSci/blob/master/blockscipy/blocksci/__init__.py) file.

**Comment by faridasabry** [comment]
Thanks a lot for your reply. I did some workaround for now but will try BlockSci mapreduce functions.
