### ISSUE TITLE
Need to get raw c++ object from pybind11

### ISSUE THREAD

**Issue by joequant** [citp/BlockSci#288]
#### System Information (if applicable)

Using AMI: yes/no  
No
BlockSci version: (please provide a commit id if you're on a development branch)  
0.6.0 dev
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Bitcoin
Parser: Disk/RPC Disk 
Total memory: 64 GB  

I would like to pass in a python block object and then get access to the c++ object to do some
processing in C++.

I can use getattr to run the code with pybind calls, but I'd like to find something more effecient

py::list process_block(py::object obj) {
  py::list l;
  l.append(obj.attr("height"));
  return l;
}

What I'd like to do is to cast obj to a Block, and then return Block.height

**Comment by maltemoeser** [comment]
Pybind11 should allow to [cast in both directions](https://pybind11.readthedocs.io/en/master/advanced/pycpp/object.html#casting-back-and-forth), though I haven't tried this myself. Questions specific to pybind11 might be better placed in their issue tracker.
