### ISSUE TITLE
Parser crashes at block 572070 with NextQueueFinishedEarlyException

### ISSUE THREAD

**Issue by icedebis** [citp/BlockSci#290]
Hello, 

I am unable to complete parcing of the Bitcoin blockchain using the disk mode.  The problem seems to be the block 572070. I tried both Ubuntu 16.04 and 18.04 several times. Setting parcing to process blocks up to 572070 works.

Here is the message I receive:

```
94.19% done, Block 572070/582427terminate called after throwing an instance of 'NextQueueFinishedEarlyException'
  what():  Next queue finished early
Aborted (core dumped)
```

#### System Information

Using AMI: local installation; 
BlockSci version: I presume 0.5 or 0.5.1 whatever the version is installed if one follows blocksci instructions for Ubuntu
Blockchain:  Bitcoin
Parser: Disk 
Total memory: 256 GB

**Comment by maltemoeser** [comment]
We've had a few similar issues like this before, if I remember correctly some were able to work around this by first parsing up to the block before, and then parsing the remainder of the blockchain. I think we fixed this issue on our [v0.6 development branch](https://github.com/citp/BlockSci/tree/v0.6), that branch should be stable enough to try out if you're inclined to play with a development version (it comes with a lot of other changes and improvements).

**Comment by icedebis** [comment]
Dear Malte,

Thank you very much for getting back. I have tried parsing up to the blcok before, and then parsing the rest. However, I got a similar error message at block 272072. I have compiled v0.6 but it seems that the syntax for running the parser has changed. Can you please provide an example of the parsing command? Also, is there any doc that describes what's new in v0.6?

Many thanks,
Igor

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by maltemoeser** [comment]
In v0.6 you first need to create a config file. The general syntax is:

```
blocksci_parser <config file> generate-config <coin type> <data directory> [--max-block <max block>] [--disk <coin directory>] [--rpc <username> <password> [--address <address>] [--port <port>]]
```

You can run `blocksci_parser help` to get more information about the available options.

Then, you can update the chain by running `blocksci_parser <config file> update`.

A WIP changelog is available [here](https://github.com/citp/BlockSci/blob/v0.6/CHANGELOG.rst). Let me know if you need help with any of these steps

**Comment by icedebis** [comment]
Thanks. The new version processed all the blocks. However, when compiling the python module I ran into the following problem:     
/.../BlockSci/blockscipy/src/generic_proxy.hpp:15:15: fatal error: any: No such file or directory
compilation terminated.
 CMakeFiles/_blocksci.dir/build.make:75: recipe for target 'CMakeFiles/_blocksci.dir/src/proxy/proxy_flow_functions_other.cpp.o' failed

I use cmake 3.14 and python 3.6.9.

**Comment by maltemoeser** [comment]
Sounds like your C++ version could be outdated if it doesn't find `<any>`, did you run `CC=gcc-7 CXX=g++-7 sudo -H pip3 install -e blockscipy` to install the Python interface?

**Comment by icedebis** [comment]
yes, this is exactly what I ran. But you are right -- the problem was with the C++. I had to point gcc and g++ to newer versions, then it worked. Thanks!

**Comment by maltemoeser** [comment]
Awesome :)

**Comment by icedebis** [comment]
There seems to be a problem with how the new version processes transactions. For example, running the following:

pd.DataFrame([(x.block.height, x.value)  for x in chain.address_from_string('1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB').outs], columns=['blk_height','v_in']).sort_values(by=['blk_height'])

gives only 51 blocks. Perhaps the syntax has changed? In the previous version, it worked fine.

**Comment by maltemoeser** [comment]
I get more than 51 blocks `11225 rows × 2 columns`. Is your chain up-to-date?

**Comment by icedebis** [comment]
The latest block is 584551.

**Comment by icedebis** [comment]
If it helps I can run some code or can try to reparse the blockchain

**Comment by icedebis** [comment]
I have rerun the parser but still get very few blocks.
len([(x.block.height, x.value)  for x in chain.address_from_string('1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB').outs])

113

Here is how the parser finished:

99.98% done, Block 584521/584552
Back linking transactions
99.88% done
Updating hash index
Updating index with 433035006 txes
100.00% done
Updating address index
Updating index with 433035006 txes
100.00% done
Updating index with scripts of type multisig_script
99.99% done
Unlocking data directory.

**Comment by maltemoeser** [comment]
That parser output looks good. Could you list the block heights you're getting?

**Comment by icedebis** [comment]
Here are the first five:

blk_height | v_in

478278 | 10000
478480 | 1368436013
478516 | 1332028453
480672 | 1540675303
480691 | 1518592837


and the last five:

  | blk_height | v_in

490364 | 1479483240
490375 | 1345648226
490444 | 1404258865
490475 | 1288884679
490500 | 1376639459

**Comment by icedebis** [comment]
running

blocks = chain.blocks
height = blocks.height

I get all the blocks (1-584551)

**Comment by maltemoeser** [comment]
Could you post the output of the following snippets:

```python
tx1 = chain.tx_with_hash("d8e4c92e9670ec0ea19c7f08e5339907045e7954d6cd7c4c542ea925f125a3b9")
print(tx1.outs[0])
print(tx1.outs[0].address)
print(tx1.outs[0].address.address_num, tx1.outs[0].address.type)
print(tx1.outs[0].address.equiv())
```

```python
tx2 = chain.tx_with_hash("f3c19dc594c4840468cc5489daa311f2f366106206adca0e3cbbadef73bc69a7")
print(tx2.outs[0])
print(tx2.outs[0].address)
print(tx2.outs[0].address.address_num, tx2.outs[0].address.type)
print(tx2.outs[0].address.equiv())
```

**Comment by icedebis** [comment]
Sure. Here is the first output:

TxOut(spending_tx_index=264080635, address=PubkeyHashAddress(1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB), value=1419903580)
PubkeyHashAddress(1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB)
331058447 Pay to pubkey hash
EquivAddress(PubkeyHashAddress(1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB))

and here is the second:

TxOut(spending_tx_index=265687110, address=PubkeyHashAddress(1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB), value=1376639459)
PubkeyHashAddress(1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB)
331058447 Pay to pubkey hash
EquivAddress(PubkeyHashAddress(1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB))

**Comment by maltemoeser** [comment]
Thanks! Seems like the outputs are connected to the correct address, but the reverse lookup doesn't work. I'll try look into this further soon

**Comment by icedebis** [comment]
If it helps I believe this problem is present even in the 5.0 version. Somehow the reverse lookup breaks if I process blocks, say up to the height 570,000 but works fine if Iprocess blocks up to the height 560000 or so

**Comment by maltemoeser** [comment]
I wonder if it might be an OS issue rather than a BlockSci issue. What is the open file limit on your system (`ulimit -n`)?

**Comment by icedebis** [comment]
I set it to 64000

**Comment by icedebis** [comment]
You were again spot on! I rerun the parser with ulimit set to 64000, and now everything is fine. Thanks!

Regarding clustering: is the default option now to cluster addresses that appear on the right hand side of transactions?

**Comment by maltemoeser** [comment]
Oh awesome! I should change the setup instructions then to highlight that.

The clusterer, by default now, only clusters input addresses (left hand side), but you can specify one of the change address heuristics to cluster change addresses (on the right hand side)
