### ISSUE TITLE
Need easy way of getting cluster from cluster_num

### ISSUE THREAD

**Issue by joequant** [citp/BlockSci#294]
Please provide a clear and concise description of the problem.

I'm doing some computations involving clusters and I need a way of getting cluster information via the cluster id.  It seems like a easy addition to cluster manager to add in cluster from id

I can add the code myself it turns out that there isn't any gotchas or if the lack of an API is intentional

#### Reproduction Steps

```
import blocksci
a = cluster.cluster_num
store a in database

Need some way of going from cluster id back to cluster.
```

#### System Information

Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch) 0.6  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  bitcoin
Parser: Disk/RPC  disk
Total memory: 64 GB

**Comment by maltemoeser** [comment]
This should be straightforward to add.

The only reason I can see this does not exist is that it could give the impression that clusters can be consistently identified by their ID, however the `cluster_num` for a cluster containing a specific address can/will be different for different clusterings

**Comment by maltemoeser** [comment]
Actually, `ClusterManager.clusters()` returns a range, so you can just do
`cm.clusters()[your_cluster_num]` to get the cluster with `your_cluster_num`
