### ISSUE TITLE
Very slow performance of v0.6

### ISSUE THREAD

**Issue by icedebis** [citp/BlockSci#295]
The new development branch (v0.6) runs much slower than 0.5 (order of magnitude about 50 - 100 times)

#### Reproduction Steps
Almost any function, e.g. see below, the function that computes flows from set of clusters.

```python
def super_cluster_flows(cluster_set):
    ins = []
    outs = []
    for cluster in cluster_set:
        ins_df = pd.DataFrame([(x.block.height, x.value, x.tx.index) 
                                 for x in cluster.outs()], columns=['blk_height', 'v_in', 'tx'])
        ins_df['cluster_id'] = cluster.index
        ins.append(ins_df)
        outs_df = pd.DataFrame([(x.spending_tx.block.height, x.value, x.spending_tx.index)  
                                  for x in cluster.outs() if x.spending_tx is not None],
                                 columns=['blk_height', 'v_out', 'tx'])
        outs_df['cluster_id'] = cluster.index
        outs.append(outs_df)
    
    ins = pd.concat(ins, ignore_index=True)
    outs = pd.concat(outs, ignore_index=True)
   
    return (ins, outs)

```

#### System Information

Using AMI: no  
BlockSci version: development branch
Blockchain:  Bitcoin
Parser: Disk
Total memory: 256 GB

**Comment by maltemoeser** [comment]
Hmm that would surprise me since, in general, v0.6 should be faster than v0.5.

If you can give me a specific reproducible example, I'd be happy to take a look at possible causes

**Comment by icedebis** [comment]
I am suprised as well. I tried several installs on different systems (Ubuntu 1604, 1904). You can run the above function  for some large clusters, e.g., the one that contains the following address 1LAnF8h3qMGx3TSwNUHVneBZUEpwE4gu3D. I use clustring where addresses on the lhs of transactions are clustered together (default in v0.6).

**Comment by maltemoeser** [comment]
With the changes made in v0.6 for the proxy interface, object creation in Python has become more expensive compared to v0.5. Rather than instantiating individual objects in Python, I'd recommend retrieving the vectors of corresponding properties:

```python
def super_cluster_flows(cluster_set):
    ins = []
    outs = []
    for cluster in cluster_set:
        co = cluster.outs()
        ins_df = pd.DataFrame({
            'blk_height': cluster.outs().block.height,
            'v_in': cluster.outs().value,
            'tx': cluster.outs().tx_index
        })
        ins_df['cluster_id'] = cluster.index
        ins.append(ins_df)
    
        outs_df = pd.DataFrame({
            'blk_height': cluster.outs().where(lambda o: o.is_spent).spending_tx.block.height,
            'v_out': cluster.outs().where(lambda o: o.is_spent).value,
            'tx': cluster.outs().where(lambda o: o.is_spent).spending_tx.index
        })
        outs_df['cluster_id'] = cluster.index
        outs.append(outs_df)
    
    ins = pd.concat(ins, ignore_index=True)
    outs = pd.concat(outs, ignore_index=True)
   
    return (ins, outs)
```

I'll keep this issue open to do some more measurements and performance comparisons between the two versions

**Comment by icedebis** [comment]
Thanks. It helps in this particular case but not everything can be vectorized. A program that ran for 1-2 hours  in v0.5 now runs 4 days in v0.6.

**Comment by maltemoeser** [comment]
I see, I'll make sure to check if there's a way to make this faster again
