### ISSUE TITLE
Issue with parsing 

### ISSUE THREAD

**Issue by ClementPavue** [citp/BlockSci#297]
Please provide a clear and concise description of the problem.
Hello, I encountered an issue with parser recently. Most recent addresses are missing transactions. 

#### Reproduction Steps
Tried reparsing didn's work, also trying re-syncing a bitcoind and then reparsing, problem remains. 

I recently updated my bitcoind 0.17. I don't know if this can be the source of the issue.

#### System Information

Using AMI: no  
BlockSci version: v0.6 
Blockchain: BTC
Parser: Disk
Total memory: 64 GB

**Comment by maltemoeser** [comment]
Can you give me an example for such an address? Do you have a sufficiently high limit for the number of open files (https://github.com/citp/BlockSci/issues/290#issuecomment-510275012)?

**Comment by ClementPavue** [comment]
For instance I only have 82 txs for this address: 3EENzQdQS3BvvnkeJjC5uVwUKFuTczpnok instead of 39400 currently. Will try to rerun with a bigger number of open file. 

If it's due to open file parser doesn't output anything thought. What can cause such a problem without a crash ?

**Comment by maltemoeser** [comment]
Yeah in the other thread it also seemed like it fails silently in that case. The database that stores all the address information needs to open a large number of files and apparently fails silently. I haven't looked into whether we can make it output an error in that case, which would definitely be helpful.

Curiously, one of my instances recently crashed, the other didn't (and lists correct no of txs), so I'm looking forward to seeing if this was just the open files limit or if there's another issue

**Comment by ClementPavue** [comment]
Add a few random crash as well once in a while, can't say if it's related to open files thought. 

Anyway I'll let you know about my issue and try to solve the issue by myself and send it to you; 

My guess is, the faulty code is in `backUpdateTxes` function right ?

**Comment by maltemoeser** [comment]
My crash related to running out of memory, so looking forward to seeing if reparsing in your case works with a higher limit for open files. `backUpdateTxes`, IIRC, is only responsible for updating spent outputs with the `txnum` of the transaction spending it.

**Comment by ClementPavue** [comment]
Parser is fine with an higher number of open file. Thanks for your help !

**Comment by maltemoeser** [comment]
Perfect, and sorry about that, should have made it clearer in the documentation (just recently added a note on the limit)
