### ISSUE TITLE
Transactions do not match online databases

### ISSUE THREAD

**Issue by jiagengliu** [citp/BlockSci#306]
#### Reproduction Steps

The transactions found in BlockSci do not match the results from bitinfochart and BTC.com. The issue is different from #244 as I cannot find these addresses from the transactions, either. 

```
special_addr = "34HkfmwW9XdnASYBmnAEmz7XVRW37sffxK"
another_special_addr = "34K9f4EZQsmLB2wptj4Pm8qXUbYHhyT853"
normal_addr = "34KCeUB5axK7BpcAtAzxBk3mtZjqnAMCGK"
block_num = 513566

print(chain.address_from_string(special_addr).in_txes())  # empty
print(chain.address_from_string(special_addr).out_txes())  # only one, which can be found on bitinfochart
print(chain.address_from_string(special_addr) 
      in [out.address for out in list(chain.blocks[block_num].outputs)]) # False
print(chain.address_from_string(normal_addr) 
      in [out.address for out in list(chain.blocks[block_num].outputs)])  # True
```

I wonder if it is my own parser's problem. Thank you!

#### System Information

Using AMI: Yes 
BlockSci version: 0.5
Blockchain: Bitcoin
Parser: Disk/RPC  
Total memory: 61 GB

**Comment by maltemoeser** [comment]
Does this only occur with P2SH addresses? It might be an issue with address_from_string not recognizing P2SH (#217)

**Comment by jiagengliu** [comment]
Indeed. Thanks for the explanation.

**Comment by jiagengliu** [comment]
Here is a P2PKH address that does not work in v0.5

```
addr = chain.address_from_string('1KaoETsiqovEXDdp2EpgTaywCwpQ4S7CQ4')  # a PubkeyHashAddress
print(addr.in_txes())  # only one tx shows up
```

**Comment by maltemoeser** [comment]
Looks like this is similar to #272

**Comment by jiagengliu** [comment]
Thanks again!
