### ISSUE TITLE
dumping cluster cases segfault

### ISSUE THREAD

**Issue by joequant** [citp/BlockSci#308]
Please provide a clear and concise description of the problem.

Dumping out a clluster cases a segfault

#### Reproduction Steps

```
import blocksci
chain = blocksci.Blockchain('/srv/config/blocksci_config')
cm = blocksci.cluster.ClusterManager('/srv/data/clusters', chain)
#cm = blocksci.cluster.ClusterManager.create_clustering("/srv/data/clusters", ch
ain)
#for i in ['34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo', '3E35SFZkfLMGo4qX5aVs1bBDSnAuGg
BH33',
#         '3M219KR5vEneNb47ewrPfWyb5jQ2DjxRP6', '1NDyJtNTjmwk5xPNhjgAMu4HDHigtob
u1s'
#         ]:

#i = '34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo'
i = '3M219KR5vEneNb47ewrPfWyb5jQ2DjxRP6'
a = chain.address_from_string(i)
c = cm.cluster_with_address(a)
print(c, c.address_count())
for a in c.addresses:
    print(a)
```

#### System Information

Using AMI: yes/no  
BlockSci version: dev 20190801
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  bitcoin
Parser: Disk/RPC disk  
Total memory: 64 GB

**Comment by maltemoeser** [comment]
Yeah iterating over `cluster.addresses` is currently broken, you can use the `.to_list()` workaround, see #273
