### ISSUE TITLE
Serialization of addresses causes SEGFAULT

### ISSUE THREAD

**Issue by jiagengliu** [citp/BlockSci#309]
Please provide a clear and concise description of the problem.

Since `address_to_string` does not work with P2SH addresses in v0.5 yet (#306), I tried to serialize address objects but loading it causes a Segmentation fault. Is there a better workaround?

#### Reproduction Steps

```
import blocksci, pickle
chain = blocksci.Blockchain("/home/ubuntu/bitcoin")
addr_dumped = pickle.dumps(chain.blocks[500002].coinbase_tx.outs.all[0].address)
addr = pickle.loads(addr_dumped)  # kernel crashes
```

#### System Information

Using AMI: yes
BlockSci version: 0.5
Blockchain: Bitcoin 
Parser: Disk/RPC  
Total memory: 61 GB

**Comment by maltemoeser** [comment]
We provide a pickler that should work with BlockSci objects (`blocksci.pickler.Pickler`, `blocksci.pickler.Unpickler`)

**Comment by jiagengliu** [comment]
@maltemoeser Thank you! I am wondering if the reference doc may be updated.
