### ISSUE TITLE
address.txes() missing some transaction

### ISSUE THREAD

**Issue by TTY-00** [citp/BlockSci#310]
#### System Information (if applicable)

Blockchain:Bitcoin
Parser: Disk 
Total memory: 252 GB  

It seems that txes() function  can not get all transactions of an address. Is this a common problem?

**Comment by maltemoeser** [comment]
This often happens if the parser is run with an insufficient open files limit (e.g., #297)

**Comment by maltemoeser** [comment]
Feel free to reopen this issue if your problem hasn't been resolved and you have new information that might help to identify the exact problem.

**Comment by TTY-00** [comment]
I raise my limit to 20000, but still has this problem.  How much does blocksci need? Thanks.

**Comment by TTY-00** [comment]
Maybe it is influenced by the result I parsed before change the limits? Anyway to clean?

**Comment by maltemoeser** [comment]
@TTY-00 You'll need to delete the parser directory (save your mempool recordings if you have any) and re-parse the chain

**Comment by yya518** [comment]
@maltemoeser do you mean that in order for the change open file limits to work, I need to re-parse the chain after setting the limits to 20000?

**Comment by maltemoeser** [comment]
@yya518 yes, the parser needs to be run with a sufficiently large open files limit

**Comment by yya518** [comment]
@maltemoeser So I re-parsed the chain after setting the open file limits to 20000, however, I still got incorrect transaction counts for some addresses. Can you please suggest a solution? Thanks a lot.

**Comment by maltemoeser** [comment]
@yya518 please open a new issue with a reproducible example. There are also a few known bugs on v0.5 with regards to addresses that have been resolved on the development branch v0.6

**Comment by yya518** [comment]
@maltemoeser thanks for the reply. I have updated to branch v0.6 and is checking on the address issue. Will report an issue if I find anything inconsistent.
