### ISSUE TITLE
docs: provide guide for use of v0.6 Python interface

### ISSUE THREAD

**Issue by maltemoeser** [citp/BlockSci#311]
The new Python proxy interface provides a variety of new features to filter and select data without having to instantiate Python objects. However, using Python objects directly can be a lot slower than in v0.5 (#295). We should create a guide that provides an overview of the new interface and how to use it efficiently.

**Comment by jiagengliu** [comment]
Hi! I am wondering there's an update to this? I am not sure how to vectorize `cluster_with_address(some_addresses).index`

**Comment by maltemoeser** [comment]
Updating the docs is more of a medium-term goal as we finalize the interface. For your specific case, I don't think `cluster_with_address` currently works with address proxies

**Comment by jiagengliu** [comment]
Thanks. Since it is the case, could there be an option to use Python objects in a v0.5 way? Also mentioned in #295.

**Comment by maltemoeser** [comment]
Could you provide a code example of what you're trying to achieve that doesn't work with the current interface?

**Comment by jiagengliu** [comment]
Referring to my comment above, I cannot vectorize getting cluster indices from many addresses, and now I have to do `cm.cluster_with_address(addr) for addr in my_tx.outs.addresses.to_list()`, which is slow.
