### ISSUE TITLE
blocksci.Address: difference between first_tx and revealed_tx ?

### ISSUE THREAD

**Issue by crantini** [citp/BlockSci#314]
#### System Information (if applicable)
BlockSci version: v0.6 / 26bfec6e21ae122334f568200878884e96e05c2b

#### Question Body

I am trying to understand the difference between `revealed_tx` and `first_tx` please.

> `out.address.script.revealed_tx` returns `None` when the address has never been spent (https://github.com/citp/BlockSci/issues/56)

The v0.6 documentation was helpful as a start. The above was helpful too. However, I am still not positive that I fully get it.

Can you please lay out briefly and precisely what the difference(s) is between these two methods?

**Comment by maltemoeser** [comment]
Good question, in the C++ the name of that variable is actually a bit more revealing: `txFirstSpent`. The idea behind the name is that a particular script (think address) might receive coins in different transactions, and the first time that one of those coins is spent the script is revealed (e.g., P2PKH reveals the full pubkey or P2SH reveals the output script that was hashed).

In contrast, `first_tx` really is the first transaction in which this script (think address) ever occurred on the blockchain.
