### ISSUE TITLE
compile fails on rlim_t in doctor.hpp

### ISSUE THREAD

**Issue by joequant** [citp/BlockSci#319]
Please provide a clear and concise description of the problem.

doctor.hpp files on error rlim_t

missing include <sys/resource.h>

#### Reproduction Steps

Compile version v0.6 9205e8c878ce5bf313fc6ba9990f8f68785aeb8d

#### System Information

Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch)  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Parser: Disk/RPC  
Total memory: XX GB  

/root/BlockSci/tools/parser/doctor.hpp:22:11: error: 'rlim_t' does not name a type; did you mean 'id_t'?
     const rlim_t MIN_OPEN_FILES = 20000;
           ^~~~~~
           id_t
ESC[0mESC[91m/root/BlockSci/tools/parser/doctor.cpp: In member function 'void BlockSciDoctor::checkOpenFilesLimit()':
/root/BlockSci/tools/parser/doctor.cpp:153:24: error: 'MIN_OPEN_FILES' was not declared in this scope
     if(openFileLimit < MIN_OPEN_FILES) {
                        ^~~~~~~~~~~~~~
ESC[0mESC[91m/root/BlockSci/tools/parser/doctor.cpp:153:24: note: suggested alternative: 'CLONE_FILES'
     if(openFileLimit < MIN_OPEN_FILES) {
                        ^~~~~~~~~~~~~~
                        CLONE_FILES
ESC[0m[ 87%] Building CXX object tools/parser/CMakeFiles/blocksci_parser.dir/hash_index_creator.cpp.o
[ 87%] Building CXX object src/CMakeFiles/blocksci.dir/address/equiv_address.cpp.o

**Comment by maltemoeser** [comment]
Sorry, forgot to push a commit here
