### ISSUE TITLE
dependencies: upgrade rocksdb to latest version

### ISSUE THREAD

**Issue by joequant** [citp/BlockSci#320]
Right now the build fixes rocksdb to a particular revision which cannot be compiled with gcc8 or gcc9 and does not include the latest bug fixes / performance updates.  Before 0.6 release, it would be nice to upgrade the rocksdb to the latest release.

The problem is that the version of rocksdb is of a revision that happens that happens to have a bug that produces rocksdb files that are not forward compatible, so an upgrade requires a rebuild of the database.

The version of rocksdb in blocksci contains the following problem.....

https://tracker.ceph.com/issues/25146

Which causes an upgrade of the rocksdb database to no longer read the current database.

**Comment by maltemoeser** [comment]
Thanks for the heads up! Updating the dependencies is definitely on our backlog for v0.6. If you're already experimentally running on a new version, please let me know if you encounter any other issues!

**Comment by maltemoeser** [comment]
https://github.com/facebook/rocksdb/commit/adcf920f407f0d7b78b71348017e13632fdb95e9 is needed for newer versions to work with cmake, not yet merged into a release
