### ISSUE TITLE
balance(height: int=-1) always return 0 when height not set as default 

### ISSUE THREAD

**Issue by mengmengtech** [citp/BlockSci#322]
###  balance(height: int=-1) always return 0 when height set as default 
***
 - version: V0.6
 - problem: call balance function with height parameter to use the address object to Calculates held by this address at the height
 - Example:
<pre><code>
addr = chain.address_from_string('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa')
for i in range(-100000,100000):
	if addr.balance(i)*1e-8 > 0:
		print(str(addr.balance(i)*1e-8))
</code></pre>

Result: only one record "18.0963985" 
	
Checked result from blockchain.com:
	- No. Transactions	1752	
	- Total Received	68.11770993 BTC	
	- Final Balance	68.11770993 BTC

***
	
Anything wrong with my usage?
Hopefuly can get your suggestion upon it. thanks much!

**Comment by maltemoeser** [comment]
In your example, `addr` is a P2PKH address. However, it was also used as P2PK address (blockchain.info shows them as the same address, in BlockSci they are different). Our docs have some [further explanation](https://citp.github.io/BlockSci/reference/addresses/equiv_address.html).

In your case, you'll probably want to use `addr.equiv()`:

```python
addr
> PubkeyHashAddress(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa)

addr.balance()
> 1810770993

addr.equiv()
> EquivAddress(PubkeyAddress(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa), PubkeyHashAddress(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa))

addr.equiv().balance()
> 6811770993
```
