### ISSUE TITLE
How blocksci set the cluster updated when new block received with 'increasement' way?

### ISSUE THREAD

**Issue by mengmengtech** [citp/BlockSci#323]
#### Does Blocksci cluster has the method for 'increasement' update?
***
 - version: V0.6 & 0.5
 - problem: <b>create_clustering</b> does not support 'increasement' update
 - questions:
 
	 - comparing blocksci_parser can create parser from latest <b>blockheight</b>
	 - whether/how to set the cluster updated when new block received？
	 - whether the <b>clusterid</b> changed for new clusterid? is it possible to merge together for "increament update"?

We called function via python like belows:
```	 
import blocksci
chain = blocksci.chain("bsci.conf") 
cm = blocksci.cluster.ClusterManager.create_clustering("cluster", chain)
```	 

from source code, the "Overwrite" mode does not update from latest cluster status，and seems only overwrite the path directly instead!

<pre>
if (boost::filesystem::exists(path)) {
	boost::filesystem::remove(path);
}
</pre>
     

***

Hopefuly can get your suggestion upon it. Thanks much!

#### System Information

Using AMI: no  
BlockSci version: v0.6 & v0.5  
Blockchain: Bitcoin
Parser: Disk 
Total memory: 128 GB

**Comment by maltemoeser** [comment]
Incremental cluster updates are not supported, though re-running the clusterer is fairly quick :)
See #163 for some discussion of this
