### ISSUE TITLE
Why do my BCH block timestamps not match browser-based block explorers?

### ISSUE THREAD

**Issue by crantini** [citp/BlockSci#325]
#### System Information

Using AMI: no  
BlockSci version: f317c1566afaafc333fbc28e85bcfad7469a6d8c
Blockchain: Bitcoin Cash
Parser: Disk

#### Body

Hello,

Thanks again for a great tool!

I am experiencing this behavior in IPython:

```python
In [6]: chain = blocksci.Blockchain('./bitcoinabc.blocksci_config')
In [10]: chain.blocks[549864].time                                                                                                                                           
Out[10]: datetime.datetime(2018, 9, 28, 17, 40, 1)
```

Via Bash:
```
ubuntu@xxx:~/BlockSci$ date
Tue Sep 17 00:48:56 UTC 2019
```

According to https://www.blockchain.com/bch/block/549864:
> Timestamp 2018-09-28 1:40 PM

According to https://www.blockdozer.com/block/000000000000000000e75a547bca6f184404832f607987309dbcfc3d88c70b22:
> Timestamp | Sep 28, 2018 1:40:01 PM

It would appear that my local BlockSci BCH chain has a timestamp for this block which is inconsistent with two other sources referenced above. (I did not have the mempool recorder running in Sept 2018.)

Do you have any idea why the timestamps are exactly 4 hours apart?

I would be grateful for any guidance on this matter.

**Comment by maltemoeser** [comment]
The timestamps returned in BlockSci are localized, i.e. they depend on your local timezone (which I guess is 4 hours apart from UTC time)

- https://github.com/citp/BlockSci/issues/252
- to convert into UTC: https://github.com/citp/BlockSci/blob/v0.6/test/blockscipy/util.py#L7
- alternatively, work with the timezone independent `block.timestamp` (which you could also convert into a UTC timestamp)

**Comment by crantini** [comment]
Thanks for your help so far, Malte.

I too was sure it must be a simple timezone problem. However, further investigation proved puzzling:

```python
In [9]: import pytz 
   ...: from tzlocal import get_localzone                                                                                                                     
In [10]: def correct_timestamp(ts): 
    ...:     tz = get_localzone() 
    ...:     ts_local = tz.localize(ts) 
    ...:     return ts_local.astimezone(pytz.utc) 
In [14]: get_localzone()                                                                                                                                      
Out[14]: <StaticTzInfo 'Etc/UTC'>

In [11]: chain.blocks[549864].time                                                                                                                            
Out[11]: datetime.datetime(2018, 9, 28, 17, 40, 1)

In [12]: correct_timestamp(chain.blocks[549864].time)                                                                                                         
Out[12]: datetime.datetime(2018, 9, 28, 17, 40, 1, tzinfo=<UTC>)

In [15]: from datetime import datetime                                                                                                                        
In [16]: datetime.utcfromtimestamp(chain.blocks[549864].timestamp)                                                                                            
Out[16]: datetime.datetime(2018, 9, 28, 17, 40, 1)
```

I am indeed physically located in GMT-4. However, the machine running BlockSci as well as IPython is UTC and always has been. Above, I am accessing the IPython directly on my BlockSci machine via SSH.

If this really is a simple timezone problem I feel bad for troubling you over it, but I am just really left scratching my head here.

Do you have any additional advice?

**Comment by crantini** [comment]
Well, hmm, I wonder if I have answered my question.

Via https://explorer.bitcoin.com/bch/block/000000000000000000e75a547bca6f184404832f607987309dbcfc3d88c70b22:
> Date | September 28, 2018 1:40 PM UTC-04:00

The linked page lists 1:40PM just like where else, but also makes explicit that the time is being displayed in GMT-4. This implies that all other explorers were converting the timezone away from UTC as well, but silently.

Perhaps in fact BlockSci's `datetime.datetime(2018, 9, 28, 17, 40, 1, tzinfo=<UTC>)` has actually always been the _only_ correct UTC timestamp!

Is this a sound and well-grounded theory?

**Comment by maltemoeser** [comment]
Seems like you solved it :) If your server is running on UTC, the timestamp returned by BlockSci will be the ("local") UTC timestamp. If it was running on GMT-4, you'd however get that timestamp instead (I hope to fix this with the next version to have everything in UTC, since this is indeed confusing).
