### ISSUE TITLE
Getting Zcash Blockchain

### ISSUE THREAD

**Issue by shiroi-tora** [citp/BlockSci#326]
I want to use Blocksci library to analyze Zcash cryptocurrency. But when I try to get chain of Zcash I got following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/torakun/BlockSci/blockscipy/blocksci/__init__.py", line 172, in new_init
    old_init(self, loc)
RuntimeError: Error, blocksci data directory does not exist

```

#### Reproduction Steps
I have succesfully dowloaded Blocksci latest version as documentation said. Also, I downloaded Zcash to my local computer so I could become a full node. I am new to this so I don't know what where and what I am doing wrong.

Here is my code: 

```
import blocksci
chain = blocksci.Blockchain("/zcash")
```

#### System Information

Using AMI: ?  
BlockSci version: v0.5
Blockchain: Zcash
Parser: 
Total memory: XX GB

**Comment by garethtdavies** [comment]
I would suggest you use this fork which includes some other Zcash specific helpers: https://github.com/cryptolu/BlockSci

That said, that error is likely simply you are trying to use an invalid path for the data directory. I've a quick script here for example that uses Blocksci on Zcash to output transaction data: https://gist.github.com/garethtdavies/5acc0cfa1ed4ac0a653663740a7703e8

**Comment by shiroi-tora** [comment]
I am currently a full node, but what rpc-username and rpc-password mean? Thanks for the reply btw.

**Comment by garethtdavies** [comment]
See here: https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_conf_guide.html#zcash-conf-guide but essentially you just need to set rpcusername and rpcpassword in your `zcash.conf` file.

If you don't have this the zcash node will use cookie-based auth and I'm not sure if Blocksci supports this, you can try removing those options and run without and if you hit auth errors just add those options in and restart your node.

**Comment by shiroi-tora** [comment]
It looks like zcash.conf configurations does not work in my zcash node. Whatever settings I entered in the file, nothings got changed. Sorry for not coming with this problem but wherever I copied zcash.conf my settings just don't work. For example I set gen=1 to mining but fullnode in terminal said you did not.

Thanks for all your fast replies.

**Comment by garethtdavies** [comment]
You will need to restart the daemon to see any effect. Assuming you have something like this in `~/.zcash/zcash.conf` it'll work:

```
addnode=mainnet.z.cash
rpcuser=yourusername
rpcpassword=yourpassword
txindex=1
```

**Comment by shiroi-tora** [comment]
I was always just restarting zcash node. Also, you have written /.zcash rather than /zcash. I also saw that, what is diffierence between these two?

**Comment by garethtdavies** [comment]
It's the location of the folder. It must be `~/.zcash/zcash.conf` (unless you are explicitly loading an alternate conf file). The dot prefix is simply a hidden folder but this is where zcashd looks. This file must exist or zcashd won't start see https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#configuration

**Comment by shiroi-tora** [comment]
I have both zcash and .zcash directories. Probably some of my errors caused by this. Will try tomorrow.

**Comment by shiroi-tora** [comment]
I am currently trying `blocksci_parser --output-directory zcash-data update --max-block -100 rpc --username your-rpc-username --password your-rpc-password --address 127.0.0.1 --port 8232` command but got an error:
`Error while interacting with RPC: std::exception
terminate called after throwing an instance of 'BitcoinException'
  what():  std::exception
Aborted` 

I am trying some solution but because of earthquake I can't get good result. I will update my results.

**Comment by shiroi-tora** [comment]
Hi again. I am still given this error. Could it be I have  to use a specific RPC username-password rather than a user-given6+ RPC ID-PW?

**Comment by garethtdavies** [comment]
Whatever values you use ifor username and password in ```blocksci_parser --output-directory zcash-data update --max-block -100 rpc --username your-rpc-username --password your-rpc-password --address 127.0.0.1 --port 8232``` must match whatever is in your zcash.conf file so just update this command to edit the username and password.

**Comment by shiroi-tora** [comment]
After some painful delays, I succesfully parsed zcash and got full chain. Thank you, it really helped. 

When I tried running your code I got the error that Tx class doesn't have anything names vpub_count or sspend_count. When I tried to look for Blocksci documentation for v0.5.0, vpub_count wasn't there also. Searched zcash community, no luck. Is there any zcash-specific Blocksci helpers/libraries I am missing?

**Comment by garethtdavies** [comment]
Yes, I am using this fork for that code: https://github.com/cryptolu/BlockSci. You can do it without but this already includes some useful Zcash helpers that are included in that script.

**Comment by shiroi-tora** [comment]
Before closing this issue, I want to ask several question regarding it. I deleted original Blocksci project and cloned than installed cryptolu's BlockSci. After that, I tried to fetch chain and got errors (exit code 136 on pycharm and terminated kernel on Jupyter). 

1. It looked like my Zcash-data didn't worked probably so I had to delete folder & re-parse it. Is it because I am now using forked version of BlockSci?

2. Do I have to delete zcash-data folder and reparse it everytime? It last almost 12-13 hours and waiting is unbearable.

**Comment by garethtdavies** [comment]
1. Not sure, but probably there is some incompatibility so the first time you might just have to start again (as you did).
2. Definitely no. After the first import (which does take a while) it'll just process blocks that it doesn't have. As above, I use this on a schedule to import and just adds the additional blocks. Note that I am requesting up to the last 100 blocks as this is the rollback limit in Zcash so there is no chance of a re-org.

```blocksci_parser --output-directory zcash-data update --max-block -100 rpc --username your-rpc-username --password your-rpc-password --address 127.0.0.1 --port 8232```

**Comment by shiroi-tora** [comment]
Thanks for everything.
