### ISSUE TITLE
cluster.addresses causes Segfault 

### ISSUE THREAD

**Issue by AndyShenAS** [citp/BlockSci#328]
I am using the v0.6 version of blocksci, but it seems that some of the cluster's apis will cause segfault. I want to get all the addresses of a cluster, can you help me with this problem?

#### Reproduction Steps

```python
>>> import blocksci
>>> chain = blocksci.Blockchain("/data/bsci/newbsci.conf")
>>> cm = blocksci.cluster.ClusterManager("/data/bsci/clusters/cluster",chain)
>>> address = chain.address_from_string("3EhLZarJUNSfV6TWMZY1Nh5mi3FMsdHa5U")
>>> cluster = cm.cluster_with_address(address)
>>> addrs = [address for address in cluster.addresses]
>>> print(len(addrs))
111
>>> print(address.__class__)
<class 'blocksci.ScriptHashAddress'>
>>> print(address.address_string)
3EhLZarJUNSfV6TWMZY1Nh5mi3FMsdHa5U
>>> print(addrs[0].__class__)
<class 'blocksci.ScriptHashAddress'>
>>> print(addrs[0].address_string)
Segmentation fault
```

#### System Information

Using AMI: no
BlockSci version: v0.6 branch, commit id 589a00b
Blockchain: Bitcoin
Parser: Disk
Total memory: 128 GB

**Comment by maltemoeser** [comment]
Yep this is a known bug, you'll need to use `cluster.addresses.to_list()` for now.

Related: #273, #296
