### ISSUE TITLE
Segmentation fault BTC block 599499

### ISSUE THREAD

**Issue by simonohanlon101** [citp/BlockSci#331]
_Please provide a clear and concise description of the problem:_
Running the blocksci parser results in a segmentation fault from block 599499 on the Bitcoin blockchain. 

#### Reproduction Steps

```
/usr/bin/blocksci_parser --output-directory /home/ubuntu/bitcoin update --max-block -10  disk --coin-directory /home/ubuntu/.bitcoin

100.0% done fetching block headers
Starting with chain of 599498 blocks
Removing 0 blocks
Adding 21 blocks
0.00% done, Block 599499/599519Failed to load tx from block599508 at offset 94035681.
Tried to advance past end of fileSegmentation fault (core dumped)
```

#### System Information

Using AMI: yes  
BlockSci version: 0.5
Blockchain: Bitcoin
Parser: Disk  
Total memory: 512 GB

**Comment by maltemoeser** [comment]
Thanks for the report, this didn't occur on our machine so I'm not sure why this happened. I'd recommend trying to reparse and maybe re-download the blockchain to see if still occurs

**Comment by simonohanlon101** [comment]
Thanks for the reply. In order to reparse is it a case of simply removing the blocksci data directory, then re-running the parser?

**Comment by maltemoeser** [comment]
@simonohanlon101 if you have mempool timestamp recordings in there that you'd like to preserve, make sure to backup the `mempool` folder before you remove the directory

**Comment by maltemoeser** [comment]
@simonohanlon101 were you able to resolve this with a reparse/redownload?

**Comment by ishitadaga** [comment]
when i run this command:
blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin

I get the following output:
Starting with chain of 0 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
Updating address index
Updating index with scripts of type multisig_script

Why is it not adding any new blocks?
