### ISSUE TITLE
Using clustering strategy in v0.6

### ISSUE THREAD

**Issue by yya518** [citp/BlockSci#333]
Using AMI: no  
BlockSci version: 0.6
Blockchain: Bitcoin
Parser: Disk
Total memory: 256 GB

 I'm using the clustering heuristics in v0.6. However, it seems that the API method has different inputs from that in v0.5. I got the following error message with the code.
`cm = blocksci.cluster.ClusterManager.create_clustering(CLUSTER_DIR, chain,no_change_heuristic)`

> TypeError: create_clustering(): incompatible function arguments. The following argument types are supported:
    1. (location: str, chain: blocksci.Blockchain, start: int=0, stop: int=-1, heuristic: blocksci.heuristics.change.ChangeHeuristic=<blocksci.heuristics.change.ChangeHeuristic object at 0x7fe9f3444c38>, should_overwrite: bool=False, ignore_coinjoin: bool=True) -> blocksci.cluster.ClusterManager
Invoked with: 'bitcoin-cluster', <blocksci.Blockchain object at 0x7fea16d6ea98>, <blocksci.heuristics.change.ChangeHeuristic object at 0x7fea341df7d8>
 

Can anyone explain what is the meaning of start=0, and end=-1? 

Am I missing anything using the following code?
`no_change_heuristic = blocksci.heuristics.change.legacy - blocksci.heuristics.change.legacy`
`cm = blocksci.cluster.ClusterManager.create_clustering(CLUSTER_DIR, chain, 0, -1, no_change_heuristic)`

Well, it also used to be blocksci.heuristics.change.legacy() in v0.5.

**Comment by maltemoeser** [comment]
Try the following

```
heuristic = blocksci.heuristics.change.none
cm = blocksci.cluster.ClusterManager.create_clustering(CLUSTER_DIR, chain, heuristic=heuristic)
```

**Comment by maltemoeser** [comment]
> Can anyone explain what is the meaning of start=0, and end=-1?

These are the block heights over which the clustering is run (all blocks by default).

**Comment by yya518** [comment]
thanks. it answers my question and solves my issue.
