### ISSUE TITLE
possible for blocksci to return fix clusterid when recreate cluster?

### ISSUE THREAD

**Issue by mengmengtech** [citp/BlockSci#337]
Currently the blocksci seems generated clusterid changed everytime I recreate cluster，however you know， the cluster required to be tagged in my working database.

My question is:
Whether it possible for blocksci to get fix clusterid?  ur kindly response upon it will be appreciated. 
Incase not possible, some rule / suggestion for cluster tagging?
thanks.

#### System Information (if applicable)

Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch)  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Parser: Disk/RPC  
Total memory: XX GB

**Comment by maltemoeser** [comment]
No, with the current implementation that's not possible. I'd suggest to tag based on addresses contained in the clusters.
