### ISSUE TITLE
How to actually tag an address or cluster?

### ISSUE THREAD

**Issue by amichaelix** [citp/BlockSci#339]
So I have been working with BlockSci 0.6 and everything is working great. The only one thing I didn't figure out is how to actually tag a cluster and/or address assuming I have a list of address<>entity. Is there a address.tag(tag:str) method?

**Comment by maltemoeser** [comment]
[ClusterManager](https://citp.github.io/BlockSci/reference/clustering/cluster.html#blocksci.cluster.Cluster.tagged_addresses) and [Cluster](https://citp.github.io/BlockSci/reference/clustering/cluster.html#blocksci.cluster.Cluster.tagged_addresses) have methods to provide tags. I haven't used these in a while, but I'll see if I can write up an example for the FAQ when I find the time.

**Comment by maltemoeser** [comment]
I've added an example to the FAQ: [How do I use BlockSci's tagging feature?](https://github.com/citp/BlockSci/wiki#toc-clustering-tagging)
