### ISSUE TITLE
error in parsing

### ISSUE THREAD

**Issue by ishitadaga** [citp/BlockSci#342]
when i run this command:
blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin

I get the following output:
Starting with chain of 0 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
Updating address index
Updating index with scripts of type multisig_script

Why is it not adding any new blocks?

**Comment by martinplattnr** [comment]
The `--coin-directory` parameter must point to the `datadir` of a (fully) synced Bitcoin node.
That's most likely what's wrong.

**Comment by ishitadaga** [comment]
@martinplattnr Thanks for helping. I am a bit new to bitcoin, so I want to know, that while compiling the Blocksci, does the full node gets downloaded? And if not could you suggest me how can I download it. I am using Ubuntu server.

**Comment by martinplattnr** [comment]
No, installing BlockSci does _not_ install and sync Bitcoin data.
You need to install Bitcoin Core and let the node sync, this may take several days.
Searching for "run bitcoin node" or "install bitcoin node" should help you out.

**Comment by ishitadaga** [comment]
oka thanks
