### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by ishitadaga** [citp/BlockSci#345]
I was running 
"blocksci_parser --output-directory bitcoin-data update disk --coin-directory /.bitcoin" this command and forcefully stopped it after 80% completion. 

Now when I run the command chain = blocksci.Blockchain('path to bitcoin-data') in python I get an error saying: RuntimeError: Error, data directory does not contain config.ini. Are you sure /home/dagaish15_id/results/bitcoin-data was the output directory of blocksci_parser?
I wanted to know that is the config.ini formed only after the completion of the above parser command? 

Also when I make an empty file called config.ini and again run the command I get the following error:RuntimeError: Error, parser data is not in the correct format. To fix you must delete the data file and rerun the parser

**Comment by maltemoeser** [comment]
Interrupting the parser likely leads to data corruption, you'll need to delete the data in the output directory and re-run it (#33).
