### ISSUE TITLE
Using Seaborn and Plotly libraries with the EC2 instance

### ISSUE THREAD

**Issue by paperbrains** [citp/BlockSci#346]
I was hoping to use both the Seaborn and Plotly libraries while accessing Blocksci via the quick setup Amazon EC2 method.

Are these libraries able to be installed for the EC2 users? Thanks.

#### System Information (if applicable)

Using AMI: yes
BlockSci version: 0.5   
Blockchain: Bitcoin

**Comment by martinplattnr** [comment]
I am not using the AMI setup myself, but I assume that you can simply SSH onto your server and install Seaborn and Plotly as described in the respective manuals, eg. https://seaborn.pydata.org/installing.html

**Comment by paperbrains** [comment]
Thanks @martinplattnr . I had blindly just copied the ssh command as in the documentation. I didn't realise that the inclusion of `-N`  in that line was prohibiting me from executing any remote command. All fixed now and I have installed my packages!
