### ISSUE TITLE
How to use Other Heuristics

### ISSUE THREAD

**Issue by candre-rungood** [citp/BlockSci#348]
In the heuristic page of the documentation https://citp.github.io/BlockSci/reference/heuristics/other_heuristics.html

I was looking at 
blocksci.heuristics.poison_tainted_outputs(output: blocksci.Output, tainted_value: int) → List[Tuple[blocksci.Output, int]]
    Returns the list of current UTXOs poison tainted by this output

but I'm note sure how to use it.
Is there an example of how to use it? 
How do i select an Output? the one i get from tx are tx outputs TxOut()

thanks

**Comment by maltemoeser** [comment]
Taking the output of a transaction should work with the heuristic

**Comment by candre-rungood** [comment]
Do you have a quick example?

it says Invoked with: 

>  poison_tainted_outputs(): incompatible function arguments. The following argument types are supported:
>     1. (outputs: List[blocksci.Output], max_block_height: int=-1, taint_fee: bool=True) -> List[Tuple[blocksci.Output, Tuple[int, int]]]
> 
> Invoked with: TxOut

When i select a transaction output

Thanks

**Comment by maltemoeser** [comment]
The error tells you to pass in a list, simply wrap your output in square brackets `[out]`

**Comment by candre-rungood** [comment]
I tried this

> 
> outputs = [output for output in chain.blocks[1000].coinbase_tx.outs]
> poison_tainted_outputs = blocksci.heuristics.poison_tainted_outputs(outputs)

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-8-58b44599c375> in <module>
>       1 outputs = [output for output in chain.blocks[1000].coinbase_tx.outs]
> ----> 2 poison_tainted_outputs = blocksci.heuristics.poison_tainted_outputs(outputs)
> 
> RuntimeError: Caught an unknown exception!

I was trying with litecoin if that matters?

**Comment by maltemoeser** [comment]
Yeah IIRC remember certain aspects of the logic were only implemented for Bitcoin.
