### ISSUE TITLE
How to use AddressIterator

### ISSUE THREAD

**Issue by jiagengliu** [citp/BlockSci#349]
Specs: BlockSci v0.6, AWS, 61GB RAM

Running the following code causes Segfault:
```
chain = blocksci.Blockchain(CONFIG_FILE)
for a in chain.blocks[100000].inputs.address:
    print(a.in_txes_count())
```

The following code yields unexpected results:
```
for a in chain.blocks[100000].inputs.address:
    print(a.raw_type)  # prints 0 0 0 
    print(a.address_num)  # prints 5664748 5664748 5664748
```
`.to_list()` works, so I wonder if it is related to #273? 

Previous question:
I am trying to get `raw_type` and `address_num` as two arrays for all inputs from a block range. However, `chain.blocks.inputs.address` returns an `AddressIterator`, which does not provide `raw_type` and `address_num`. I was wondering about a workaround for it.

Thank you!

**Comment by maltemoeser** [comment]
Quite likely related to #273.

For your previous question, try
```python
chain.blocks.inputs.address.map(lambda a: a.raw_type)
```

**Comment by jiagengliu** [comment]
Thank you! That works.
