### ISSUE TITLE
Just a question on CoinJoin detection.

### ISSUE THREAD

**Issue by aingo03304** [citp/BlockSci#350]
Hello, I found something suspicious on isCoinJoin
```c
        using pair_type = decltype(outputValues)::value_type;
        auto pr = std::max_element(std::begin(outputValues), std::end(outputValues),
                                   [] (const pair_type & p1, const pair_type & p2) {
                                       return p1.second < p2.second;
                                   }
                                   );
        
        if (pr->second != participantCount) {
            return false;
        }
        
        if (pr->first == 546 || pr->first == 2730) { // here
            return false;
        }
```
Can I know why pr->first is 546 or 2730 implies the tx is not CoinJoin?
I know 546 is the common dust-limit, but cannot find any information about 2730.

Thanks in advance!

**Comment by maltemoeser** [comment]
[See here](https://bitcointalk.org/index.php?topic=1214993.msg12737337#msg12737337)

**Comment by aingo03304** [comment]
@maltemoeser Then, can I know why the tx is not coinjoin if the dust-limit appears most?

**Comment by maltemoeser** [comment]
It's unlikely someone would create a CoinJoin to send dust-sized outputs. But it's just a heuristic, if you have contrary evidence please feel free to share!
