### ISSUE TITLE
parser not parse all blocks

### ISSUE THREAD

**Issue by ilzc** [citp/BlockSci#351]
Please provide a clear and concise description of the problem.

I'm running bitcoind 0.18.0 and sync blocks up to height 607040 which I've checked by bitcoin-cli. But while using blocksci_parser to parse the bitcoin datadir.It can't find all the blocks. With parser doctor tools ,I found out that block found in coin directory has height 585614 (in file 1722) which means the parser can only find blk01722.dat. But actually  files up to blk01888.dat in the /blocks folder.Is there anything index not correct?I've tired bitcoind -reindex but it doesn't work.

#### System Information

Using AMI: no  
BlockSci version: d6ac451
Blockchain: Bitcoin
Parser: Disk  
Total memory: 64 GB

**Comment by ilzc** [comment]
I've tried re-sync bitcoin data, everything work well . Not sure what cause that problem.

**Comment by maltemoeser** [comment]
Sometimes the block data seems to get corrupted in a way that BlockSci can't read them but Bitcoin Core is still fine.
