### ISSUE TITLE
Very slow performance on local machine

### ISSUE THREAD

**Issue by trekianov** [citp/BlockSci#356]
The generation of the Bitcoin data library is increasingly slower: at block 400000 I am currently processing about 10000 blocks per day, which means that, being optimistic, I have still at least twenty days of computation to go.
Is it possible to have a something like a snapshot of the Bitcoin data library recently generated so I could copy it and update locally? It would be a great help for people with limited computational resources.
Using AMI: yes/no  
BlockSci version: latest (0.5.0)
Blockchain:  Bitcoin
Parser: Disk
Total memory: 24GB

**Comment by maltemoeser** [comment]
24GB is insufficient for Bitcoin, you'll need to use a stronger machine. We currently don't provide snapshots (see #2).
