### ISSUE TITLE
Syncing blocks past May 2018 results in an error

### ISSUE THREAD

**Issue by wnuelle** [citp/BlockSci#358]
I'm running the following in CLI for AWS, trying to update the data past May 2018 (which don't seem to be updating after ~6hrs): blocksci_parser --output-directory blocksci update disk --coin-directory bitcoin 

I'm getting an error as a result.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not open hash index with error: While appending to file: /home/ubuntu/blocksci/hashIndex/MANIFEST-000001: No space left on device

I'm new to BlockSci and specifically am confused about "No space left on device." I posted this as a question because I don't believe it's an issue with the code. It's likely a limitation in my understanding.

**Comment by trekianov** [comment]
There is a problem with the size of the chain and the output, as stated in the pinned issue [.](https://github.com/citp/BlockSci/issues/302) The workaround is the following: when creating your AMI from the EC2 image in the readme file, do NOT click the blue "Review and Launch" button right away. Instead, proceed with the configuration and change the size of the root volume to something above 700 GB, as properly stated by @jiagengliu

**Comment by wnuelle** [comment]
Thank you for your really helpful comment! I appreciate it.
