### ISSUE TITLE
litecoin - different cluster while same input

### ISSUE THREAD

**Issue by candre-rungood** [citp/BlockSci#359]
Hello, 
With the latest v0.6 blocksci version, I want to only use same input heuristic blocksci.heuristics.change.none

I found a litecoin tx that does not return same cluster index for address that are used as input in a tx
```

tx = chain.tx_with_hash('21ee73ea36af2a63662109eb55d202f80958ef23b10d5a7ef90ecc84cca15cd2')
for input_tx in tx.ins:
    a = input_tx.address
    print (a, cm.cluster_with_address(a).index)
```

`ScriptHashAddress(MDRPJodVKvRuKb93XAV25vdKaubGj8j2kC, wrapped_address=WitnessPubkeyAddress(ltc1q9y6dt7e5m4n8tsd90y6z69uthl748ql44maddc)) 4172281
ScriptHashAddress(MPZtPt3yCn7j3derTWo3sGj6DBnkFP1JYg, wrapped_address=WitnessPubkeyAddress(ltc1q4c8hky3xdvk0p6497ne97dm20hma2v28mw5c3x)) 4173410
ScriptHashAddress(MSYvh7Q4ue2GjBB1BbVnt9zfq8CuZXYJCn, wrapped_address=WitnessPubkeyAddress(ltc1qq8e8tx539q26yrdvd3neqn89vwy509wxrf3l2s)) 4173402
ScriptHashAddress(MJXidzhYX3LmT4eBu2h9A7TKkjYTanD3bb, wrapped_address=WitnessPubkeyAddress(ltc1qqqnq0t7dur0cq2sct0ds2ccgrxng5sp6jh04qu)) 4172762
ScriptHashAddress(MN6reqaqdhGpvXip5rbt2nH5yXKc7hSbbr, wrapped_address=WitnessPubkeyAddress(ltc1q9svcea98lnr525gmms7vuvxud44dnum4zqh9y8)) 4173329
ScriptHashAddress(MA59JDhWcAMnmkRT7GvwSzfCvxdhTqFkRK, wrapped_address=WitnessPubkeyAddress(ltc1q29p9n7s7dqtjaxxw0gh0nrwqttp5nzwv5z3kgc)) 4173393
`

I tried with another blocksci setup and the same problem arises.

Thanks

**Comment by candre-rungood** [comment]
I runned a script to find other tx where the problem occurs and found 9284 tx where inputs do not have the same cluster id

https://pastebin.com/Ti5GBP5S
https://pastebin.com/AsbdytjS

**Comment by maltemoeser** [comment]
Clustering ignores coinjoin transaction (or transactions that look like coinjoin) by default. You can set the parameter `ignore_coinjoin=False` to cluster coinjoin transactions when creating the clustering.
