### ISSUE TITLE
Please support bootstrap.dat File

### ISSUE THREAD

**Issue by shufps** [citp/BlockSci#36]
Please support the bootstrap.dat File format.

This would speed up a lot ... This 150GB bootstrap-files can be downloaded and importet to bitcoin core but import takes a looong time. It would be extremly helpful when BlockSci directly could use bootstrap-files.

**Comment by hkalodner** [comment]
This is a great idea. To my understanding bootstrap.dat files are in the same (or very close to the same) format as blk0001.dat files so this should be fairly easy to add to the parser.
