### ISSUE TITLE
v0.6 clustering is not working in some cases.

### ISSUE THREAD

**Issue by gateman1218** [citp/BlockSci#360]
Please provide a clear and concise description of the problem.

#### Reproduction Steps

```
import blocksci
chain = blocksci.BlockChain("./btc.cfg")
cm = blocksci.cluster.ClusterManager(PATH_OF_CLUSTER, chain)
btc_addr = "BITCOIN ADDRESS"
cluster = cm.cluster_with_address(btc_addr)
print(cluster.size()) //stuck!
print(cluster.index) // always "0"
print(cluster.type_equiv_size) // always "245397714"
print(cluster.addresses.to_list()[0]) // stuck!
```

#### System Information

Using AMI: no  
BlockSci version: v0.6 latest version (bccf558)
Blockchain: Bitcoin  
Parser: Disk
Total memory: 64 GB  

I made a cluster without change address heuristic. After that, I printed out the cluster indexes of several Bitcoin addresses, but the results are all "0". 
Also, the program was stuck on listing all addresses in the clusters as well.

There are many addresses showing the above results. Here are several addresses: 3NhN9zDdLTGhvkytDs8KP5aKESRQ7WWR2P, 18jH83cJMjcd8yyUcy6nUEWYi3gYU2kGe1, 3EAtx1SsPEDH3n4ZZE4rqkrq4PovLweVGL, 3NokVzWnKgQkNfTZUZyJ54nHX3L3UXQxz5

**Comment by maltemoeser** [comment]
I'm not able to reproduce your behavior. How exactly did you create the cluster? It looks like you might have cluster collapse and all addresses are in a supercluster (`.size()` and `.addresses` would be slow since they need to go through millions of addresses)

```python
import blocksci
chain = blocksci.Blockchain("/blocksci/btc.json")
len(chain)
```

> 611902

```python
cm = blocksci.cluster.ClusterManager.create_clustering("../clusters/360/", chain)

cluster = cm.cluster_with_address(chain.address_from_string("3NhN9zDdLTGhvkytDs8KP5aKESRQ7WWR2P"))
```
```python
cluster.index
```
> 44602723
```python
cluster.type_equiv_size
```
> 1437994
```python
cluster = cm.cluster_with_address(chain.address_from_string("18jH83cJMjcd8yyUcy6nUEWYi3gYU2kGe1"))
```
```python
cluster.index
```
> 380407083

```python
cluster.type_equiv_size
```

> 1

**Comment by gateman1218** [comment]
I all cleaned up compiled object files and re-compiled everything as well as created a cluster again.
Then, there are no issues anymore. The latest head on v0.6 branch works fine.

Thank you for a very quick response.
