### ISSUE TITLE
What does DedupAddressType stand for ? I could not find the meaning of it in documentation.

### ISSUE THREAD

**Issue by kunduzb17** [citp/BlockSci#361]
#### System Information (if applicable)

Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch)  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Parser: Disk/RPC  
Total memory: XX GB

**Comment by maltemoeser** [comment]
BlockSci deduplicates address data, i.e. when the same key has been used with different address formats: [Equivalent Addresses - BlockSci documentation](https://citp.github.io/BlockSci/reference/addresses/equiv_address.html)
