### ISSUE TITLE
Incremental updates of the parser

### ISSUE THREAD

**Issue by kunduzb17** [citp/BlockSci#362]
Can I have a question about incremental update of the parser? Initially I have 436007 blocks, after that I have upgraded my bitcoin until 546016 , should I do `blocksci_parser --output-directory bitcoin-data update --max-block -110009 disk --coin-directory .bitcoin` ?

P.S I tried something similar , then all my data got corrupted , so I had to reparse from the beginning, and it took a long time.
#### System Information (if applicable)

Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch)  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Parser: Disk/RPC  
Total memory: XX GB

**Comment by maltemoeser** [comment]
You can use `--max-block 546016`. Perhaps make a copy of your parser directory in case something breaks during the update.

Also, consider using the development version v0.6 since there are some bugs in v0.5 that [have been fixed](https://github.com/citp/BlockSci/issues?q=is%3Aopen+is%3Aissue+label%3Afixed-in-v0.6) in v0.6.

**Comment by kunduzb17** [comment]
Thanks for quick response!
I had followed your instructions.
So, blocksci_parser added blocks and updated hash index successfully.
However, while updating address index it makes error: too many open files.
Do you know how I can resolve it?

-------------------------------------------
```
100.0% done fetching block headers
Starting with chain of 613056 blocks
Removing 0 blocks
Adding 1 blocks
0.00% done, Block 613057/613057
Back linking transactions

Updating hash index
Updating index with 169884978 txes
100.00% doneterminate called after throwing an instance of 'std::runtime_error'
  what():  Could not open address index with error: While open directory: /home/ubuntu/bitcoin-data/addressesDb: Too many open files
Aborted (core dumped)
```

**Comment by maltemoeser** [comment]
You’ll need to increase the open files limit, here is a guide that I’ve relied on in the past: https://ro-che.info/articles/2017-03-26-increase-open-files-limit
