### ISSUE TITLE
C++ interface example

### ISSUE THREAD

**Issue by kunduzb17** [citp/BlockSci#364]
I have tested BlockSci on Jupiter Notebook interface, and it seems work fine.
But I have an issue with C++ interface. I had created play.cpp file on BlockSci directory, it contains simple lines of code
```
#include <blocksci/blocksci.hpp>

int main(int argc, const char * argv[]) {
        blocksci::Blockchain chain{"/home/ubuntu/bitcoin-data"};
}
```
So, I run it by `g++ play.cpp -o play` on BlockSci directory, however I have error:
```
In file included from /usr/include/blocksci/chain/output.hpp:19:0,
                 from /usr/include/blocksci/chain/transaction.hpp:12,
                 from /usr/include/blocksci/chain/algorithms.hpp:12,
                 from /usr/include/blocksci/chain.hpp:12,
                 from /usr/include/blocksci/blocksci.hpp:14,
                 from play.cpp:1:
/usr/include/blocksci/address/address.hpp:20:10: fatal error: range/v3/view/any_view.hpp: No such file or directory
 #include <range/v3/view/any_view.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I had checked #238 issue, however it did not help.

#### System Information (if applicable)

Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch)  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Parser: Disk/RPC  
Total memory: XX GB

**Comment by maltemoeser** [comment]
It's not finding the rangev3 library. The easiest way to compile and run your code would be to modify `example/example.cpp` and then run `make blocksci_example`

**Comment by kunduzb17** [comment]
It still shows the same error.

```
ubuntu@ip-172-78-89-876:~/BlockSci/example$ g++ example.cpp -o exampleIn file included from /usr/include/blocksci/chain/output.hpp:19:0,                 from /usr/include/blocksci/chain/transaction.hpp:12,                 from /usr/include/blocksci/chain/algorithms.hpp:12,
                 from /usr/include/blocksci/chain.hpp:12,
                 from /usr/include/blocksci/blocksci.hpp:14,
                 from performance.hpp:12,
                 from example.cpp:9:
/usr/include/blocksci/address/address.hpp:20:10: fatal error: range/v3/view/any_view.hpp: No such file or directory
 #include <range/v3/view/any_view.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by aingo03304** [comment]
@kunduzb17 You can execute example after you compile the blocksci. 
Try <built directory: release>/example and then do `make blocksci_example`
