### ISSUE TITLE
Reproduce clustering on another machine?

### ISSUE THREAD

**Issue by jiagengliu** [citp/BlockSci#373]
BlockSci version: v0.6
Blockchain: Bitcoin
 
----

I was wondering if clustering is deterministic and/or reproducible on another machine? In particular, can we retrieve the parameters used to create a cluster, such as `start`, `end`, and/or `heuristic`? 

Thank you so much.

**Comment by maltemoeser** [comment]
It should be deterministic, though I believe due to the `linkScripthashNested` step during clustering it will currently only produce the same results if the `chain` objects are the same (i.e. have the same height)

**Comment by jiagengliu** [comment]
Thank you! Is there a way to retrieve the height, start, end, and/or heuristic information from an existing cluster?

**Comment by maltemoeser** [comment]
No, that information isn't stored in the clustering.

**Comment by jiagengliu** [comment]
I wish it were. Thanks though!
