### ISSUE TITLE
chain of 0 blocks removing 0 blocks adding 0 blocks [parser]

### ISSUE THREAD

**Issue by jamieserrano** [citp/BlockSci#379]
Hello, 

I have generated a bitcoin config file with blocksci parser running: 

`blocksci_parser /home/dockeruser/blocksci_data/btc.cfg generate-config bitcoin /home/dockeruser/blocksci_data --max-block '-6' --disk /home/dockeruser/block_data`

which creates the following config file:

```{
    "chainConfig": {
        "coinName": "bitcoin",
        "dataDirectory": "/home/dockeruser/blocksci_data",
        "pubkeyPrefix": [
            0
        ],
        "scriptPrefix": [
            5
        ],
        "segwitActivationHeight": 481824,
        "segwitPrefix": "bc"
    },
    "parser": {
        "disk": {
            "blockMagic": 3652501241,
            "coinDirectory": "/home/dockeruser/block_data",
            "hashFuncName": "doubleSha256"
        },
        "maxBlockNum": -6
    },
    "version": 5
}
```

but when I run `blocksci_parser /home/dockeruser/blocksci_data/btc.cfg update`I get the response:

```275GB of free disk space available.
OK: Open files limit of 1048576.

Locking data directory.

Starting with chain of 0 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
Updating address index
Updating index with scripts of type multisig_script

Unlocking data directory.
```

would someone be able to help me with this issue?

for context, 

`/home/dockeruser/block_data` contains  a series of blk000xx.dat files, rev000xx.dat files, and a folder index. in index I have .1db files, CURRENT, LOCK, MANNIFEST-xxx

and blocksci_data is empty. is this correct formatting?

**Comment by maltemoeser** [comment]
The coin directory is intended to point to the top-level directory of the blockchain data as produced by most clients, try moving the `*.blk` files into a `blocks` subdirectory in your `block_data` folder and it should work. If it doesn't, try running `blocksci_parser /home/dockeruser/blocksci_data/btc.cfg doctor` and see if it reports any problems.

**Comment by jamieserrano** [comment]
ah, of course. Thanks!

**Comment by jamieserrano** [comment]
Hello,

I I copied the output directory (with addressDb, chain, config.ini,
hashIndex, parser, scripts) from one EC2 instance to a larger one. On this
new instance I have blocksci installed and the output directory, but when I
go to read the chain with
chain = blocksci.Blockchain("/home/ubuntu/blocksci-output/") I get the
error:

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/home/ubuntu/BlockSci/blockscipy/blocksci/__init__.py", line 289,
in new_init

    old_init(self, loc)

RuntimeError: Error, path /home/ubuntu/blocksci-output must point to to
existing blocksci config file

**Comment by mplattner** [comment]
If you use v0.6, you must provide the path to the config _file_, not just the data directory, e.g., `chain = blocksci.Blockchain("/home/ubuntu/blocksci-output/CONFIG.JSON")`.
Also check file permissions if this does not fix the issue.

**Comment by jamieserrano** [comment]
Ah thank you. One of my instances has blocksci v0.5.0 while the new one has
v0.6. When I installed blocksci, on the new instance, I followed these
instructions: https://citp.github.io/BlockSci/compiling.html But it seems I
have still ended up with version 0.6. Is there a way for me to install
version 0.5 For now?

Regards,

Jamie.

**Comment by mplattner** [comment]
You can checkout a revision prior to merging the v0.6 branch, e.g., commit https://github.com/citp/BlockSci/commit/e0237e2f06a19ca81162b7803c599217bc1f3682 via `git checkout e0237e2f06a19ca81162b7803c599217bc1f3682`.
