### ISSUE TITLE
File missing blocksci_interface on GIT

### ISSUE THREAD

**Issue by mjpiedade** [citp/BlockSci#38]
Hi there,

When I start with import blocksci I get the error message below:
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nowhere/BlockSci/blocksci/__init__.py", line 1, in <module>
    from blocksci.blocksci_interface import *
ModuleNotFoundError: No module named 'blocksci.blocksci_interface'

I looked for the file in my system and on GIT and the file is missing. There is no blocksci_interface.so file.

Can you help?

Regards,
Miguel Piedade

**Comment by hkalodner** [comment]
In order to run BlockSci you must build it from source. There are build instructions towards the bottom of the readme. BlockSci has a python library interface, but it is a thin layer over a library written in C++.
