### ISSUE TITLE
std::bad_alloc error when running blocksci_parser

### ISSUE THREAD

**Issue by shihao-guo** [citp/BlockSci#39]
When I run blocksci_parser to update it throws error msg without much context, I'm wondering if there's any way to solve it? 

I kept running the command to make sure that blockSci is up to date, and the first few times everything is fine, it's only after running it several times that the error starts to occur. The machine has 60GB RAM and is no where near full capacity when I run the erring command.

```
# blocksci_parser --output-directory /home/ubuntu/bitcoin update --max-block 502264 disk --coin-directory /home/ubuntu/.bitcoin
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

And it looks like it's `bitcoin/parser/blockList.dat` causing the problem. Once I remove this file blocksci_parser will work again

**Comment by hkalodner** [comment]
Chances are that this was a compatibility issue between an old version of the parser and a newer version. Closing this unless this problem can be reproduced in the latest version.

**Comment by jredondo** [comment]
After I while with the AMI deployed and running, and after running successfully the parser many times before (including Litecoin) I'm now receiving an assertion:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./update.sh: line 3:  1748 Aborted                 (core dumped) /usr/local/bin/blocksci_parser --output-directory /home/ubuntu/bitcoin update --max-block -6 disk --coin-directory /home/ubuntu/.bitcoin

Not sure what might be wrong or how to get it running again.

It is worth noticing that removing blockList.dat file and re running the parser worked, but would like to have a clearer idea about what happened.

Any hint or comment is welcome.

Thanks in advance.

**Comment by Haaroon** [comment]
I'm having this issue running it on the latest version of the Bitcoin blockchain, I dont get any of the files mentioned above.
