### ISSUE TITLE
Find the transaction that determines the clustering of an address

### ISSUE THREAD

**Issue by jiagengliu** [citp/BlockSci#401]
Thank you for providing us with this wonderful library.

I have a question regarding clustering: I'm using the default clustering in v0.6, which I assume only uses the multi-input heuristics and ignores CoinJoin/coinbase. I wonder if there's a way to find the transaction that links two clusters? 

In particular, my clustering groups these two addresses together: 1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY and 142BHpdq4wey7PC3Cp5QiUoshF19u3yvHN. However, other online sources such as bitinfochart and walletexplorer do not put them together. I wonder if it's due to CoinJoin, but it'd be helpful if I could know which transaction to look at. Thank you!

**Comment by jiagengliu** [comment]
I manually investigated the issue. I think it's likely because BlockSci doesn't detect a CoinJoin transaction: ba31c8833b7417fec9a84536f32fcb52d432acb66d99b9be6f3899686a269b2b

**Comment by maltemoeser** [comment]
Hmm that transaction is certainly interesting :D It is not a CoinJoin though (it only aggregates inputs, but does not show characteristics of a multi-user transaction) so I think clustering the inputs is valid. That looks more like some spam or cleanup transaction, I wonder if there's some rationale there to try to detect and ignore those?

**Comment by maltemoeser** [comment]
And to answer the original question: no, the library currently doesn't allow to determine which transaction merged two clusters.

**Comment by jiagengliu** [comment]
@maltemoeser Thanks for the response! Your comment is very helpful. I thought the transaction is a CoinJoin because neither bitinfochart nor walletexplorer put 1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY and 18fmv2VksuggKMdT4X7bmhJH96v868xkuY in one cluster. It's not clear from their websites either why they don't, though. Can you point to any literature that discusses the heuristics here? I wonder if there's a way to tweak the heuristics, too.

**Comment by maltemoeser** [comment]
@jiagengliu I'll take a closer look at these addresses tomorrow and will report back :)

**Comment by maltemoeser** [comment]
After looking at some of the addresses involved, it seems like they may have had their private keys leaked (through nonce reuse, e.g., [see this paper](http://eprint.iacr.org/2013/734.pdf)). There isn't really a practical way to exclude those keys from clustering, we would need to scan all the signatures on the blockchain to determine which addresses have their private key revealed to exclude them. I probably wouldn't object to having a static list of addresses to ignore, but would want to have some understanding of what the impact is of the use of these addresses first.

**Comment by jiagengliu** [comment]
Thank you so much @maltemoeser ! I'm not particularly concerned so I'd like to go ahead and close it.
