### ISSUE TITLE
AMI unavailable.

### ISSUE THREAD

**Issue by v-borges** [citp/BlockSci#406]
Opening the [AMI ](https://console.aws.amazon.com/ec2/home?region=us-east-1#launchAmi=ami-0d0091e593d44cce1)link at the README, I got the following message at aws:

> We cannot proceed with your requested configuration. You cannot use this AMI (ami-0d0091e593d44cce1).
> This AMI has been deregistered, or you do not have permission to use it. Try again with another AMI for which you have permissions, or request permission to use this AMI from its owner.

Can someone please upload that again?

**Comment by mplattner** [comment]
We are working on an updated AMI for the latest BlockSci version, as it is stated in the readme: https://github.com/citp/BlockSci#quick-setup-using-amazon-ec2

> Note: The AMI is temporarily unavailable. We are currently working on a new version on the v0.6 development branch and will make a new AMI available soon.
