### ISSUE TITLE
Duplicated addresses in cluster.addresses

### ISSUE THREAD

**Issue by jiagengliu** [citp/BlockSci#408]
I have found cases where equivalent addresses are counted twice. I wonder if it is intentional? 

#### Reproduction Steps

```
cluster = cm.cluster_with_address(chain.address_from_string(
    '1PLvcoFj9Ek7ADP2dakggYbdPaFiuZ768t'))
cluster.addresses.to_list()
[a.equiv() for a in cluster.addresses.to_list()]
```

#### System Information

Using AMI: Yes
BlockSci version: 0.6
Blockchain: Bitcoin
Parser: Disk  
Total memory: 64 GB

**Comment by maltemoeser** [comment]
Yeah I think it is, `.addresses` will iterate through all dedup addresses and return every non-dedup address that has been seen on chain: https://github.com/citp/BlockSci/blob/v0.6/src/cluster/cluster.cpp#L85

**Comment by jiagengliu** [comment]
@maltemoeser Thank you! I got confused because of the difference between type_equiv_size and address_count.

**Comment by maltemoeser** [comment]
@jiagengliu if you're working with equiv addresses, I recently merged #402 which fixed the reverse lookup for script equivalence, e.g. from p2pk->p2sh that is used to find all equiv addresses (it wasn't correctly created before). would require a reparse to correctly build that index

**Comment by jiagengliu** [comment]
@maltemoeser Thank you so much! I only worked with clusters recently, which I assume doesn't rely on the reverse lookup? I haven't used that `.equiv()` extensively but it's definitely useful to know.

**Comment by maltemoeser** [comment]
Yep you're correct, the clusterer wasn't affected because it uses the normal/wrapped lookup (P2SH->P2PK/whatever) 👍
