### ISSUE TITLE
How can I build BlockSci on Windows?

### ISSUE THREAD

**Issue by fqjdmppc** [citp/BlockSci#41]
Amazing tool for blockchain analysis, but I want to use it with my Windows PC and Visual Studio...

**Comment by hkalodner** [comment]
BlockSci currently only has official support for Mac and Linux (The two platforms that I use). I think (though I'm not sure) that all of BlockSci's dependencies are available on windows so the code should hopefully work though I'm sure there are a number of build system hurdles.

It'd be great to be able to support BlockSci on windows, but it's unfortunately not very high on my priority list currently.

**Comment by fqjdmppc** [comment]
Thanks for your response

**Comment by ridicoulous** [comment]
@fqjdmppc Hello. Did you find a solution?

**Comment by ridicoulous** [comment]
> Sorry this is still not supported. I'd say it's probably possible with some work, but it's unfortunately not a development priority.

Sure, I understand. I hope anyone find a working solution, cause I have troubles at building via CMAKE - it can't find builded jsoncpp library despite  that I am pointing the right path to "include" folder of jsoncpp
