### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by luisalrp** [citp/BlockSci#411]
I am trying to use the graphsense export feature but I get an "IndexError" while running the script.

#### Reproduction Steps
```
import blocksci
chain = blocksci.Blockchain(args.blocksci_config)
    print('Last parsed block: %d (%s)' % (chain[-1].height, datetime.strftime(chain[-1].time, '%F %T')))
```

I run the doctor and I got the following

```
dockeruser@7049af82e1b4:~$ blocksci_parser /var/data/blocksci_data/btc.cfg doctor
374GB of free disk space available.
Warning: Open files limit of 1024 is potentially too low. This could lead to data corruption.

Checking configuration for issues.
OK: Found data directory on disk.
OK: Found disk parser settings in config.

Constructing chain index from scratch. This may take a few minutes.
100.0% done fetching block headers
OK: Most recent block found in coin directory has height 630678 (in file 2076)

Found 1 warnings and 0 errors.
Warnings may be bening, errors must be resolved for BlockSci to run.
```

#### System Information

Using AMI: AWS Linux r5.xlarge.  
BlockSci version: 0.6
Blockchain: Bitcoin
Parser: Disk
Total memory: 64 GB

**Comment by maltemoeser** [comment]
Could you show us the code that creates the problem? Might be related to the graphsense script rather than BlockSci itself?

**Comment by luisalrp** [comment]
Sure. It is in the line 355 from the script [https://github.com/graphsense/graphsense-blocksci/blob/master/scripts/blocksci_export.py].

I am reparsing the Bitcoin Blockchain to avoid possible errors. I can't see the output since i deattached from the docker instance but a ps -aux says it is still working. Will come with more detail. Thanks!

**Comment by maltemoeser** [comment]
Oh I see, yeah that error would mean your `Blockchain` object has a length of 0. Which is weird given that `doctor` can construct a full chain. If a reparse doesn't fix it, one thing that might be useful to check are the file permissions, i.e. that the location the BlockSci files are stored is readable by the user running the export script.

**Comment by luisalrp** [comment]
Thanks for your assistance @maltemoeser. After reparshing the whole chain it works perfect :D
