### ISSUE TITLE
Failed with error code 1

### ISSUE THREAD

**Issue by amukherjee1991** [citp/BlockSci#413]
I was follwing the instructions for compiling and got stuck with this error in the last step of the process as described on https://citp.github.io/BlockSci/compiling.html

`Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mb0s34od/pandas/setup.py", line 42
        f"numpy >= {min_numpy_ver}",
                                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mb0s34od/pandas/`

Any help from the community?

**Comment by amukherjee1991** [comment]
I fixed this error for now as I believe that was python version and pip version issue. However, when i run 
`CC=gcc-7 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=Release ..`
I am getting another error which was not there before.

`/home/arghya/BlockSci/src/internal/column_iterator.hpp:13:10: fatal error: range/v3/view/facade.hpp: No such file or directory
 #include <range/v3/view/facade.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/internal/CMakeFiles/blocksci_internal.dir/build.make:86: recipe for target 'src/internal/CMakeFiles/blocksci_internal.dir/address_index.cpp.o' failed
make[2]: *** [src/internal/CMakeFiles/blocksci_internal.dir/address_index.cpp.o] Error 1
CMakeFiles/Makefile2:6442: recipe for target 'src/internal/CMakeFiles/blocksci_internal.dir/all' failed
make[1]: *** [src/internal/CMakeFiles/blocksci_internal.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2`

I am clueless now!

**Comment by amukherjee1991** [comment]
After going through all the steps again I am again stuck on the last step

`ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/arghya/BlockSci/blockscipy/setup.py'"'"'; __file__='"'"'/home/arghya/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

**Comment by maltemoeser** [comment]
Could you please provide the information that was suggested in the issue template? Specifically, which OS and version of BlockSci you are using?

**Comment by amukherjee1991** [comment]
I am using Ubuntu 16.04 as per the documentation. I was usign the master and had the issue. Then I swtiched to v.06 as you adviced on the other issue.

**Comment by maltemoeser** [comment]
Looks like it doesn't find `range/v3/view/facade.hpp`, which should be in `./external/range-v3/include/range/v3/view`. From what I understand, you first compiled v0.5 and then switched to v0.6? Try running the following

```
git submodule sync
git submodule update --recursive
```

**Comment by maltemoeser** [comment]
The error in #410 shows a problem with finding a package configuration file, whereas here an import cannot be found.

**Comment by amukherjee1991** [comment]
I think I ran master, then moved to v0.6 when I saw your comment on #410. After running 

`git submodule sync
git submodule update --recursive`

I get another error,

`Running setup.py develop for blocksci
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/arghya/BlockSci/blockscipy/setup.py'"'"'; __file__='"'"'/home/arghya/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/arghya/BlockSci/blockscipy/
    Complete output (48 lines):
    running develop
    Checking .pth file support in /usr/local/lib/python3.7/dist-packages/
    /usr/bin/python3.7 -E -c pass
    TEST PASSED: /usr/local/lib/python3.7/dist-packages/ appears to support .pth files
    running egg_info
    writing blocksci.egg-info/PKG-INFO
    writing dependency_links to blocksci.egg-info/dependency_links.txt
    writing requirements to blocksci.egg-info/requires.txt
    writing top-level names to blocksci.egg-info/top_level.txt
    reading manifest file 'blocksci.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'blocksci/templateMakefile'
    warning: no files found matching 'blocksci/filterTxesExtension.cpp'
    warning: no files found matching '*' under directory 'blocksci/pybind11/'
    writing manifest file 'blocksci.egg-info/SOURCES.txt'
    running build_ext
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
      CMake 3.8.2 or higher is required.  You are running version 3.5.1


    -- Configuring incomplete, errors occurred!
    See also "/home/arghya/BlockSci/blockscipy/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    See also "/home/arghya/BlockSci/blockscipy/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/arghya/BlockSci/blockscipy/setup.py", line 77, in <module>
        'requests>=2.19.1'
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 119, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/arghya/BlockSci/blockscipy/setup.py", line 32, in run
        self.build_extension(ext)
      File "/home/arghya/BlockSci/blockscipy/setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/arghya/BlockSci/blockscipy', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/arghya/BlockSci/blockscipy/blocksci', '-DPYTHON_EXECUTABLE=/usr/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/arghya/BlockSci/blockscipy/setup.py'"'"'; __file__='"'"'/home/arghya/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

**Comment by maltemoeser** [comment]
Hmm looks like you need a newer version of [CMake](https://cmake.org/download/)

```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.8.2 or higher is required. You are running version 3.5.1
```

There are also warnings that probably are coming from your first attempt to compile the 0.5 version (such as `warning: no files found matching 'blocksci/filterTxesExtension.cpp'`), I'd suggest to remove the `blockscipy/build` folder to get rid of the old build.

**Comment by amukherjee1991** [comment]
It worked finally. Thanks!

**Comment by maltemoeser** [comment]
Great to hear!
