### ISSUE TITLE
blokcsci_parser not working as intended

### ISSUE THREAD

**Issue by shiroi-tora** [citp/BlockSci#418]
I am using PIVX cryptocurrency version pivx-4.1.1. Also, I am using to work on blockchain. But blocksci_parser is not working. 

I am using this code:
`sudo blocksci_parser --output-directory pivxChain update --max-block -100 rpc --username <myID> --password <myPW>--address 127.0.0.1 --port 8332`

It was working before but now I always get this:

`SYNOPSIS
        blocksci_parser <config file> generate-config <coin type> <data directory> [--max-block <max block>] [--disk <coin directory>] [--rpc <username> <password> [--address <address>] [--port <port>]]
        blocksci_parser <config file> update
        blocksci_parser <config file> core-update
        blocksci_parser <config file> index-update
        blocksci_parser <config file> address-index-update
        blocksci_parser <config file> hash-index-update
        blocksci_parser <config file> compact-indexes
        blocksci_parser <config file> doctor

OPTIONS
        <config file>
                    Path to config file

        generate-config
                    Create new BlockSci configuration

        Configuration options
            <coin type>
                    coin type (supported modes)
                        bitcoin(disk, rpc)
                        bitcoin_testnet(disk, rpc)
                        bitcoin_regtest(disk, rpc)
                        bitcoin_cash(disk, rpc)
                        bitcoin_cash_testnet(disk, rpc)
                        bitcoin_cash_regtest(disk, rpc)
                        litecoin(disk, rpc)
                        litecoin_testnet(disk, rpc)
                        litecoin_regtest(disk, rpc)
                        dash(rpc)
                        dash_testnet(rpc)
                        namecoin(rpc)
                        namecoin_testnet(rpc)
                        zcash(rpc)
                        zcash_testnet(rpc)
                        custom

            <data directory>
                    Path to blocksci data location

            --max-block, -m <max block>
                    Max block height to scan up to

            File parser options
                <coin directory>
                    Path to cryptocurrency directory

            RPC options
                <username>
                    RPC username

                <password>
                    RPC password

                --address <address>
                    RPC address

                --port <port>
                    RPC port

        update      Update all BlockSci data
        core-update Update just the core BlockSci data (excluding indexes)

        index-update
                    Update indexes to latest chain state

        address-index-update
                    Update address index to latest state

        hash-index-update
                    Update hash index to latest state

        compact-indexes
                    Compact indexes to speed up blockchain construction

        doctor      Diagnose issues with BlockSci or the provided config file.`

I am using Linux / Ubuntu.

**Comment by jptbrandao** [comment]
Are you using v0.6? If you are, the syntax has changed:

Check out https://github.com/citp/BlockSci/wiki#toc-dev-parser-syntax . Hope it helps.

**Comment by shiroi-tora** [comment]
It worked, I have always used documentation here: [https://citp.github.io/BlockSci/](https://citp.github.io/BlockSci/), so didn't knew I was downloading v0.6. 

Thanks.
