### ISSUE TITLE
method argument bug

### ISSUE THREAD

**Issue by yya518** [citp/BlockSci#423]
https://github.com/citp/BlockSci/blob/7572f18911aa2068cdd914522bb872808894c857/blockscipy/blocksci/__init__.py#L756

should be 
`def outputs_spent_after_height(outputs, height):`

instead of 
`def outputs_spent_after_height(outputs, age):`

Thanks for the great library by the way.

**Comment by maltemoeser** [comment]
Thank you, fixed in 9b42885b04a763974a0e5e3c7be84029a10cbc8e
