### ISSUE TITLE
Blocksci_parser generate-config returns nothing

### ISSUE THREAD

**Issue by Kindhearted57** [citp/BlockSci#424]
#### System Information (if applicable)
Ubuntu 16.04
Using AMI: no
BlockSci version: v0.6
Blockchain: Bitcoin 
Parser: Disk
Total memory: 338GB (/var/data/block_data)

```
blocksci_parser /var/data/blocksci_data/btc.cfg generate-config bitcoin /var/data/blocksci_data --max-block '-6' --disk /var/data/block_data
```

didn't return an error information, at the same time, there is no btc.cfg under blocksci_data.
I have no clue about why...

**Comment by Kindhearted57** [comment]
Ok, I've learned from [this page](https://github.com/citp/BlockSci/blob/31ca093750aa454877617bdf5b46ab27fce87989/docs/setup.rst) that BlockSci requires at least 60GB of RAM to parse the Bitcoin blockchain now, so I guess this is what caused my problem.

**Comment by maltemoeser** [comment]
Generating the config file shouldn't depend on the memory available (it's just writing a `.json` file). Did you double-check that the file permissions allow the parser to write the config file?

**Comment by Kindhearted57** [comment]
I have checked the file permission and it turns out that's exactly where the problem comes in! Thanks~
However, maybe there should be some error information returned to make it easier to find out what caused the problem?🧐

**Comment by kakarottocheng** [comment]
I have the same issue, I wonder how I should fill out the parameters to generate the config file?

**Comment by ww3113306** [comment]
I have the same issue. And I have checked the file permission and I used
`sudo chmod 777`
to change it. But I still have the same issue.
