### ISSUE TITLE
v0.6 documentation

### ISSUE THREAD

**Issue by saravana87** [citp/BlockSci#426]
Hi,
I installed the new v0.6 and started blocksci parser.
I tried to use the following code
chain = blocksci.Blockchain("/parser/bitcoin/bitcoin-data/btc.json")
print(chain[43])
blocks = chain.range('2010-07-1')

it throwing
IndexError: single positional indexer is out-of-bounds

If there are changes in the classes and functions please let me know where I can read it.

#### System Information (if applicable)
Using AMI: yes/no  
BlockSci version: (please provide a commit id if you're on a development branch)  
Blockchain: (e.g., Bitcoin, Bitcoin Cash, Litecoin)  
Parser: Disk/RPC  
Total memory: XX GB

**Comment by jiagengliu** [comment]
Hi, I think they have released v0.7, and the doc is here: https://citp.github.io/BlockSci/index.html

**Comment by saravana87** [comment]
Yes thank you
