### ISSUE TITLE
Use virtual size instead of raw size

### ISSUE THREAD

**Issue by jnewbery** [citp/BlockSci#43]
Since segwit was activated at block 494,784, the limiting resource on block space is 'weight', which is defined in [BIP 141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki) as:

> Block weight is defined as Base size * 3 + Total size. (rationale[3])
> 
> Base size is the block size in bytes with the original transaction serialization without any witness-related data, as seen by a non-upgraded node.
> 
> Total size is the block size in bytes with transactions serialized as described in BIP144, including base data and witness data.

For fee market analysis, the relevant metric is transaction weight (Base transaction size * 3 + Total transaction size), which can be normalized to *virtual size* (Transaction weight / 4). This is because miners will order transactions by fee/virtual byte to maximize the fee yield from a block.

For transactions without any segwit inputs, virtual size is the same as size.

BlockSci should therefore store the *tx virtual size* instead of *tx size*. Virtual size is exposed in the `getrawtransaction` and `getblock` (with verbosity=2) RPC methods as `vsize`.

**Comment by hkalodner** [comment]
Good catch, this is definitely a segwit support issue. I think the answer is to record both the real size and the virtual size since they are both useful quantities. Both should be able to fit in the current data format without any major changes. I'll slot this for the next major release.

**Comment by jnewbery** [comment]
Great. I'm happy to review/test once you have something.

**Comment by hkalodner** [comment]
This is now resolved in BlockSci v0.4

**Comment by jnewbery** [comment]
Thanks @hkalodner 

(for reference, I believe this is the change: https://github.com/citp/BlockSci/pull/58/commits/7b78aba5a2bd6157b2397a430cc6901bdc36fcfe#diff-8eea305b6ac0a8dacd8fea0778fd383fR63)
