### ISSUE TITLE
Clustering with change.none.unique_change raises TypeError Pythonm

### ISSUE THREAD

**Issue by Haaroon** [citp/BlockSci#440]
Please provide a clear and concise description of the problem.

#### Reproduction Steps

```
import blocksci
_cfg = '/home/ubuntu/blocksci.cfg'
print("Loading blocksci chain...")
chain = blocksci.Blockchain(_cfg)
heuristic = blocksci.heuristics.change.none.unique_change()
cm = blocksci.cluster.ClusterManager.create_clustering('/home/ubuntu/blocksci_unique_change_clustering', chain, heuristic, should_overwrite=True, ignore_coinjoin=True)
```

#### System Information

Using AMI: no  
BlockSci version: 0.7  
Blockchain: Bitcoin 
Parser: Disk  
Total memory: 128 GB  

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/7131194/97619224-da103f80-1a17-11eb-8045-f0ab2a539ad7.png">

**Comment by Haaroon** [comment]
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/7131194/97619395-18a5fa00-1a18-11eb-9ce3-c466ef1c4712.png">

**Comment by maltemoeser** [comment]
I think it requires you to specify the keyword, i.e. `heuristic=heuristic`

**Comment by Haaroon** [comment]
Ah perfect, that fixed it. 

For the record

`cm = blocksci.cluster.ClusterManager.create_clustering('/home/ubuntu/blocksci_unique_change_clustering', chain=chain, heuristic=blocksci.heuristics.change.none.unique_change, should_overwrite=True,ignore_coinjoin=True)` did the trick
