### ISSUE TITLE
blocksci_cluster gives incorrect address output 

### ISSUE THREAD

**Issue by Haaroon** [citp/BlockSci#441]
Output of addresses from cluster (after using blocksci_clusterer) is invalid.

#### Reproduction Steps
First make the cluster
```
cd /opt/scripts
blocksci_clusterer "/var/data/blocksci_data/btc.cfg" blocksci_clusters
```

Next test it with a random address
```
import blocksci
chain = blocksci.Blockchain('/var/data/blocksci_data/btc.cfg')
cm = blocksci.cluster.ClusterManager("/home/ubuntu/blocksci_cluster/", chain)
addr = chain.address_from_string('37pHXf3AtpJeu2GkaUY33WZkFPpeRPrZgr')
addr_cluster = cm.cluster_with_address(addr)
cluster_addrs = list(addr_cluster.addresses)
cluster_addrs[0] // Gives a broken output
```
<img width="889" alt="image" src="https://user-images.githubusercontent.com/7131194/97878900-26f55e00-1d17-11eb-90b5-ae0dda42cdcc.png">

#### System Information

Using AMI: no  
BlockSci version: 0.7 
Blockchain: Bitcoin
Parser: Disk
Total memory: 128 GB

**Comment by Haaroon** [comment]
Temporarily i have found a bypass by instead calling the intxes, converting that to string and cleaning the result ,here is the code incase anyone has this issue

```
in_txs = addr_cluster.input_txes()
cluster_address_strings = set([])
c=0
for tx in in_txs:
    c+=1
    if c % 10000 == 0:
        print('%i/%i' % (c, len(in_txes))
    for inx in tx.inputs:
        cluster_address_strings.add(str(inx.address))
cleaned = set([])
for a in cluster_address_strings: 
    cleaned.add(a.split('(')[1].split(')')[0].split(',')[0])
```

**Comment by maltemoeser** [comment]
Try using `addresses.to_list()` instead of `list(addresses)` (#273, #296)

**Comment by Haaroon** [comment]
perfect, fixed
