### ISSUE TITLE
BlockSci always returns empty lists, no matter which function I call

### ISSUE THREAD

**Issue by alex-btc** [citp/BlockSci#465]
I successfully installed BlockSci in Ubuntu 18.04 and parsed the bitcoin blockchain until block 400.000 (put a limit on config file just to test the library, before parsing the whole thing).

But when I call any function, it just returns an empty list as a result.

For example:

```
import blocksci
chain = blocksci.Blockchain('/home/my_username/BlockSci/config.conf')
anomalous_fee = [tx for block in chain for tx in block if tx.fee > 1e7] # return []
blocks = chain.range('2011') # return []
heights = [block.height for block in chain] # return []
```
In the case above, the value returned to anomalous_fee, blocks and heights is just an empty list.

Any insight on what might be happening?

System Information

Using AMI: no
BlockSci version: 0.7
Blockchain: Bitcoin
Parser: Disk
Total memory: 128 GB

**Comment by kakarottocheng** [comment]
Hi, I installed BlockSci on Ubuntu 18.04, too. I wonder how should I fill out the parameters in "blocksci_parser <config file> generate-config <coin type> <blocksci data directory> [--max-block <max block>] [--disk <fullnode data directory>] [--rpc <username> <password> [--address <address>] [--port <port>]]" to generate the config file? Thank you!

**Comment by alex-btc** [comment]
I was able to successfully parse the chain using the bitcoin RPC interface, instead of reading it from disk.

I did a small test, only to block 100000, and it worked. Now I will parse the whole thing.

**Comment by kakarottocheng** [comment]
Thank you for your reply! I wonder how you filled out the parameters for "blocksci_parser generate-config [--max-block ] [--disk ] [--rpc [--address] [--port ]]" ? I am having a trouble to generate the config file.
