### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dfogaras** [citp/BlockSci#49]
Thanks a lot for creating BlockSci. I'm following the local setup on a new ubuntu 16.04 and I got the error below. Do you have any advice?
Thanks,
Daniel

`ubuntu@ip-172-31-24-144:~/BlockSci/release$ sudo make install
[ 36%] Built target blocksci_static
[ 72%] Built target blocksci
[ 89%] Built target blocksci_parser
[ 91%] Built target mempool_recorder
[ 92%] Building CXX object src/python-interface/CMakeFiles/blocksci_interface.dir/output_py.cpp.o
In file included from /home/ubuntu/BlockSci/libs/range-v3/include/range/v3/view_facade.hpp:21:0,
                 from /home/ubuntu/BlockSci/src/blocksci/util/file_mapper.hpp:17,
                 from /home/ubuntu/BlockSci/src/blocksci/chain/chain_access.hpp:16,
                 from /home/ubuntu/BlockSci/src/blocksci/chain/output.hpp:14,
                 from /home/ubuntu/BlockSci/src/blocksci/chain/transaction.hpp:13,
                 from /home/ubuntu/BlockSci/src/blocksci/chain/block.hpp:13,
                 from /home/ubuntu/BlockSci/src/python-interface/ranges_py.hpp:11,
                 from /home/ubuntu/BlockSci/src/python-interface/output_py.cpp:9:
/home/ubuntu/BlockSci/libs/range-v3/include/range/v3/view_interface.hpp: In substitution of 'template<class Container, class D, class, int _concept_requires_341, typename std::enable_if<((_concept_requires_341 == 43) || std::is_same<std::integer_sequence<bool, typename ranges::v3::concepts::models<ranges::v3::concepts::Range, T>::type:: value, typename std::integral_constant<bool, (! typename ranges::v3::concepts::models<ranges::v3::concepts::View, T>::type:: value)>::type:: value, typename ranges::v3::concepts::models<ranges::v3::concepts::MoveConstructible, T>::type:: value, typename ranges::v3::concepts::models<ranges::v3::concepts::ConvertibleTo, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>()))>::type, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<T&>()))>::type>::type:: value, typename ranges::v3::concepts::models<ranges::v3::concepts::Constructible, Container, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type>::type:: value>, std::integer_sequence<bool, (typename ranges::v3::concepts::models<ranges::v3::concepts::Range, T>::type:: value || true), (typename std::integral_constant<bool, (! typename ranges::v3::concepts::models<ranges::v3::concepts::View, T>::type:: value)>::type:: value || true), (typename ranges::v3::concepts::models<ranges::v3::concepts::MoveConstructible, T>::type:: value || true), (typename ranges::v3::concepts::models<ranges::v3::concepts::ConvertibleTo, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>()))>::type, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<T&>()))>::type>::type:: value || true), (typename ranges::v3::concepts::models<ranges::v3::concepts::Constructible, Container, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type>::type:: value || true)> >()), int>::type <anonymous> > ranges::v3::view_interface<Derived, <anonymous> >::operator Container() const [with Container = auto:3; D = ranges::v3::any_view<blocksci::Output>; <template-parameter-1-3> = <missing>; int _concept_requires_341 = <missing>; typename std::enable_if<((_concept_requires_341 == 43) || std::is_same<std::integer_sequence<bool, typename ranges::v3::concepts::models<ranges::v3::concepts::Range, T>::type:: value, typename std::integral_constant<bool, (! typename ranges::v3::concepts::models<ranges::v3::concepts::View, T>::type:: value)>::type:: value, typename ranges::v3::concepts::models<ranges::v3::concepts::MoveConstructible, T>::type:: value, typename ranges::v3::concepts::models<ranges::v3::concepts::ConvertibleTo, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>()))>::type, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<T&>()))>::type>::type:: value, typename ranges::v3::concepts::models<ranges::v3::concepts::Constructible, Container, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type>::type:: value>, std::integer_sequence<bool, (typename ranges::v3::concepts::models<ranges::v3::concepts::Range, T>::type:: value || true), (typename std::integral_constant<bool, (! typename ranges::v3::concepts::models<ranges::v3::concepts::View, T>::type:: value)>::type:: value || true), (typename ranges::v3::concepts::models<ranges::v3::concepts::MoveConstructible, T>::type:: value || true), (typename ranges::v3::concepts::models<ranges::v3::concepts::ConvertibleTo, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>()))>::type, typename ranges::v3::value_type<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<T&>()))>::type>::type:: value || true), (typename ranges::v3::concepts::models<ranges::v3::concepts::Constructible, Container, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type, typename meta::v1::detail::_if_<meta::v1::list<std::is_same<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))>, decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), ranges::v3::_common_iterator_::common_iterator<decltype (ranges::v3::function_objects::{anonymous}::begin(declval<const D&>())), decltype (ranges::v3::function_objects::{anonymous}::end(declval<const D&>()))> >, std::integral_constant<bool, true> >::type>::type:: value || true)> >()), int>::type <anonymous> = <missing>]':
/home/ubuntu/BlockSci/src/python-interface/output_py.cpp:141:20:   required from 'init_output(pybind11::module&)::<lambda(auto:13&&, auto:14)> [with auto:13 = ranges::v3::any_view<blocksci::Output>&; auto:14 = addOutputRangeMethods(Class&, FuncApplication)::<lambda(Range&)> [with Class = pybind11::class_<ranges::v3::any_view<blocksci::Output> >; FuncApplication = init_output(pybind11::module&)::<lambda(auto:13&&, auto:14)>; Range = ranges::v3::any_view<blocksci::Output>]::<lambda(auto:3&&)>]'
/home/ubuntu/BlockSci/src/python-interface/output_py.cpp:63:20:   required from 'addOutputRangeMethods(Class&, FuncApplication)::<lambda(Range&)> [with Class = pybind11::class_<ranges::v3::any_view<blocksci::Output> >; FuncApplication = init_output(pybind11::module&)::<lambda(auto:13&&, auto:14)>; Range = ranges::v3::any_view<blocksci::Output>]'
/home/ubuntu/BlockSci/src/python-interface/output_py.cpp:63:16:   required from 'struct addOutputRangeMethods(Class&, FuncApplication) [with Class = pybind11::class_<ranges::v3::any_view<blocksci::Output> >; FuncApplication = init_output(pybind11::module&)::<lambda(auto:13&&, auto:14)>]::<lambda(using Range = using type = struct ranges::v3::any_view<blocksci::Output>&)>'
/home/ubuntu/BlockSci/src/python-interface/output_py.cpp:61:5:   required from 'void addOutputRangeMethods(Class&, FuncApplication) [with Class = pybind11::class_<ranges::v3::any_view<blocksci::Output> >; FuncApplication = init_output(pybind11::module&)::<lambda(auto:13&&, auto:14)>]'
/home/ubuntu/BlockSci/src/python-interface/output_py.cpp:142:6:   required from here
/home/ubuntu/BlockSci/libs/range-v3/include/range/v3/view_interface.hpp:340:17: internal compiler error: in dependent_type_p, at cp/pt.c:21233
                 typename = typename Container::allocator_type, // HACKHACK
                 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/python-interface/CMakeFiles/blocksci_interface.dir/build.make:206: recipe for target 'src/python-interface/CMakeFiles/blocksci_interface.dir/output_py.cpp.o' failed
make[2]: *** [src/python-interface/CMakeFiles/blocksci_interface.dir/output_py.cpp.o] Error 1
CMakeFiles/Makefile2:393: recipe for target 'src/python-interface/CMakeFiles/blocksci_interface.dir/all' failed
make[1]: *** [src/python-interface/CMakeFiles/blocksci_interface.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
ubuntu@ip-172-31-24-144:~/BlockSci/release$`

**Comment by cabrenn** [comment]
Just letting you know, that I am having the exact same issue using same OS.

**Comment by dfogaras** [comment]
Most likely, I mistakenly used gcc-5, but a properly executed "Local setup" would use gcc-7.
