### ISSUE TITLE
Error using filter_txes() method on the BlockSci AMI

### ISSUE THREAD

**Issue by jkrol21** [citp/BlockSci#50]
Hello when I tried to use the filter_txes() method but ran into an error.
Do I have a bug in my code or is it a BlockSci issue?
Seems to me that the tx_with_index() method has been deleted in BlockSci version 0.3.

![grafik](https://user-images.githubusercontent.com/33954554/35538452-350e39a0-054e-11e8-8106-5bd7f1e2b658.png)

**Comment by hkalodner** [comment]
Good catch. I just fixed this in master and I'll update the AMI.

**Comment by polac** [comment]
Hi @hkalodner, I proposed fix for this in #57. 

Your way of fixing the problem causes at least for me the following error:

> ~/BlockSci/Notebooks/blocksci/__init__.py in filter_txes(self, filterFunc, start, end, cpu_count)
>      85     init = list()
>      86     tx_ids = mapreduce_block_ranges(self, mapFunc, reduceFunc, init, start, end, cpu_count)
> ---> 87     return [Tx(x) for x in tx_ids]
>      88 
>      89 Blockchain.map_blocks = map_blocks
> 
> ~/BlockSci/Notebooks/blocksci/__init__.py in <listcomp>(.0)
>      85     init = list()
>      86     tx_ids = mapreduce_block_ranges(self, mapFunc, reduceFunc, init, start, end, cpu_count)
> ---> 87     return [Tx(x) for x in tx_ids]
>      88 
>      89 Blockchain.map_blocks = map_blocks
> 
> TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
>     1. blocksci.blocksci_interface.Tx(arg0: int)
>     2. blocksci.blocksci_interface.Tx(arg0: str)
> 
> Invoked with: []

**Comment by hkalodner** [comment]
Ah there was actually a second bug which should be fixed in our next release which should be coming out shortly.
