### ISSUE TITLE
Segmentation fault after running clustering tool

### ISSUE THREAD

**Issue by totalslacker** [citp/BlockSci#52]
I tried rebuilding the clusters and now I get a segmentation fault when I call the python cluster_with_address method.

This was working before rebuilding the clusters. Afterwards the following script:

import blocksci
from blocksci import *
import blocksci.cluster_python

chain = blocksci.Blockchain("/home/ubuntu/bitcoin/")
print(chain)
print("loading clusters\n")
cm = blocksci.cluster_python.ClusterManager("/home/ubuntu/bitcoin/clusters")
print(cm)

address = blocksci.Address.from_string("15rg7dmf9PS6dPdne3F816rKLmDsDNxex9")
print(address)
print(address.out_txes()[0].hash)
print("Loading cluster")
cluster = cm.cluster_with_address(address)

causes a segmentation fault:

<blocksci.blocksci_interface.Blockchain object at 0x7f1cde3fbeb8>
loading clusters

<blocksci.cluster_python.ClusterManager object at 0x7f1cfcd5d500>
Address(addressNum=52075814, type=pubkeyhash)
b35744527be738a9f2dc01e61d3e2268e7f76a4a770d725dce73635acbf524da
Loading cluster
Segmentation fault (core dumped)

I have also tried deleting the bitcoin data directory, along with a fresh checkout of BlockSci (master branch), rebuilding all tools and rebuilding the bitcoin data directory. Same result.

Copying the original *.dat files back in the bitcoin/clusters directory also crashes. So, it would seem reasonable that it's something else causing the issue.

Is this a known issue? What might I do to debug this?

**Comment by Husam92** [comment]
I am getting exactly same error after updating to the latest version

**Comment by hkalodner** [comment]
This is fixed in the latest update. The trailing slash was required in the ClusterManager constructor, but this is no longer true.
