### ISSUE TITLE
blocksci_parser can't interpret zcash blocks

### ISSUE THREAD

**Issue by wangbx66** [citp/BlockSci#54]
I tried 

```
./BlockSci/release/bin/blocksci_parser --output-directory chain-data update disk --coin-directory .zcash
```

but it ends up showing

```
Starting with chain of 0 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
...
```

It's like blocksci is not recognizing the zcash blockchain on my computer. I tried replacing .zcash folder with .litecoin and it works perfectly well. I read the page saying blocksci is supporting zcash, am I misunderstanding something?

Thank you

**Comment by hkalodner** [comment]
Zcash is only supported using the RPC parser, not the disk parser.
