### ISSUE TITLE
Obtain list of transactions

### ISSUE THREAD

**Issue by diamondduck** [citp/BlockSci#6]
Hello, 
I was trying to figure out how BlockSci works, but I was not able to obtain list of transaction for a given address num. 
```
add_num = 10000
address = blocksci.Address(add_num, blocksci.address_type.pubkeyhash)

```
But:
`
address.txes()`

keeps giving me an empty list.

**Comment by hkalodner** [comment]
I'll take a look and verify this, but there's a good chance that this is a bug in the initial release which will be resolved in the next version which will be released soon. The lookup from addresses to transactions they're involved in was a late addition and it still under development. The much more stable interface is going from transaction outputs to addresses. In the mean time while this is being fixed you could instead iterate over all outputs and check if they are sent to the address in question.

**Comment by hturki** [comment]
Can also confirm that I'm running into this on develop:

![image](https://user-images.githubusercontent.com/868618/32422686-a5b363f0-c26f-11e7-8f08-815bfe0f0b61.png)

**Comment by alexbuechel** [comment]
Hi guys,

This issue is about 2 months old, so i just wanna ask if there is already a solution for this bug? 
We ran into the same issue...

Thank a lot
Alex
