### ISSUE TITLE
blocksci_parser complains about missing config.ini upon very first run

### ISSUE THREAD

**Issue by danpape** [citp/BlockSci#63]
Hi, cloned the source yesterday, and trying to run the parser on my testnet3 directory, but blocksci_parser errors out with "Error, data directory does not contain config.ini. Are you sure "/data/blocksci/bitcoin-data" was the output directory of blocksci_parser?"  This is the very first time I've run blocksci_parser. Creating an empty 'config.ini' doesn't help, I get "Error, parser data is not in the correct format. To fix you must delete the data file and rerun the parser" in that case. 

Is there a base 'config.ini' I should try using, or should blocksci_parser create one for me?

**Comment by hkalodner** [comment]
Whoops sorry this was a regression created by faef367.
I'll fix this tomorrow.

**Comment by ypsilon94** [comment]
Same problem here!

**Comment by yiwesi** [comment]
Yep, I have this problem also.

**Comment by innarliiv** [comment]
Thanks, it's working now!

**Comment by vdidonato** [comment]
As of today this is still a problem for me

**Comment by maltemoeser** [comment]
@kepler16bv hmm this issue should have long been resolved. I'd suggest to open a new bug report with your specific issue and details about your setup
