### ISSUE TITLE
run clusterer & 'blocksci.cluster_python'

### ISSUE THREAD

**Issue by snmsc** [citp/BlockSci#71]
Hi, Thanks for all the work you guys are putting in! I'm running a local installation of the latest BlockSci version and parsed the Bitcoin blockchain. I have a dataframe that contains transaction level information, but I'm struggling to get the clusters. Running 

$ clusterer /home/user/bitcoin-data

as in issue #61, just gives

clusterer: command not found

and in the example Notebook

import blocksci.cluster_python

just returns

ImportError: No module named 'blocksci.cluster_python'

How do I get the clusters? Did I miss this in the documentation?

**Comment by hkalodner** [comment]
Hi @snmsc, the clustering module is not fully documented yet.

The relevant code exists in the `clustering` folder located in the base of the repo. 
A similar install process to installing BlockSci itself should work.
```
cd clustering
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
```

That should leave clusterer installed on your system and the blocksci.cluster_python package installed alongside the main blocksci python module.

**Comment by snmsc** [comment]
Hi, thanks for the fast response! It installed but when running

$ clusterer /home/user/bitcoin-data

after about 20 minutes I get 

terminate called after throwing an instance of 'std::invalid_argument'
what(): combination of enum values is not valid
Aborted (core dumped)

also when running 

cluster = cm.cluster_with_address(address)

from the example Notebook, my kernel keeps dying.

So I'm now setting up a new virtual machine and go through all the steps from the beginning.
I'll report back whether I get it running...

**Comment by hkalodner** [comment]
Hmm. Are you running the latest version of BlockSci? I'd start by updating from master and then reinstalling first BlockSci and then the clusterer.

If the `clusterer` does not complete correctly that would certainly lead to crashes trying to use the Cluster module.

**Comment by snmsc** [comment]
With the new installation it works like a charm!
The clusterer finishes orderly and I can call the cluster methods. No idea what caused the issue...

Thanks for your help!

**Comment by ishitadaga** [comment]
when i run this command:
blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin

I get the following output:
Starting with chain of 0 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
Updating address index
Updating index with scripts of type multisig_script

Why is it not adding any new blocks?

**Comment by maltemoeser** [comment]
@ishitadaga please open a separate issue since it doesn't seem related to this issue
