### ISSUE TITLE
CMake file through Demo + dynamicCode5

### ISSUE THREAD

**Issue by ypsilon94** [citp/BlockSci#72]
Hi everyone,
I'm trying to launch the demo provided; unfortunately, I found a CMake Error, that you'll find in the following, I tried to find the file to correct it but I didn't manage to. Could you help me? 

The error:
At the step: Transactions Paying over 1000 dollars in fees
Line: %time high_fee_txes = chain.cpp.filter_tx("fee(tx) > 10000000", 0, len(chain))
Error: CMake Error at CMakeLists.txt:38 (add_subdirectory):
  add_subdirectory given source "/home/ubuntu/BlockSci/libs/pybind11" which
  is not an existing directory.  **( <-- here the problem is quite stupid, the path is just "/home/salvatore/BlockSci/libs/pybind11" but I can't find where to correct it )**

CMake Error at CMakeLists.txt:42 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module". **( <-- I think it will be solved after the first)**

make: *** No targets specified and no makefile found.  Stop.

make: *** No rule to make target 'install'.  Stop.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<timed exec> in <module>()

~/BlockSci/Notebooks/blocksci/__init__.py in filter_tx(self, code, start, end)
    225             filled_template = template.safe_substitute({"module_name":module_name, "func_def" : code})
    226             makefile = self.create_makefile(module_name)
--> 227             func = self.build_function(filled_template, makefile, module_name)
    228             self.saved_tx_filters[code] = func
    229         return self.saved_tx_filters[code](self.chain, start, end)

~/BlockSci/Notebooks/blocksci/__init__.py in build_function(self, full_code, makefile, module_name)
    252         out, err = process.communicate()
    253         print(err.decode('utf8'))
--> 254         mod = importlib.import_module(module_name)
    255         return getattr(mod, "func")

/usr/lib/python3.5/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.5/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ImportError: No module named 'dynamicCode5' **( <-- Do I have to import it? )**

Thank you very much for your help!

**Comment by hkalodner** [comment]
Hey @ypsilon94,

Whoops the problem is that the path is hardcoded in BlockSci/Notebooks/blocksci/templateMakefile.

I'm working on a fix to this.

**Comment by rihanagosh08** [comment]
CMake Error at python/openpose/CMakeLists.txt:6 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module"..please give the solution for this

**Comment by maltemoeser** [comment]
@rihanagosh08 your problem does not seem related to BlockSci. If you have an issue related to BlockSci, please open a new issue
