### ISSUE TITLE
Not all blocks parsed

### ISSUE THREAD

**Issue by nomeata** [citp/BlockSci#73]
It seems that BlockSci does not reliably index all transactions. For example, [this transaction](https://blockexplorer.com/tx/b83f3c690163517aa32d8ff3524acf87cc6f344595f642674c0733876f079642) is found using
```
$ bitcoin-cli b83f3c690163517aa32d8ff3524acf87cc6f344595f642674c0733876f079642
{
  "txid": "b83f3c690163517aa32d8ff3524acf87cc6f344595f642674c0733876f079642",
  "hash": "b83f3c690163517aa32d8ff3524acf87cc6f344595f642674c0733876f079642",
  "version": 1,
…
```
but not using
```
>>> import blocksci
>>> chain = blocksci.Blockchain("…")
>>> chain.tx_with_hash('b83f3c690163517aa32d8ff3524acf87cc6f344595f642674c0733876f079642')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No Match for hash
```

I created the index using
```
./blocksci_parser --output-directory …/blocksci update disk --coin-directory …/bitcoin/datadir
```
and the parser finished successfully.

There are more transactions affected, but I could not yet detect a pattern. It is not the case that it simply ignores all transaction with nulldata output, as [transactions like this](https://blockexplorer.com/tx/d29c9c0e8e4d2a9790922af73f0b8d51f0bd4bb19940d9cf910ead8fbe85bc9b) are found just fine.

**Comment by hkalodner** [comment]
Looking up that particular transaction works fine on my installation. I'll do a full test and see if there are any txids missing. Is anyone else hitting this problem?

I'm not sure what would be causing this. The code to generate the tx hash index is pretty straightforward. I'm guessing a reinstallation would fix your problem, but that's not a very satisfying answer.

**Comment by nomeata** [comment]
Thanks for checking so quickly. So it is a local problem of sorts? That’s weird.

Does it matter to BlockSci whether the `bitcoind` whose data directory `BlockSci` parses, is called with `-txindex`?

**Comment by nomeata** [comment]
A stab in the dark: I am re-building the BlockSci index using the `rpc` rather than the `disk` method. Once that is done I will report back if it made a difference.

**Comment by nomeata** [comment]
Hmm, loading the whole bitcoin chain using `rpc` will take a few days, it seems…

Is there anything else I can try to debug? I tried to load elements related to the missing transaction, but they are all missing: 
 * `chain.address_from_string('1BjxLkPF1biMgBdwyzwvaW5ZNUaUYQjWWD')` is `None`
 * the previous transaction, `chain.tx_with_hash('41c8460b28e30a2546eccbeb896e9470aa3d7c3b69c2f337689aa284eb2d1617')`, is also `None`
 * and `chain[367578]` throws an `IndexError`. 367578 is the height of the block containing this transaction, according to https://blockexplorer.com/block/0000000000000000004ac6df6a44bae938d717b55f205f4266d59e98c0d21a11. Is this the correct way of looking up a block with BlockSci? If so, it looks like the whole block is missing… any guess why that would happen?

**Comment by nomeata** [comment]
Ok, reparsing fixed it. Sorry for the noise!

**Comment by Haaroon** [comment]
i had the same issue, for me it was when the txes were not all properly indexed on the machine, pretty annoying but hey the solution was to reindex the blockchain then to reparse the entire chain,

**Comment by nomeata** [comment]
I am reparsing again, but I am running into #100 it seems :(
