### ISSUE TITLE
filter_txes doesn't seems to work

### ISSUE THREAD

**Issue by salvp** [citp/BlockSci#74]
Hi.
We are trying to  use this function to obtain a transaction's subset

There is an example:
chain.filter_txes(filterFunc = lambda x : x.fee >= 100, start=0, end=len(chain), cpu_count=8) 

We receive this error:

NameError                                 Traceback (most recent call last)
<ipython-input-4-a15a2f5b2e79> in <module>()
----> 1 print(chain.filter_txes(filterFunc= lambda x : x.input_count > 2,start= 500000, end = len(chain), cpu_count=8).hash)

~/BlockSci/Notebooks/blocksci/__init__.py in filter_txes(self, filterFunc, start, end, cpu_count)
     95     init = list()
     96     tx_ids = mapreduce_block_ranges(self, mapFunc, reduceFunc, init, start, end, cpu_count)
---> 97     return [chain.tx_with_index(x) for x in tx_ids]
     98 
     99 Blockchain.map_blocks = map_blocks

~/BlockSci/Notebooks/blocksci/__init__.py in <listcomp>(.0)
     95     init = list()
     96     tx_ids = mapreduce_block_ranges(self, mapFunc, reduceFunc, init, start, end, cpu_count)
---> 97     return [chain.tx_with_index(x) for x in tx_ids]
     98 
     99 Blockchain.map_blocks = map_blocks

NameError: name 'chain' is not defined

Thank you for your help!

**Comment by hkalodner** [comment]
This should be fixed now. I'm surprised nobody has hit this before. This was only working for me since I always name my `Blockchain` object `chain` so it was finding the global variable rather than the `self` parameter.

**Comment by rbitr** [comment]
Hi, I'm still having this error, running ami-0650807b
