### ISSUE TITLE
BlockSci "make" fails

### ISSUE THREAD

**Issue by delgadod** [citp/BlockSci#78]
Hello,

While following the install procedure in the section

> cd ../../..
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install

"make" fails with error:

> diego@diego_tower:~/BlockSci/release$ make
[  1%] Building CXX object src/blocksci/CMakeFiles/blocksci_static.dir/address/equiv_address.cpp.o
/home/diego/BlockSci/src/blocksci/address/equiv_address.cpp: In constructor ‘blocksci::EquivAddress::EquivAddress(uint32_t, blocksci::EquivAddressType::Enum, bool, const blocksci::DataAccess&)’:
/home/diego/BlockSci/src/blocksci/address/equiv_address.cpp:34:40: error: use of ‘type’ before deduction of ‘auto’
     for (auto type : equivAddressTypes(type)) {
                                        ^
/home/diego/BlockSci/src/blocksci/address/equiv_address.cpp: At global scope:
/home/diego/BlockSci/src/blocksci/address/equiv_address.cpp:33:71: warning: unused parameter ‘type’ [-Wunused-parameter]
 EquivAddress::EquivAddress(uint32_t scriptNum, EquivAddressType::Enum type, bool scriptEquivalent_, const DataAccess &access_) : scriptEquivalent(scriptEquivalent_), access(access_) {
                                                                       ^
src/blocksci/CMakeFiles/blocksci_static.dir/build.make:206: recipe for target 'src/blocksci/CMakeFiles/blocksci_static.dir/address/equiv_address.cpp.o' failed
make[2]: *** [src/blocksci/CMakeFiles/blocksci_static.dir/address/equiv_address.cpp.o] Error 1
CMakeFiles/Makefile2:159: recipe for target 'src/blocksci/CMakeFiles/blocksci_static.dir/all' failed
make[1]: *** [src/blocksci/CMakeFiles/blocksci_static.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by delgadod** [comment]
I seem to be having the same issue as #79 

![blocksci_make_fail](https://user-images.githubusercontent.com/25486506/38220726-d4cd4e9a-36a9-11e8-830a-4ffd28158cb2.png)

**Comment by hkalodner** [comment]
This is now resolved. I'm not sure why this was an error in older compilers, but not in the latest gcc and clang. The problem was that it was misunderstanding that there were two variables with the same name.
