### ISSUE TITLE
BlockSci make fails

### ISSUE THREAD

**Issue by sweyn** [citp/BlockSci#79]
On Ubuntu 16.04 LTS:

cd ../../..
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install

$:   make
[ 36%] Built target blocksci_static
[ 36%] Linking CXX shared library libblocksci.so
/usr/bin/ld: /usr/local/lib/librocksdb.a(db_impl.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/librocksdb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/blocksci/CMakeFiles/blocksci.dir/build.make:1327: recipe for target 'src/blocksci/libblocksci.so...' failed
make[2]: *** [src/blocksci/libblocksci.so...] Error 1
CMakeFiles/Makefile2:196: recipe for target 'src/blocksci/CMakeFiles/blocksci.dir/all' failed
make[1]: *** [src/blocksci/CMakeFiles/blocksci.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
$:

**Comment by hkalodner** [comment]
Hi @sweyn,

I think this is a problem with the rocksdb install. Did you do both `make static_lib` and `make shared_lib` when installing rocksdb?

**Comment by sweyn** [comment]
@hkalodner  Apparently, I did not `make static_lib` for rocksdb, blocksci compiles without error after I corrected that mistake. Mea culpa, pardon the inconvenience, and thanks for the tip.

**Comment by hkalodner** [comment]
No problem @sweyn. One of the things I'm working on for the next release is cleaning up the build experience. It's currently pretty messy. Glad that it's working for you now!
