### ISSUE TITLE
List of Txes to Tx Range

### ISSUE THREAD

**Issue by mosessoh** [citp/BlockSci#83]
Tx Range object in the Python API exposes the `all()` function that gives us a list of all the Tx objects in the Tx Range. Is there a method that allows us to go from a list of Tx objects to a Tx Range? I could not find one in the documentation.

**Comment by hkalodner** [comment]
There's currently no way to do this, but I'd definitely consider adding this in a future version. We could provide something similar to numpy's `np.asarray`interface.
