### ISSUE TITLE
blocksci_parser : dogecoin : both disk and rpc fail

### ISSUE THREAD

**Issue by StephenHarrington** [citp/BlockSci#86]
Has anyone successfully parsed dogecoin?  I have a full node running with txindex=1 in the dogecoin.conf file.  

Trying disk update (with fully qualified paths not shown) yields:

```
blocksci_parser --output-directory dogecoin update --max-block -6 disk --coin-directory .dogecoin

100.0% done fetching block headers
Starting with chain of 0 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
Updating address index
Updating index with scripts of type multisig_script

```
And then exits

Using rpc mode:

```
blocksci_parser --output-directory dogecoin update rpc --username XXXX --password XXXXXXXX --port 6332
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted (core dumped)

```

I have been able to parse other coins - e.g. litecoin with disk mode and namecoin with rpc mode.

Anyone successfully parse dogecoin?  Any other experiences with parsing other altcoins with blocksci?

Thanks!

**Comment by hkalodner** [comment]
I need to check this, but there might be a compatibility problem with compatibility first running the disk parser and then the roc parser with the same output directory. Could you try deleting the output directory and trying the RPC parser again?

**Comment by StephenHarrington** [comment]
This seems to be working!  My mistake, thank you for the prompt response.

**Comment by hkalodner** [comment]
Not at all, it should fail way to gracefully in this situation. I'm going to leave this open until I at least get a better error message.

**Comment by hkalodner** [comment]
This issue is now resolved. If the index is invalid or corrupted, it is deleted and a new index is generated from scratch.
