### ISSUE TITLE
How to run mempool_recorder 

### ISSUE THREAD

**Issue by snmsc** [citp/BlockSci#87]
Hi,

I think the mempool_recorder described in your working paper is not documented yet.
Could you write a few lines on how to call it and use its output? (Or refer me to where it is documented)

With Bitcoin Core running, I tried 

mempool_recorder /home/user/bitcoin-data /home/user/.bitcoin

on my local setup, which gives 

terminate called after throwing an instance of 'BitcoinException' 
what(): std:: exception
Aborted (core dumped)

Thanks again for this awesome package!

**Comment by hkalodner** [comment]
This hasn't been very well maintained and isn't working correctly. This has been fixed and integrated directly with the python library in the soon to be release BlockSci v0.5.

**Comment by snmsc** [comment]
Cool, thanks!
