### ISSUE TITLE
Its at block 371919 its parsing at 3 blk/min 

### ISSUE THREAD

**Issue by freeskaro** [citp/BlockSci#88]
Its at block 371919 its parsing at 3 blk/min. This is like ABE. Is it line by line inserts or is there another command than update? At this rate, it would take 35 days to parse. I only have 128Gb of SSD so its regular hard drive. My computer is not crap, it downloaded the whole blockchain in under 12 hrs. Is there something I am doing wrong?

**Comment by hkalodner** [comment]
It sounds like you probably don't have enough memory on your machine. 64GB is recommended although 32GB should be possible although much slower. I'm guessing you have 16GB or under?

**Comment by freeskaro** [comment]
It's not really 'designed for speed' if it needs 64GB RAM to parse the database. 
BitcoinDatabaseGenerator could parse blockchain in 12 hrs on my HP laptop with 12 GB DDR3 RAM (much slower than my linux gaming DELL I'm using for BlockSci). Its just not updated for SegWit. If you use indexed searches, its also immediate on my laptop. That's an example of speed.
https://github.com/ladimolnar/BitcoinDatabaseGenerator

**Comment by hkalodner** [comment]
BlockSci isn't designed to parse the Blockchain quickly. The parser performs a a large number of tasks when it runs to produce a format optimized for analysis. This includes UTXO normalization where it connects every input to the output it spends as well as Address normalization where it connects all outputs which send to the same address. It has been optimized to the point that it can run in about 12 hours on a 64GB machine which has been performant enough for our purposes.

The large amount of work that the parser does when generating BlockSci's binary data format allows BlockSci to minimize the amount of work that has to be done at runtime when performing analysis tasks.

Whether BlockSci is the right tool for you depends on what you are trying to achieve. BlockSci is optimized for use cases where users want to perform blockchain-wide queries which have to look at all inputs and outputs. The main benchmark I highlight is how we can calculate the maximum transaction fee every created in the entire blockchain in 1.2 seconds on a 64GB 8vCPU machine.
