### ISSUE TITLE
Inputs are missing for some old address

### ISSUE THREAD

**Issue by ClementPavue** [citp/BlockSci#89]
Hello,

I try to retrieve the inputs from an address using the cpp library and for some old address I don't get any inputs. 

```
Blockchain chain(...);
auto startingAddress = getAddressFromString("1JPJ1ij5hoNAkEX5nDiYQXgtyeC1uvvv82",chain.getAccess());

if (startingAddress) {
	auto inputs = (*startingAddress).getInputs();
	auto inpSize = inputs.size();
	std::cout << inpSize << std::endl;
}
```

According to blockchain.info there is 4 inputs. 

Is this a bug or am I missing something ?

**Comment by hkalodner** [comment]
It looks like that address has only been used as an output if I'm looking at the right thing https://blockchain.info/address/1JPJ1ij5hoNAkEX5nDiYQXgtyeC1uvvv82

**Comment by ClementPavue** [comment]
Yes my bad sorry for the noise.

**Comment by yiwesi** [comment]
Sorry for reopening, but I checked this address with python and get neither output nor input:

Output:
> Balance:  0
Equiv:  EquivAddress()
In Txes:  []
In Txes Count:  0
Ins:  []
Out Txes:  []
Out Txes count:  0
Outs:  []
Txes:  []
Type:  Pay to pubkey hash
Adress String:  1JPJ1ij5hoNAkEX5nDiYQXgtyeC1uvvv82
Find Multisigs:  []
First Tx:  Tx(len(txins)=2, len(txouts)=2, size_bytes=436, block_height=482706, tx_index=250670717)
Has been spent:  False
Pubkey:  None
Pubkeyhash:  81318bdce5fd16302429f5fa7e0d0604a07db1be
revealed TX:  None

Code:
> import blocksci
chain = blocksci.Blockchain("")
address = chain.address_from_string("1JPJ1ij5hoNAkEX5nDiYQXgtyeC1uvvv82")
print("Balance: ", address.balance())
print("Equiv: ", address.equiv())
print("In Txes: ",address.in_txes())
print("In Txes Count: ", address.in_txes_count())
print("Ins: ", address.ins())
print("Out Txes: ", address.out_txes())
print("Out Txes count: ", address.out_txes_count())
print("Outs: ", address.outs())
print("Txes: ", address.txes())
print("Type: ", address.type)
print("Adress String: ", address.address_string)
print("Find Multisigs: ", address.find_multisigs())
print("First Tx: ", address.first_tx)
print("Has been spent: ", address.has_been_spent)
print("Pubkey: ", address.pubkey)
print("Pubkeyhash: ", address.pubkeyhash)
print("revealed TX: ", address.revealed_tx)

What me also confuses is, that the Pubkeyhash form BlockSci is `81318bdce5fd16302429f5fa7e0d0604a07db1be` and from blockchain.info it is `beb17da004060d7efaf529243016fde5dc8b3181`
