### ISSUE TITLE
Version of a Transaction

### ISSUE THREAD

**Issue by yiwesi** [citp/BlockSci#92]
Can you please add the function to get the version of a transaction.
For example: This [transaction ](https://blockchair.com/bitcoin/transaction/aeab1893b4f859c4f4ffa486b1cfa45761ea6aad550576a58de06e73ece7fb5f) have version 1
and this [transaction](https://blockchair.com/bitcoin/transaction/b7022124bc7f31af9342d2f7af98ad9f60f2fd4fa544bf1affca8a436aadda41) have version 2.

I tried to implement it by myself but for this [transaction ](https://blockchair.com/bitcoin/transaction/aeab1893b4f859c4f4ffa486b1cfa45761ea6aad550576a58de06e73ece7fb5f) I get `10911` back and for this [transaction ](https://blockchair.com/bitcoin/transaction/aeab1893b4f859c4f4ffa486b1cfa45761ea6aad550576a58de06e73ece7fb5f) I get `6658` back.

**Comment by hkalodner** [comment]
This isn't currently recorded by the parser. I'd be happy to add this in the next version with a parser update.

**Comment by yiwesi** [comment]
When is this to be exptected to be implemented?
