### ISSUE TITLE
Add cluster.index method

### ISSUE THREAD

**Issue by snmsc** [citp/BlockSci#93]
Hi,

I think a cluster.index method that gives an ID for a cluster could be helpful.

As in issue #75  and #81, I can't loop over clusters and their outputs because some clusters have to many outputs and blow up my memory (64GB). So I'm looping over transactions and getting the cluster of an address. But that means I need to hold a Cluster - ID dictionary in memory...

**Comment by hkalodner** [comment]
This should already be available as `cluster. cluster_num`. I think you're right it would be better renamed to `cluster.index`.

Btw in the soon to be released next version, `cluster.outs()` will produce an iterable so you'll be able to do this more directly.

**Comment by snmsc** [comment]
Ah, awesome! Thanks!
