### ISSUE TITLE
Getting address of Tx on Dash testnet

### ISSUE THREAD

**Issue by heojae91** [citp/BlockSci#94]
Hello,
I'm doing some test of Dash on testnet, but it generates bitcoin-like address such as "17HGVKGNHUW2TYoC3jrEf2rSV6Xeyd7NuM" which starts with 1. But, address of Dash-testnet starts with "y" such as "yPwTggY8JEFaDjAgUdHmapG4SmzY6SDbE9".

I think the reason is that the magic value in Dash testnet is different from Dash mainnet. The magic value in mainnet is 76, and in testnet is 140 (https://dashpay.atlassian.net/wiki/spaces/DOC/pages/47742983/Testnet).

**Comment by hkalodner** [comment]
I've added support for this in the working branch for the next version which should be released very soon. Currently blocksci identifies which chain to use the prefixes for based on the folder name. Dash Testnet will be chosen if the BlockSci data fold is named dash_testnet.
